/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
*/

//! Integration tests for the UnionFlat iterator variants.
//!
//! Most tests live in the shared [`union_common_tests!`] macro. This file only
//! contains implementation-specific tests that assert on internal observability
//! counters (e.g. `read_count()`) whose values differ between Flat and Heap.

// Shared behavioral tests generated by the macro.
mod common {
    use rqe_iterators::{UnionFullFlat, UnionQuickFlat};
    union_common_tests!(UnionFullFlat, UnionQuickFlat);
}

use crate::utils::{Mock, MockRevalidateResult, create_mock_2, create_mock_3};
use rqe_iterators::{RQEIterator, UnionFullFlat, UnionQuickFlat};

// =============================================================================
// Implementation-specific tests (read_count assertions differ between Flat and Heap)
// =============================================================================

#[test]
#[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
fn reuse_results_optimization_quick_mode() {
    let (children, data) = create_mock_2([3], [2]);
    let mut union = UnionQuickFlat::new(children);

    let result = union
        .read()
        .expect("read failed")
        .expect("should have result");
    assert_eq!(result.doc_id, 2);
    assert_eq!(
        data[0].read_count(),
        1,
        "child0 should be read once for initial heap setup"
    );
    assert_eq!(
        data[1].read_count(),
        1,
        "child1 should be read once for initial heap setup"
    );

    let result = union
        .read()
        .expect("read failed")
        .expect("should have result");
    assert_eq!(result.doc_id, 3);
    assert_eq!(
        data[0].read_count(),
        1,
        "child0 should NOT be re-read (reuse optimization)"
    );
    assert_eq!(
        data[1].read_count(),
        1,
        "child1 was at doc 2, should NOT be re-read (quick mode returns first match)"
    );

    let result = union.read().expect("read failed");
    assert!(result.is_none());
    assert_eq!(
        data[0].read_count(),
        2,
        "child0 should now be read to discover EOF"
    );
    assert_eq!(
        data[1].read_count(),
        2,
        "child1 should now be read to discover EOF"
    );
}

// =============================================================================
// into_trimmed
// =============================================================================

/// `into_children` returns all children that were passed to the constructor.
#[test]
fn into_children_returns_all_children() {
    let (children, _data) = create_mock_3([1, 2], [3, 4], [5, 6]);
    let mut recovered = UnionFullFlat::new(children).into_children();
    assert_eq!(recovered.len(), 3);

    let mut docs: Vec<Vec<u64>> = recovered
        .iter_mut()
        .map(|c| std::iter::from_fn(|| c.read().unwrap().map(|r| r.doc_id)).collect::<Vec<_>>())
        .collect();
    // The order is not a strong contract so we sort again.
    docs.sort_unstable();
    assert_eq!(docs, [[1, 2], [3, 4], [5, 6]]);
}

/// `into_trimmed` on a `UnionFullFlat` produces a working `UnionTrimmed` that
/// yields all children in reverse order when the limit is large enough.
#[test]
#[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
fn into_trimmed_full_flat_yields_all_children() {
    let (children, _data) = create_mock_3([1, 2], [3, 4], [5, 6]);
    let union = UnionFullFlat::new(children);
    let mut trimmed = union.into_trimmed(usize::MAX, true).unwrap();

    // UnionTrimmed drains children last-to-first.
    let mut docs = Vec::new();
    while let Some(r) = trimmed.read().unwrap() {
        docs.push(r.doc_id);
    }
    assert_eq!(docs, [5, 6, 3, 4, 1, 2]);
}

/// `into_trimmed` on a `UnionQuickFlat` applies trimming correctly.
#[test]
#[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
fn into_trimmed_quick_flat_trims_asc() {
    // 3 children with est [2, 2, 2], limit=1.
    // Asc scan from child[1]: child[1].est=2 > 1 → keep=2.
    let (children, _data) = create_mock_3([1, 2], [3, 4], [5, 6]);
    let union = UnionQuickFlat::new(children);
    let mut trimmed = union.into_trimmed(1, true).unwrap();

    assert_eq!(trimmed.num_children_total(), 3, "all children stay alive");
    let mut docs = Vec::new();
    while let Some(r) = trimmed.read().unwrap() {
        docs.push(r.doc_id);
    }
    // Active window [0..2), reads in reverse: child[1] then child[0].
    assert_eq!(docs, [3, 4, 1, 2]);
}

#[test]
fn union_full_flat_upholds_current_contract() {
    use rqe_iterators_test_utils::{assert_current_contract, assert_current_contract_via_skip_to};
    let children: Vec<Box<dyn RQEIterator<'static>>> = vec![
        Box::new(crate::utils::Mock::new([1u64, 3])),
        Box::new(crate::utils::Mock::new([2u64, 4])),
    ];
    let mut it = UnionFullFlat::new(children);
    assert_eq!(assert_current_contract(&mut it), [1, 2, 3, 4]);
    assert_current_contract_via_skip_to(&mut it, 5);
}

/// `skip_to_quick` returns on the first exact match, so a later sibling can still
/// be unread after many reads. A revalidation must not read that child's
/// `last_doc_id() == 0` as a position: doc 0 sorts ahead of every real id, so the
/// union would report a document no index holds and move *backwards*, handing a
/// parent documents it has already been given.
#[test]
#[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
fn revalidate_with_an_unread_sibling_does_not_move_the_union_backwards() {
    // child0 holds the probe target, so the early return never reaches child1.
    let matching: Mock<'static, 3> = Mock::new([10, 20, 30]);
    let mut matching_data = matching.data();
    let untouched: Mock<'static, 2> = Mock::new([15, 25]);
    let untouched_data = untouched.data();

    let children: Vec<Box<dyn RQEIterator<'static>>> =
        vec![Box::new(matching), Box::new(untouched)];
    let mut it = UnionQuickFlat::new(children);

    let outcome = it
        .skip_to(10)
        .expect("skip_to must not fail")
        .expect("10 is present");
    match outcome {
        rqe_iterators::SkipToOutcome::Found(r) | rqe_iterators::SkipToOutcome::NotFound(r) => {
            assert_eq!(r.doc_id, 10)
        }
    }
    assert_eq!(it.last_doc_id(), 10);
    assert_eq!(
        untouched_data.read_count(),
        0,
        "the early return is what leaves this child unread — the premise of the test",
    );

    matching_data.set_revalidate_result(MockRevalidateResult::Move);
    let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
    let status = it
        .revalidate(&*mock_ctx.spec_read())
        .expect("revalidate must not fail");

    // A `Moved` result is the union's current document and is consumed from here
    // rather than by the next read, so it counts as delivered.
    let mut seen = Vec::new();
    if let rqe_iterators::RQEValidateStatus::Moved {
        current: Some(result),
    } = &status
    {
        assert_ne!(result.doc_id, 0, "doc 0 is not a document");
        seen.push(result.doc_id);
    }
    assert!(
        it.last_doc_id() >= 10,
        "the union must not move behind the document it already yielded, got {}",
        it.last_doc_id(),
    );

    // The unread sibling's documents are still owed, so none may be skipped over.
    while let Some(r) = it.read().expect("read must not fail") {
        seen.push(r.doc_id);
    }
    assert!(
        seen.iter().all(|id| *id > 10),
        "nothing already yielded may be handed back: {seen:?}",
    );
    assert!(
        seen.contains(&15),
        "the unread sibling's 15 is still owed and must not be skipped: {seen:?}",
    );
}

mod via_resume {
    use crate::utils::{Mock, MockRevalidateResult};
    use rqe_iterators::{RQEIterator, ResumeOutcome, TypeErasedRQEIterator, UnionFullFlat};
    use rqe_iterators_test_utils::{ResumeOutcomeExt, revalidate_via_resume};

    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn revalidate_ok() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 5> = Mock::new([10, 20, 30, 40, 50]);
        let child1: Mock<'_, 5> = Mock::new([15, 25, 35, 45, 55]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullFlat::new(children);

        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 10);
        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 15);

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();

        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 20);
    }

    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn revalidate_moved() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 5> = Mock::new([10, 20, 30, 40, 50]);
        let child1: Mock<'_, 5> = Mock::new([15, 25, 35, 45, 55]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Move);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Move);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullFlat::new(children);

        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 10);

        let guard = mock_ctx.spec_read();
        let union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_moved();
        // After Move, children advance — last_doc_id should reflect new min.
        assert!(union.last_doc_id() > 10);
    }

    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn revalidate_single_child_aborts() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 5> = Mock::new([10, 20, 30, 40, 50]);
        let child1: Mock<'_, 5> = Mock::new([15, 25, 35, 45, 55]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Abort);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullFlat::new(children);

        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 10);

        let guard = mock_ctx.spec_read();
        // One child aborted, the other survives — union continues (Ok or Moved).
        let mut union =
            match revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
                .expect("resume failed")
            {
                ResumeOutcome::Ok(it) | ResumeOutcome::Moved(it) => it,
                ResumeOutcome::Aborted => {
                    panic!("Expected MOVED or OK when one child aborts, got Aborted")
                }
            };
        // Reads from the surviving child should continue.
        let r = union.read().unwrap().unwrap();
        assert!(r.doc_id >= 15);
    }

    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn revalidate_all_children_abort() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 5> = Mock::new([10, 20, 30, 40, 50]);
        let child1: Mock<'_, 5> = Mock::new([15, 25, 35, 45, 55]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Abort);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Abort);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullFlat::new(children);

        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 10);

        let guard = mock_ctx.spec_read();
        let outcome = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed");
        assert!(matches!(outcome, ResumeOutcome::Aborted));
    }

    /// Phase 3.15 regression: when no child moved, the aggregate must be
    /// rebuilt at `saved_last_doc_id` so subsequent reads continue from the
    /// same logical position.
    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn revalidate_minimum_unchanged_returns_ok() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 3> = Mock::new([10, 30, 50]);
        let child1: Mock<'_, 3> = Mock::new([10, 40, 60]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullFlat::new(children);

        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 10);

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();

        // Union must continue producing the remaining children's docs.
        let r = union.read().unwrap().unwrap();
        assert!(r.doc_id > 10, "expected next doc_id > 10, got {}", r.doc_id);
    }

    /// Phase 5b.5 regression: an EOF child swap-removed into the dead tail must
    /// NOT be re-included as a live child by resume — that would yield its
    /// already-read max doc_id forever.
    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn revalidate_swap_removed_dead_tail_not_yielded_again() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        // Child 0 has a small doc set; child 1 has more docs.
        // Read past child 0's EOF so it's swap-removed into the dead tail.
        let child0: Mock<'_, 2> = Mock::new([10, 20]);
        let child1: Mock<'_, 5> = Mock::new([5, 15, 25, 35, 45]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullFlat::new(children);

        // Drain child0: 5 (c1), 10 (c0), 15 (c1), 20 (c0) — c0 now at EOF and
        // gets swap_remove_child'd next time `read()` advances past 20.
        let mut docs = Vec::new();
        for _ in 0..4 {
            docs.push(union.read().unwrap().unwrap().doc_id);
        }
        assert_eq!(docs, [5, 10, 15, 20]);
        // The next read trims child0 to the dead tail.
        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 25);

        // Now resume: child0 is in the dead tail. It must NOT re-emerge as live.
        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();

        // Continue reading: must surface the rest of child1 and never repeat 20.
        let remaining: Vec<_> =
            std::iter::from_fn(|| union.read().unwrap().map(|r| r.doc_id)).collect();
        assert_eq!(remaining, [35, 45]);
    }
}
