/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
*/

//! Integration tests for the UnionHeap iterator variants.
//!
//! Most tests live in the shared [`union_common_tests!`] macro. This file only
//! contains implementation-specific tests that assert on internal observability
//! counters (e.g. `read_count()`) whose values differ between Flat and Heap.

// Shared behavioral tests generated by the macro.
mod common {
    use rqe_iterators::{UnionFullHeap, UnionQuickHeap};
    union_common_tests!(UnionFullHeap, UnionQuickHeap);
}

use crate::utils::{Mock, MockRevalidateResult, create_mock_2, create_mock_3};
use rqe_iterators::{RQEIterator, UnionFullHeap, UnionQuickHeap};
use rqe_iterators_test_utils::ContractChecker;

// =============================================================================
// Implementation-specific tests (read_count assertions differ between Flat and Heap)
// =============================================================================

/// A revalidation before the first read rebuilds the heap while every child still
/// sits at `last_doc_id() == 0`, leaving an entry per child at doc 0. The first
/// read must not inherit those: doc 0 sorts ahead of every real id, so the union
/// would report an id no document has.
#[test]
fn revalidate_before_first_read_leaves_no_stale_heap_entries() {
    // The empty child has nothing to yield but reports not-at-EOF until something
    // reads it, so the rebuild keeps it.
    let empty: Mock<'static, 0> = Mock::new([]);
    let sibling: Mock<'static, 2> = Mock::new([5, 7]);
    let mut sibling_data = sibling.data();

    let children: Vec<Box<dyn RQEIterator<'static>>> = vec![Box::new(empty), Box::new(sibling)];
    let mut it = ContractChecker::new(UnionFullHeap::new(children));

    // A sibling aborting is what triggers the rebuild, and leaves the empty child
    // as the only one standing.
    sibling_data.set_revalidate_result(MockRevalidateResult::Abort);
    let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
    let _ = it
        .revalidate(&*mock_ctx.spec_read())
        .expect("revalidate should not fail");

    assert!(
        it.read().expect("read should not fail").is_none(),
        "nothing is left to yield, so the union must report EOF rather than doc 0",
    );
}

#[test]
fn reuse_results_optimization_quick_mode() {
    let (children, data) = create_mock_2([3], [2]);
    let mut union = ContractChecker::new(UnionQuickHeap::new(children));

    let result = union
        .read()
        .expect("read failed")
        .expect("should have result");
    assert_eq!(result.doc_id, 2);
    assert_eq!(
        data[0].read_count(),
        1,
        "child0 should be read once for initial heap setup"
    );
    assert_eq!(
        data[1].read_count(),
        1,
        "child1 should be read once for initial heap setup"
    );

    let result = union
        .read()
        .expect("read failed")
        .expect("should have result");
    assert_eq!(result.doc_id, 3);
    // In heap quick mode, read() calls skip_to(last_doc_id + 1) = skip_to(3).
    // child1 (at doc 2) is below target 3, so it gets advanced (skip_to → EOF).
    // child0 (at doc 3) is already at target, so it's reused (no extra read).
    assert_eq!(
        data[0].read_count(),
        1,
        "child0 at doc 3 matches target - reused (no read needed)"
    );
    // child1 was at doc 2 < target 3, so the heap advances it via skip_to
    // which internally calls read(), incrementing read_count.
    assert_eq!(
        data[1].read_count(),
        2,
        "child1 was at doc 2 < target 3, advanced via skip_to"
    );

    let result = union.read().expect("read failed");
    assert!(result.is_none());
    assert_eq!(
        data[0].read_count(),
        2,
        "child0 should now be read to discover EOF"
    );
    assert_eq!(
        data[1].read_count(),
        2,
        "child1 already at EOF, no additional read"
    );
}

// =============================================================================
// into_trimmed
// =============================================================================

/// `into_trimmed` on a `UnionFullHeap` produces a working `UnionTrimmed` that
/// yields all children in reverse order when the limit is large enough.
#[test]
fn into_trimmed_full_heap_yields_all_children() {
    let (children, _data) = create_mock_3([1, 2], [3, 4], [5, 6]);
    let union = UnionFullHeap::new(children);
    let mut trimmed = ContractChecker::new_unordered(union.into_trimmed(usize::MAX, true).unwrap());

    let mut docs = Vec::new();
    while let Some(r) = trimmed.read().unwrap() {
        docs.push(r.doc_id);
    }
    assert_eq!(docs, [5, 6, 3, 4, 1, 2]);
}

/// `into_children` returns all children that were passed to the constructor.
#[test]
fn into_children_returns_all_children() {
    let (children, _data) = create_mock_3([1, 2], [3, 4], [5, 6]);
    let mut recovered = UnionFullHeap::new(children).into_children();
    assert_eq!(recovered.len(), 3);

    let mut docs: Vec<Vec<u64>> = recovered
        .iter_mut()
        .map(|c| std::iter::from_fn(|| c.read().unwrap().map(|r| r.doc_id)).collect::<Vec<_>>())
        .collect();
    // The order is not a strong contract so we sort again.
    docs.sort_unstable();
    assert_eq!(docs, [[1, 2], [3, 4], [5, 6]]);
}

/// `into_trimmed` on a `UnionQuickHeap` applies trimming correctly.
#[test]
fn into_trimmed_quick_heap_trims_desc() {
    // 3 children with est [2, 2, 2], limit=1.
    // Desc scan from child[1] backward: child[1].est=2 > 1 → skip=1.
    let (children, _data) = create_mock_3([1, 2], [3, 4], [5, 6]);
    let union = UnionQuickHeap::new(children);
    let mut trimmed = ContractChecker::new_unordered(union.into_trimmed(1, false).unwrap());

    assert_eq!(
        trimmed.inner().num_children_total(),
        3,
        "all children stay alive"
    );
    let mut docs = Vec::new();
    while let Some(r) = trimmed.read().unwrap() {
        docs.push(r.doc_id);
    }
    // Active window [1..3), reads in reverse: child[2] then child[1].
    assert_eq!(docs, [5, 6, 3, 4]);
}

/// The same stale-entry problem with children that all have documents, which is
/// the damaging shape: the union emits doc 0, advances the child whose stale
/// entry it just consumed — dropping a document that child had already produced
/// during heap setup — and never converges, because a duplicate entry keeps
/// matching the id just yielded.
///
/// One child has to still be unread when the rebuild runs, so only the sibling
/// reports `Moved` (which advances a `Mock` onto its first document).
///
/// The drain is bounded so a regression fails on the assertion below rather than
/// spinning until the harness kills it.
#[test]
fn revalidate_before_first_read_keeps_every_document_of_non_empty_children() {
    let moved: Mock<'static, 2> = Mock::new([5, 7]);
    let mut moved_data = moved.data();
    let untouched: Mock<'static, 2> = Mock::new([6, 8]);

    let children: Vec<Box<dyn RQEIterator<'static>>> = vec![Box::new(moved), Box::new(untouched)];
    let mut it = ContractChecker::new(UnionFullHeap::new(children));

    // `Moved` triggers the rebuild and leaves this child on doc 5, while the
    // sibling stays at `last_doc_id() == 0` — the entry that would go stale.
    moved_data.set_revalidate_result(MockRevalidateResult::Move);
    let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
    let _ = it
        .revalidate(&*mock_ctx.spec_read())
        .expect("revalidate should not fail");

    // One more than the 4 documents on offer, so an iterator that fails to
    // converge is caught rather than drained forever.
    const MAX_READS: usize = 5;
    let mut doc_ids = Vec::new();
    for _ in 0..MAX_READS {
        match it.read().expect("read should not fail") {
            Some(result) => doc_ids.push(result.doc_id),
            None => break,
        }
    }

    assert_eq!(
        doc_ids,
        vec![5, 6, 7, 8],
        "the union must yield both children in full: no doc 0 ahead of them, no \
         document dropped by a stale entry advancing a child twice, and no id \
         repeated by a duplicate entry",
    );
}

/// The active-child count is derived from the same pass that seeds the heap.
///
/// A pre-read revalidation can move a child onto its last document, which under a
/// look-ahead `at_eof()` excludes it from `rebuild_heap` and from the count taken
/// from that heap — while the reseed below legitimately puts it back. A count left
/// over from the smaller heap then runs past zero as children exhaust, which
/// panics in debug and wraps into a nonsense sort weight in release.
#[test]
fn revalidate_before_first_read_keeps_the_active_count_in_step_with_the_heap() {
    // One document, so `Moved` leaves this child on its last one.
    let moved: Mock<'static, 1> = Mock::new([5]);
    let mut moved_data = moved.data();
    let other: Mock<'static, 2> = Mock::new([6, 8]);

    let children: Vec<Box<dyn RQEIterator<'static>>> = vec![Box::new(moved), Box::new(other)];
    let mut it = ContractChecker::new(UnionFullHeap::new(children));
    assert_eq!(it.inner().num_children_active(), 2);

    moved_data.set_revalidate_result(MockRevalidateResult::Move);
    let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
    let _ = it
        .revalidate(&*mock_ctx.spec_read())
        .expect("revalidate should not fail");

    // One more than the 3 documents on offer, so a non-converging iterator is
    // caught rather than drained forever.
    const MAX_READS: usize = 4;
    let mut doc_ids = Vec::new();
    for _ in 0..MAX_READS {
        match it.read().expect("read should not fail") {
            Some(result) => doc_ids.push(result.doc_id),
            None => break,
        }
    }

    assert_eq!(doc_ids, vec![5, 6, 8], "every document, once, in order");
    assert_eq!(
        it.inner().num_children_active(),
        0,
        "both children are exhausted, and the count reached zero by counting them \
         rather than by wrapping past it",
    );
}

#[test]
fn union_full_heap_upholds_current_contract() {
    use rqe_iterators_test_utils::{assert_current_contract, assert_current_contract_via_skip_to};
    let children: Vec<Box<dyn RQEIterator<'static>>> = vec![
        Box::new(Mock::new([1u64, 3])),
        Box::new(Mock::new([2u64, 4])),
    ];
    let mut it = ContractChecker::new(UnionFullHeap::new(children));
    assert_eq!(assert_current_contract(&mut it), [1, 2, 3, 4]);
    assert_current_contract_via_skip_to(&mut it, 5);
}

mod via_resume {
    use crate::utils::{Mock, MockIteratorError, MockRevalidateResult};
    use rqe_core::DocId;
    use rqe_iterators::{
        RQEIterator, RQEIteratorBoxed, RQEIteratorError, RQESuspendedIterator, RQEValidateStatus,
        ResumeOutcome, TypeErasedRQEIterator, UnionFullHeap, UnionHeap, UnionQuickHeap,
    };
    use rqe_iterators_test_utils::{ResumeOutcomeExt, revalidate_via_resume};

    /// Read `it` to completion, collecting the doc ids it yields.
    fn drain<'index>(it: &mut impl RQEIterator<'index>) -> Vec<DocId> {
        let mut seen = Vec::new();
        while let Some(doc) = it.read().expect("read failed") {
            seen.push(doc.doc_id);
        }
        seen
    }

    /// Wrap three mocks as the type-erased children a composite really holds:
    /// their active and suspended forms carry different vtables, which a
    /// concrete-child test cannot exercise.
    fn boxed_children<'spec, const N0: usize, const N1: usize, const N2: usize>(
        c0: Mock<'spec, N0>,
        c1: Mock<'spec, N1>,
        c2: Mock<'spec, N2>,
    ) -> Vec<TypeErasedRQEIterator<'spec>> {
        vec![
            TypeErasedRQEIterator::new(Box::new(c0)),
            TypeErasedRQEIterator::new(Box::new(c1)),
            TypeErasedRQEIterator::new(Box::new(c2)),
        ]
    }

    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn revalidate_ok() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 5> = Mock::new([10, 20, 30, 40, 50]);
        let child1: Mock<'_, 5> = Mock::new([15, 25, 35, 45, 55]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullHeap::new(children);

        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 10);
        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 15);

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();

        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 20);
    }

    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn revalidate_moved() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 5> = Mock::new([10, 20, 30, 40, 50]);
        let child1: Mock<'_, 5> = Mock::new([15, 25, 35, 45, 55]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Move);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Move);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullHeap::new(children);

        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 10);

        let guard = mock_ctx.spec_read();
        let union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_moved();
        assert!(union.last_doc_id() > 10);
    }

    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn revalidate_single_child_aborts() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 5> = Mock::new([10, 20, 30, 40, 50]);
        let child1: Mock<'_, 5> = Mock::new([15, 25, 35, 45, 55]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Abort);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullHeap::new(children);

        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 10);

        let guard = mock_ctx.spec_read();
        let mut union =
            match revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
                .expect("resume failed")
            {
                ResumeOutcome::Ok(it) | ResumeOutcome::Moved(it) => it,
                ResumeOutcome::Aborted => {
                    panic!("Expected MOVED or OK when one child aborts, got Aborted")
                }
            };
        let r = union.read().unwrap().unwrap();
        assert!(r.doc_id >= 15);
    }

    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn revalidate_all_children_abort() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 5> = Mock::new([10, 20, 30, 40, 50]);
        let child1: Mock<'_, 5> = Mock::new([15, 25, 35, 45, 55]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Abort);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Abort);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullHeap::new(children);

        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 10);

        let guard = mock_ctx.spec_read();
        let outcome = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed");
        assert!(matches!(outcome, ResumeOutcome::Aborted));
    }

    /// Phase 3.17 regression: when no child moved, rebuild aggregate at the
    /// previous saved position (no skip_to shortcut).
    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn revalidate_minimum_unchanged_returns_ok() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 3> = Mock::new([10, 30, 50]);
        let child1: Mock<'_, 3> = Mock::new([10, 40, 60]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullHeap::new(children);

        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 10);

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();

        let r = union.read().unwrap().unwrap();
        assert!(r.doc_id > 10, "expected next doc_id > 10, got {}", r.doc_id);
    }

    /// Phase 5b.5 regression: an EOF child dropped from the heap must NOT be
    /// re-inserted into it by resume — it would yield its already-read max
    /// doc_id forever.
    ///
    /// The *surviving* child has to move, or `any_change` stays false and
    /// `resume` returns before `rebuild_heap` runs at all: the heap would then
    /// be carried over untouched and the re-admission filter this test is about
    /// (`rebuild_heap`'s `!child.at_eof()`) would never be reached.
    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn revalidate_swap_removed_dead_tail_not_yielded_again() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 2> = Mock::new([10, 20]);
        let child1: Mock<'_, 5> = Mock::new([5, 15, 25, 35, 45]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Move);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullHeap::new(children);

        let mut docs = Vec::new();
        for _ in 0..4 {
            docs.push(union.read().unwrap().unwrap().doc_id);
        }
        assert_eq!(docs, [5, 10, 15, 20]);
        // The next read runs child0 past its last document, dropping it from
        // the heap while it stays in the children vector.
        let r = union.read().unwrap().unwrap();
        assert_eq!(r.doc_id, 25);

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_moved();
        assert_eq!(
            union.last_doc_id(),
            35,
            "only the surviving child backs the union's new position",
        );

        let remaining: Vec<_> =
            std::iter::from_fn(|| union.read().unwrap().map(|r| r.doc_id)).collect();
        assert_eq!(remaining, [45], "child0's 20 must not come back");
    }

    /// The same dead-tail child, but *aborting*: the compaction that removes it
    /// shifts the survivor down to slot 0, invalidating every `child_idx` the
    /// heap still caches. Only the `rebuild_heap` that follows re-derives them,
    /// so a resume that reused the carried-over heap would index a child that no
    /// longer lives there.
    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn resume_compacts_over_an_aborted_dead_tail_child() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 2> = Mock::new([10, 20]);
        let child1: Mock<'_, 5> = Mock::new([5, 15, 25, 35, 45]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Abort);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullHeap::new(children);

        let mut docs = Vec::new();
        for _ in 0..5 {
            docs.push(union.read().unwrap().unwrap().doc_id);
        }
        assert_eq!(docs, [5, 10, 15, 20, 25]);

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();
        assert_eq!(
            union.last_doc_id(),
            25,
            "the survivor still sits on the union's document",
        );
        assert_eq!(drain(&mut union), [35, 45]);
    }

    /// `resume` hands the aggregate back across the cycle rather than rebuilding
    /// it, so every entry must still *reach* its child afterwards. Every other
    /// `Ok`-path test reads first, which resets and rebuilds the aggregate, so a
    /// broken entry would be overwritten before anything read it. Dereference
    /// every entry here instead, in the window between the resume and the next
    /// read — the window a scorer walking `current()` occupies in production.
    ///
    /// Run under miri this is also the regression test for the entries'
    /// *provenance*, which is the half a plain read cannot see: the addresses
    /// survive a child's transition on their own, the borrows they were derived
    /// from do not, and only `resume`'s re-derivation of the entries makes them
    /// usable rather than merely well-addressed. The twin of
    /// `union_flat::via_resume::resume_ok_leaves_the_aggregate_pointing_at_live_children`.
    #[test]
    fn resume_ok_leaves_the_aggregate_pointing_at_live_children() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        // All three children start on 10, so all three back the aggregate.
        let child0: Mock<'_, 3> = Mock::new([10, 40, 70]);
        let child1: Mock<'_, 3> = Mock::new([10, 50, 80]);
        let child2: Mock<'_, 3> = Mock::new([10, 60, 90]);
        // Nothing moves, so `resume` carries the aggregate across untouched —
        // the case its liveness obligation rests on entirely.
        for data in [child0.data(), child1.data(), child2.data()].iter_mut() {
            data.set_revalidate_result(MockRevalidateResult::Ok);
        }

        let mut union = UnionFullHeap::new(boxed_children(child0, child1, child2));
        assert_eq!(union.read().unwrap().unwrap().doc_id, 10);

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();

        let current = union
            .current()
            .expect("an unchanged union is still positioned");
        assert_eq!(current.doc_id, 10);
        let aggregate = current
            .as_aggregate()
            .expect("a full union publishes an aggregate result");
        assert_eq!(aggregate.len(), 3, "one entry per child on the document");
        for i in 0..aggregate.len() {
            let entry = aggregate.get(i).expect("index below len");
            assert_eq!(
                entry.doc_id, 10,
                "entry {i} must still reach its child's live result",
            );
        }

        // Only now let a read rebuild the aggregate from scratch.
        assert_eq!(union.read().unwrap().unwrap().doc_id, 40);
    }

    /// The rebuild recomputes `freq` and `field_mask` from the children it
    /// re-pushes, so a published union never claims a frequency or a set of
    /// fields that its own entries do not account for. `field_mask` is the one
    /// that bites if it drifts — it decides field filtering and field-weighted
    /// scoring, so an over-broad mask lets a document through a filter no live
    /// child matches.
    ///
    /// Asserted as agreement between the result and its entries rather than
    /// against literals, because that is the invariant: whatever the children
    /// hold, the two must say the same thing.
    #[test]
    fn resume_leaves_the_aggregate_agreeing_with_its_entries() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        // Two children on the union's document and one past it, so the rebuild
        // has to *select* rather than re-push everything it is handed.
        let child0: Mock<'_, 2> = Mock::new([10, 40]);
        let child1: Mock<'_, 2> = Mock::new([10, 50]);
        let child2: Mock<'_, 2> = Mock::new([20, 60]);
        for data in [child0.data(), child1.data(), child2.data()].iter_mut() {
            data.set_revalidate_result(MockRevalidateResult::Ok);
        }

        let mut union = UnionFullHeap::new(boxed_children(child0, child1, child2));
        assert_eq!(union.read().unwrap().unwrap().doc_id, 10);

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();

        let current = union
            .current()
            .expect("an unchanged union is still positioned");
        let aggregate = current
            .as_aggregate()
            .expect("a full union publishes an aggregate result");
        assert_eq!(
            aggregate.len(),
            2,
            "only the children sitting on doc 10 back the result",
        );

        let mut freq = 0;
        let mut field_mask = 0;
        for i in 0..aggregate.len() {
            let entry = aggregate.get(i).expect("index below len");
            assert_eq!(entry.doc_id, 10, "entry {i} is on the union's document");
            freq += entry.freq;
            field_mask |= entry.field_mask;
        }
        assert_eq!(current.freq, freq, "freq must be the sum over the entries");
        assert_eq!(
            current.field_mask, field_mask,
            "field_mask must be the union over the entries",
        );
    }

    /// Metrics survive the rebuild, because they cannot be rebuilt.
    ///
    /// Unlike `freq` and `field_mask`, which are copied from each child,
    /// `RSIndexResult::push_borrowed` **moves** a child's metrics into the
    /// aggregate — so by the time a resume runs, the children hold none and
    /// there is nothing to re-accumulate. The rebuild therefore clears the
    /// records alone and carries `metrics` across; reaching for
    /// `reset_aggregate` instead would read as tidier and would discard them for
    /// good, taking `__vector_score` out of a hybrid query's reply on every
    /// suspend/resume cycle.
    #[test]
    fn resume_keeps_the_metrics_the_aggregate_gathered() {
        use rqe_iterators::metric::MetricSortedById;

        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let scored = MetricSortedById::new(vec![100u64], vec![0.5]);
        let sibling: Mock<'_, 2> = Mock::new([100, 200]);
        sibling
            .data()
            .set_revalidate_result(MockRevalidateResult::Ok);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(scored)),
            TypeErasedRQEIterator::new(Box::new(sibling)),
        ];
        let mut union = UnionFullHeap::new(children);
        let first = union.read().expect("read failed").expect("doc 100");
        assert_eq!(first.doc_id, 100);
        assert_eq!(
            first.metrics.len(),
            1,
            "the aggregate gathered the scored child's metric",
        );

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();

        let current = union.current().expect("still on doc 100");
        assert_eq!(current.doc_id, 100);
        assert_eq!(
            current.metrics.len(),
            1,
            "the metric must survive a rebuild of the document it was gathered for",
        );
    }

    /// A quick union reports a single child, so the rebuild stops at the first
    /// one it finds on the union's document rather than aggregating every match.
    ///
    /// Which child that is deliberately goes unasserted: the rebuild picks by
    /// slot where the read path picks by heap order, and any child on the
    /// document backs the position equally — the same latitude the settle takes
    /// when it re-picks a backer after its children moved. What must hold is
    /// that there is exactly one entry and it is on the union's document.
    #[test]
    fn quick_resume_republishes_a_single_backer() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        // All three on doc 10, so a rebuild that aggregated would show three.
        let child0: Mock<'_, 2> = Mock::new([10, 40]);
        let child1: Mock<'_, 2> = Mock::new([10, 50]);
        let child2: Mock<'_, 2> = Mock::new([10, 60]);
        for data in [child0.data(), child1.data(), child2.data()].iter_mut() {
            data.set_revalidate_result(MockRevalidateResult::Ok);
        }

        let mut union = UnionQuickHeap::new(boxed_children(child0, child1, child2));
        assert_eq!(union.read().unwrap().unwrap().doc_id, 10);

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();

        let current = union
            .current()
            .expect("an unchanged union is still positioned");
        assert_eq!(current.doc_id, 10);
        let aggregate = current
            .as_aggregate()
            .expect("a quick union still publishes an aggregate result");
        assert_eq!(aggregate.len(), 1, "quick mode reports one child, not all");
        assert_eq!(
            aggregate.get(0).expect("one entry").doc_id,
            10,
            "the backer must sit on the union's document",
        );
    }

    /// The suspend/resume cycle must reuse the allocation: the FFI wrapper and
    /// delegating parents cache raw pointers into the iterator's storage, and a
    /// rebuilt box would dangle them.
    #[test]
    fn resume_preserves_box_address() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let guard = mock_ctx.spec_read();
        let children = vec![Mock::new([10u64, 30]), Mock::new([20u64, 40])];
        let mut union = Box::new(UnionFullHeap::new(children));
        let r = union.read().expect("read failed").expect("expected doc");
        assert_eq!(r.doc_id, 10);
        let addr_before = &*union as *const _ as usize;

        let suspended = union.suspend();
        assert_eq!(
            &*suspended as *const _ as usize, addr_before,
            "suspend must reuse the allocation",
        );
        let mut active = match suspended.resume(&guard).expect("resume failed") {
            ResumeOutcome::Ok(a) => a,
            ResumeOutcome::Moved(_) => panic!("expected Ok, got Moved"),
            ResumeOutcome::Aborted => panic!("expected Ok, got Aborted"),
        };
        assert_eq!(
            &*active as *const _ as usize, addr_before,
            "resume must reuse the allocation",
        );

        let r = active.read().expect("read failed").expect("expected doc");
        assert_eq!(r.doc_id, 20, "the union carries on where it was");
    }

    /// A child whose resume *fails* takes the union down the
    /// `free_after_consumed_child` teardown, the most delicate unsafe in this
    /// file: it drops the compacted resumed prefix, leaves the consumed slot
    /// alone, and drops the still-suspended tail. Get the `kept`/`consumed`
    /// boundary wrong and it is a double free or a leak, both of which miri
    /// sees through the mocks' reference-counted state.
    ///
    /// This is the plain shape: no child aborted first, so `kept == consumed`
    /// and the buffer is a resumed prefix, the consumed slot, and a suspended
    /// tail — all three regions at once.
    #[test]
    fn resume_child_error_frees_a_shell_with_a_suspended_tail() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let guard = mock_ctx.spec_read();
        let child0: Mock<'_, 3> = Mock::new([10, 40, 70]);
        let child1: Mock<'_, 3> = Mock::new([20, 50, 80]);
        let child2: Mock<'_, 3> = Mock::new([30, 60, 90]);
        child1
            .data()
            .set_error_on_resume(Some(MockIteratorError::TimeoutError(None)));

        let mut union = UnionFullHeap::new(boxed_children(child0, child1, child2));
        assert_eq!(union.read().unwrap().unwrap().doc_id, 10);

        match revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard) {
            Err(e) => assert!(matches!(e, RQEIteratorError::TimedOut)),
            Ok(_) => panic!("the failing child's error must reach the caller"),
        }
    }

    /// The same teardown, but with a hole in the middle: child 0 aborts before
    /// child 2 fails, so the survivor is compacted down to slot 0 and `kept`
    /// (1) trails `consumed` (2). Slot 1 is then a vacated hole that the
    /// teardown must skip — the clause the plain shape never reaches.
    #[test]
    fn resume_child_error_frees_a_shell_with_a_hole_in_it() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let guard = mock_ctx.spec_read();
        let child0: Mock<'_, 3> = Mock::new([10, 40, 70]);
        let child1: Mock<'_, 3> = Mock::new([20, 50, 80]);
        let child2: Mock<'_, 3> = Mock::new([30, 60, 90]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Abort);
        child2
            .data()
            .set_error_on_resume(Some(MockIteratorError::TimeoutError(None)));

        let mut union = UnionFullHeap::new(boxed_children(child0, child1, child2));
        assert_eq!(union.read().unwrap().unwrap().doc_id, 10);

        match revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard) {
            Err(e) => assert!(matches!(e, RQEIteratorError::TimedOut)),
            Ok(_) => panic!("the failing child's error must reach the caller"),
        }
    }

    /// A `Moved` that changes *which* child is the minimum, which is what makes
    /// the post-resume `rebuild_heap` more than a formality. Both children
    /// advance, but child 0 jumps past child 1: the root has to change hands, so
    /// a re-sift that is merely partial or mis-ordered — not just an absent one —
    /// surfaces as the wrong position.
    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn resume_moved_resifts_the_heap_when_the_root_changes_child() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 2> = Mock::new([10, 100]);
        let child1: Mock<'_, 2> = Mock::new([15, 20]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Move);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Move);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullHeap::new(children);
        assert_eq!(
            union.read().unwrap().unwrap().doc_id,
            10,
            "child 0 starts out as the root",
        );

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_moved();
        assert_eq!(
            union.last_doc_id(),
            20,
            "child 1 is the minimum now that child 0 jumped to 100",
        );
        assert_eq!(drain(&mut union), [100]);
    }

    /// A finished union is finished whatever its children now say:
    /// `revalidate` tests `is_eof` before it looks at a single child, so it
    /// reports `Ok` without asking them. `resume` has to transition the
    /// children regardless, but must still reach the same verdict — and hand
    /// back the position it was spent on, since the aggregate it carries was
    /// never rebuilt.
    #[test]
    fn resume_of_a_finished_union_is_ok() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 2> = Mock::new([10, 30]);
        let child1: Mock<'_, 2> = Mock::new([20, 40]);
        for data in [child0.data(), child1.data()].iter_mut() {
            data.set_revalidate_result(MockRevalidateResult::Move);
        }

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullHeap::new(children);
        assert_eq!(drain(&mut union), [10, 20, 30, 40]);
        assert!(union.at_eof());
        let spent_at = union.last_doc_id();

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();
        assert!(union.at_eof());
        assert!(union.current().is_none());
        assert_eq!(
            union.last_doc_id(),
            spent_at,
            "a spent union keeps the position it stopped on",
        );
        assert!(matches!(union.read(), Ok(None)));
    }

    /// A child that lands behind a *full* union is a broken child on the resume
    /// path exactly as it is on the legacy one, and the shared settle says so
    /// instead of absorbing it — the resume twin of
    /// `revalidate_asserts_when_a_resurrected_child_lands_behind_a_full_union`.
    ///
    /// A conforming child cannot get there. `advance_matching_children` leaves no
    /// child in the heap behind the union, and exhaustion is terminal across the
    /// cycle ([`at_eof`](RQEIterator::at_eof)), so one `rebuild_heap` left out
    /// stays left out. The mock breaks that on purpose, and its lever is
    /// [`MockData::set_force_read_none`]: a `read` that answers `None` while the
    /// child is neither exhausted nor out of documents, leaving it out of the heap
    /// on a live, lagging position. (The legacy twin uses
    /// [`MockData::set_revalidate_reseeks_to`], which only `revalidate` honours —
    /// [`MockSuspended::resume`] never reads it.)
    ///
    /// [`MockData::set_force_read_none`]: crate::utils::MockData::set_force_read_none
    /// [`MockData::set_revalidate_reseeks_to`]: crate::utils::MockData::set_revalidate_reseeks_to
    /// [`MockSuspended::resume`]: crate::utils::MockSuspended
    #[test]
    #[cfg(debug_assertions)]
    #[should_panic(expected = "moved behind the union's position")]
    fn resume_asserts_when_a_lagging_child_lands_behind_a_full_union() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let guard = mock_ctx.spec_read();
        let child0: Mock<'_, 3> = Mock::new([10, 30, 40]);
        let child1: Mock<'_, 3> = Mock::new([20, 100, 200]);
        let mut data0 = child0.data();
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Move);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionFullHeap::new(children);
        assert_eq!(union.read().unwrap().unwrap().doc_id, 10);

        // The contract violation: child0 answers `None` while still sitting on 10,
        // so the union drops it from the heap with a live, lagging position.
        data0.set_force_read_none(true);
        assert_eq!(union.read().unwrap().unwrap().doc_id, 20);
        assert_eq!(union.read().unwrap().unwrap().doc_id, 100);

        // child1 has to move, or resume returns before the parked child is ever
        // re-admitted.
        let _ = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard);
    }

    /// Every child is transitioned, exhausted ones included, so a `rewind` after a
    /// resume brings the whole union back — the behavioural half of that rule
    /// (the other half is that a skipped slot would be undefined behaviour, which
    /// no test can observe).
    ///
    /// child1 is spent and out of the heap before the suspend, so a resume that
    /// walked only the heap's children would leave it suspended, and the rewind
    /// below would rewind and read it in that state.
    #[test]
    fn resume_then_rewind_revives_the_exhausted_children_too() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let guard = mock_ctx.spec_read();
        let child0: Mock<'_, 3> = Mock::new([10, 40, 70]);
        let child1: Mock<'_, 1> = Mock::new([20]);
        let child2: Mock<'_, 2> = Mock::new([30, 60]);

        let mut union = UnionFullHeap::new(boxed_children(child0, child1, child2));
        assert_eq!(
            (0..4)
                .map(|_| union.read().unwrap().unwrap().doc_id)
                .collect::<Vec<_>>(),
            [10, 20, 30, 40],
            "reading past 20 drops child1 out of the heap",
        );

        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();

        union.rewind();
        assert_eq!(
            drain(&mut union),
            [10, 20, 30, 40, 60, 70],
            "the rewind must revive every child, including the one dropped as spent",
        );
    }

    // =========================================================================
    // `UnionQuickHeap` coverage: `QUICK_EXIT = true` is a separate
    // monomorphization with its own settle branches, and every test above uses
    // `UnionFullHeap`.
    // =========================================================================

    #[test]
    fn quick_revalidate_ok() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 5> = Mock::new([10, 20, 30, 40, 50]);
        let child1: Mock<'_, 5> = Mock::new([15, 25, 35, 45, 55]);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionQuickHeap::new(children);
        assert_eq!(union.read().unwrap().unwrap().doc_id, 10);

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();
        assert_eq!(union.last_doc_id(), 10);
        assert_eq!(drain(&mut union), [15, 20, 25, 30, 35, 40, 45, 50, 55]);
    }

    #[test]
    fn quick_revalidate_moved() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let child0: Mock<'_, 5> = Mock::new([10, 20, 30, 40, 50]);
        let child1: Mock<'_, 5> = Mock::new([15, 25, 35, 45, 55]);
        child0
            .data()
            .set_revalidate_result(MockRevalidateResult::Move);
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Move);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionQuickHeap::new(children);
        assert_eq!(union.read().unwrap().unwrap().doc_id, 10);

        let guard = mock_ctx.spec_read();
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_moved();
        assert_eq!(union.last_doc_id(), 20);
        assert_eq!(drain(&mut union), [25, 30, 35, 40, 45, 50, 55]);
    }

    /// The settle's `min.doc_id < original_last_doc_id` recovery, reached the only
    /// way a conforming union can reach it: the quick `skip_to` returns on the
    /// first exact match, stranding a live sibling behind the union. That makes the
    /// block quick mode's alone, which is what the `debug_assert!(QUICK_EXIT, ..)`
    /// above it claims and
    /// `resume_asserts_when_a_lagging_child_lands_behind_a_full_union` checks from
    /// the other side.
    #[test]
    fn quick_resume_keeps_a_child_stranded_behind_the_union() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let guard = mock_ctx.spec_read();
        let child0: Mock<'_, 3> = Mock::new([5, 100, 300]);
        let child1: Mock<'_, 3> = Mock::new([10, 50, 200]);
        // The lagger moves — to 50, still behind the union — which both gets the
        // resume past its `!any_change` early return and keeps child0 on 100.
        child1
            .data()
            .set_revalidate_result(MockRevalidateResult::Move);

        let children = vec![
            TypeErasedRQEIterator::new(Box::new(child0)),
            TypeErasedRQEIterator::new(Box::new(child1)),
        ];
        let mut union = UnionQuickHeap::new(children);
        assert_eq!(union.read().unwrap().unwrap().doc_id, 5);

        // An exact match on child0, so the quick path returns without ever
        // reaching child1 — which stays on 10, behind the union's 100.
        assert!(union.skip_to(100).expect("skip_to failed").is_some());
        assert_eq!(union.last_doc_id(), 100);

        // 50 is behind the already-delivered 100, so it is not a position to move
        // to: the union stays put, republished from child0, which still holds it.
        let mut union = revalidate_via_resume(TypeErasedRQEIterator::new(Box::new(union)), &guard)
            .expect("resume failed")
            .expect_ok();
        assert_eq!(
            union.last_doc_id(),
            100,
            "the union must not fall back onto the stranded child's position",
        );
        assert_eq!(
            drain(&mut union),
            [200, 300],
            "the stranded child is caught up rather than dropped, so its 200 shows up",
        );
    }

    // =========================================================================
    // Differential: the legacy `revalidate` and the new `resume` are two
    // spellings of one transition and must not drift.
    // =========================================================================

    /// The outcome shape the legacy and resume paths share.
    #[derive(Debug, PartialEq, Eq)]
    enum Outcome {
        Ok,
        Moved,
        Aborted,
        Failed,
    }

    /// Drive `build()` through the legacy `revalidate` and through
    /// `suspend`/`resume`, and require both to agree on the outcome *and* on
    /// everything read afterwards. `what` names the scenario in the failure.
    #[track_caller]
    fn assert_paths_agree<'index, const QUICK_EXIT: bool>(
        what: &str,
        guard: &index_spec::IndexSpecReadGuard<'index>,
        build: impl Fn() -> Box<UnionHeap<'index, TypeErasedRQEIterator<'index>, QUICK_EXIT>>,
    ) {
        let mut legacy = build();
        let legacy_outcome = match legacy.revalidate(guard) {
            Ok(RQEValidateStatus::Ok) => Outcome::Ok,
            Ok(RQEValidateStatus::Moved { .. }) => Outcome::Moved,
            Ok(RQEValidateStatus::Aborted) => Outcome::Aborted,
            Err(_) => Outcome::Failed,
        };
        // An aborted or failed iterator is dropped rather than used, so there is
        // nothing left to read on either path.
        let legacy_tail = match legacy_outcome {
            Outcome::Ok | Outcome::Moved => drain(&mut *legacy),
            Outcome::Aborted | Outcome::Failed => Vec::new(),
        };

        let (resumed_outcome, resumed_tail) = match build().suspend().resume(guard) {
            Ok(ResumeOutcome::Ok(mut it)) => (Outcome::Ok, drain(&mut *it)),
            Ok(ResumeOutcome::Moved(mut it)) => (Outcome::Moved, drain(&mut *it)),
            Ok(ResumeOutcome::Aborted) => (Outcome::Aborted, Vec::new()),
            Err(_) => (Outcome::Failed, Vec::new()),
        };

        assert_eq!(
            legacy_outcome, resumed_outcome,
            "{what}: the two paths disagree on the outcome",
        );
        assert_eq!(
            legacy_tail, resumed_tail,
            "{what}: the two paths disagree on what is read afterwards",
        );
    }

    /// Every child outcome at every position, for both modes. The position
    /// matters because the abort/error teardown splits the child list at the
    /// failing index, and the mode matters because `QUICK_EXIT` takes settle
    /// branches the full union cannot reach.
    #[test]
    fn revalidate_and_resume_agree_on_every_child_outcome() {
        let outcomes = [
            MockRevalidateResult::Ok,
            MockRevalidateResult::Move,
            MockRevalidateResult::Abort,
            MockRevalidateResult::TimedOut,
        ];
        for position in 0..3 {
            for outcome in outcomes {
                let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
                let guard = mock_ctx.spec_read();
                let build = || {
                    let child0: Mock<'_, 4> = Mock::new([10, 20, 40, 70]);
                    let child1: Mock<'_, 4> = Mock::new([10, 30, 50, 80]);
                    let child2: Mock<'_, 4> = Mock::new([10, 35, 60, 90]);
                    for (i, data) in [child0.data(), child1.data(), child2.data()]
                        .iter_mut()
                        .enumerate()
                    {
                        data.set_revalidate_result(if i == position {
                            outcome
                        } else {
                            MockRevalidateResult::Ok
                        });
                    }
                    (child0, child1, child2)
                };
                let what = format!("child {position} reports {outcome:?}");
                assert_paths_agree(&format!("full: {what}"), &guard, || {
                    let (c0, c1, c2) = build();
                    let mut it = Box::new(UnionFullHeap::new(boxed_children(c0, c1, c2)));
                    assert_eq!(it.read().expect("read failed").expect("doc").doc_id, 10);
                    it
                });
                assert_paths_agree(&format!("quick: {what}"), &guard, || {
                    let (c0, c1, c2) = build();
                    let mut it = Box::new(UnionQuickHeap::new(boxed_children(c0, c1, c2)));
                    assert_eq!(it.read().expect("read failed").expect("doc").doc_id, 10);
                    it
                });
            }
        }
    }

    /// The two exits `revalidate` reaches *before* it looks at any child, and
    /// which `resume` has to reproduce even though it must transition the
    /// children regardless: a union that has already finished, and a union that
    /// never had a child to begin with.
    ///
    /// `MockRevalidateResult::TimedOut` is deliberately not in the loop below —
    /// it is the one child outcome the two paths cannot agree on, pinned by
    /// [`resume_of_a_spent_union_surfaces_a_child_error`] instead.
    #[test]
    fn revalidate_and_resume_agree_on_a_spent_or_empty_union() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let guard = mock_ctx.spec_read();

        for outcome in [MockRevalidateResult::Ok, MockRevalidateResult::Abort] {
            assert_paths_agree(
                &format!("full, spent, children {outcome:?}"),
                &guard,
                || {
                    let child0: Mock<'_, 2> = Mock::new([10, 30]);
                    let child1: Mock<'_, 2> = Mock::new([20, 40]);
                    for data in [child0.data(), child1.data()].iter_mut() {
                        data.set_revalidate_result(outcome);
                    }
                    let mut it = Box::new(UnionFullHeap::new(vec![
                        TypeErasedRQEIterator::new(Box::new(child0)),
                        TypeErasedRQEIterator::new(Box::new(child1)),
                    ]));
                    assert_eq!(drain(&mut *it), [10, 20, 30, 40]);
                    it
                },
            );
        }

        assert_paths_agree("full, empty", &guard, || {
            Box::new(UnionFullHeap::new(Vec::new()))
        });
        assert_paths_agree("quick, empty", &guard, || {
            Box::new(UnionQuickHeap::new(Vec::new()))
        });
    }

    /// A union that no longer holds the aggregate it built cannot resume: it has
    /// no way to re-validate a payload it did not create, so it refuses rather
    /// than re-narrow the substitute's suspended pointers. The union counterpart
    /// of `optional::via_resume::resume_aborts_when_result_no_longer_virtual`.
    ///
    /// The three substitutes cover the three ways a payload can slip a looser
    /// gate. `Numeric` is not an aggregate at all. `HybridMetric` *is* one, so
    /// `is_aggregate()` would admit it. And an owned `Union` has the right kind
    /// too, so even an exact-kind check would admit it — all three borrow no
    /// entries, which is precisely why the rebuild reports success for them
    /// without re-validating a thing.
    #[test]
    fn resume_aborts_when_the_result_is_no_longer_a_union() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let guard = mock_ctx.spec_read();

        for substitute in [
            index_result::RSIndexResult::build_numeric(1.0).build(),
            index_result::RSIndexResult::build_hybrid_metric().build(),
        ] {
            let child0: Mock<'_, 2> = Mock::new([10, 30]);
            let child1: Mock<'_, 2> = Mock::new([10, 40]);
            let mut union = Box::new(UnionFullHeap::new(vec![
                TypeErasedRQEIterator::new(Box::new(child0)),
                TypeErasedRQEIterator::new(Box::new(child1)),
            ]));

            let current = union.read().unwrap().unwrap();
            assert_eq!(current.doc_id, 10);
            // A consumer swaps what `current()` handed out for something the
            // union never built.
            let kind = substitute.kind();
            *current = substitute;

            assert!(
                matches!(
                    union.suspend().resume(&guard).expect("no error"),
                    ResumeOutcome::Aborted
                ),
                "a {kind:?} result must abort the resume, not be re-narrowed",
            );
        }
    }

    /// The other known divergence, and the one the differential harness cannot
    /// see: it compares outcomes and the documents read afterwards, never what a
    /// `rewind` brings back.
    ///
    /// `revalidate` returns before it looks at a child when the union is spent,
    /// so a child that would abort is never asked and stays in the list; a later
    /// `rewind` re-admits it. `resume` has to transition every child, so it
    /// learns about the abort and drops it, and the rewind has one fewer child
    /// to revive.
    ///
    /// Deliberate, not a defect. An aborted child's underlying state is
    /// unrecoverable, so the ones `resume` drops here are precisely the ones
    /// `revalidate` would go on to rewind and read after their index had gone
    /// away. The mock cannot show that — its "aborted" child stays perfectly
    /// readable — which is exactly why the difference is asserted here rather
    /// than left for the harness to trip over.
    #[test]
    fn resume_of_a_spent_union_drops_children_that_revalidate_would_rewind() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let guard = mock_ctx.spec_read();

        let build = || {
            let child0: Mock<'_, 2> = Mock::new([10, 30]);
            let child1: Mock<'_, 2> = Mock::new([20, 40]);
            child1
                .data()
                .set_revalidate_result(MockRevalidateResult::Abort);
            let mut it = Box::new(UnionFullHeap::new(vec![
                TypeErasedRQEIterator::new(Box::new(child0)),
                TypeErasedRQEIterator::new(Box::new(child1)),
            ]));
            assert_eq!(drain(&mut *it), [10, 20, 30, 40], "the union is spent");
            it
        };

        let mut legacy = build();
        assert!(matches!(
            legacy.revalidate(&guard),
            Ok(RQEValidateStatus::Ok)
        ));
        legacy.rewind();
        assert_eq!(
            drain(&mut *legacy),
            [10, 20, 30, 40],
            "the legacy path never asked, so the aborting child is still there",
        );

        let mut resumed = revalidate_via_resume(TypeErasedRQEIterator::new(build()), &guard)
            .expect("resume failed")
            .expect_ok();
        resumed.rewind();
        assert_eq!(
            drain(&mut resumed),
            [10, 30],
            "resume asked, learned of the abort, and dropped the child for good",
        );
    }

    /// The single outcome on which the legacy and resume paths are known to
    /// disagree, asserted so it stays a known quantity.
    ///
    /// A spent union sends `revalidate` home with `Ok` before it looks at a
    /// child, so a child that would time out is never asked. Resume has to
    /// transition every child before it can hand any of them back, and
    /// [`resume`](rqe_iterators::RQESuspendedIterator::resume) consumes the child
    /// *by value* — once it answers `Err` the child no longer exists, so there is
    /// nothing to carry on to the `is_eof` exit with. The difference is
    /// structural, not a missing branch.
    ///
    /// A timeout is transient (the child is intact, the resume just ran out of
    /// budget), so the cost is a query-level error where the legacy path would
    /// have finished quietly.
    #[test]
    #[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
    fn resume_of_a_spent_union_surfaces_a_child_error() {
        let mock_ctx = rqe_iterators_test_utils::MockContext::new(0, 0);
        let guard = mock_ctx.spec_read();

        let build = || {
            let child0: Mock<'_, 2> = Mock::new([10, 30]);
            let child1: Mock<'_, 2> = Mock::new([20, 40]);
            for data in [child0.data(), child1.data()].iter_mut() {
                data.set_revalidate_result(MockRevalidateResult::TimedOut);
            }
            let mut it = Box::new(UnionFullHeap::new(vec![
                TypeErasedRQEIterator::new(Box::new(child0)),
                TypeErasedRQEIterator::new(Box::new(child1)),
            ]));
            assert_eq!(drain(&mut *it), [10, 20, 30, 40], "the union is spent");
            it
        };

        assert!(
            matches!(build().revalidate(&guard), Ok(RQEValidateStatus::Ok)),
            "the legacy path never reaches the timing-out child",
        );
        assert!(
            build().suspend().resume(&guard).is_err(),
            "resume must ask every child, and a consumed child cannot be walked past",
        );
    }
}
