/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
*/

//! Integration tests for the UnionFlat iterator variants.
//!
//! Most tests live in the shared [`union_common_tests!`] macro. This file only
//! contains implementation-specific tests that assert on internal observability
//! counters (e.g. `read_count()`) whose values differ between Flat and Heap.

// Shared behavioral tests generated by the macro.
mod common {
    use rqe_iterators::{UnionFullFlat, UnionQuickFlat};
    union_common_tests!(UnionFullFlat, UnionQuickFlat);
}

use crate::utils::{create_mock_2, create_mock_3};
use rqe_iterators::{RQEIterator, UnionFullFlat, UnionQuickFlat};

// =============================================================================
// Implementation-specific tests (read_count assertions differ between Flat and Heap)
// =============================================================================

#[test]
#[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
fn reuse_results_optimization_quick_mode() {
    let (children, data) = create_mock_2([3], [2]);
    let mut union = UnionQuickFlat::new(children);

    let result = union
        .read()
        .expect("read failed")
        .expect("should have result");
    assert_eq!(result.doc_id, 2);
    assert_eq!(
        data[0].read_count(),
        1,
        "child0 should be read once for initial heap setup"
    );
    assert_eq!(
        data[1].read_count(),
        1,
        "child1 should be read once for initial heap setup"
    );

    let result = union
        .read()
        .expect("read failed")
        .expect("should have result");
    assert_eq!(result.doc_id, 3);
    assert_eq!(
        data[0].read_count(),
        1,
        "child0 should NOT be re-read (reuse optimization)"
    );
    assert_eq!(
        data[1].read_count(),
        1,
        "child1 was at doc 2, should NOT be re-read (quick mode returns first match)"
    );

    let result = union.read().expect("read failed");
    assert!(result.is_none());
    assert_eq!(
        data[0].read_count(),
        2,
        "child0 should now be read to discover EOF"
    );
    assert_eq!(
        data[1].read_count(),
        2,
        "child1 should now be read to discover EOF"
    );
}

// =============================================================================
// into_trimmed
// =============================================================================

/// `into_trimmed` on a `UnionFullFlat` produces a working `UnionTrimmed` that
/// yields all children in reverse order when the limit is large enough.
#[test]
#[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
fn into_trimmed_full_flat_yields_all_children() {
    let (children, _data) = create_mock_3([1, 2], [3, 4], [5, 6]);
    let union = UnionFullFlat::new(children);
    let mut trimmed = union.into_trimmed(usize::MAX, true).unwrap();

    // UnionTrimmed drains children last-to-first.
    let mut docs = Vec::new();
    while let Some(r) = trimmed.read().unwrap() {
        docs.push(r.doc_id);
    }
    assert_eq!(docs, [5, 6, 3, 4, 1, 2]);
}

/// `into_trimmed` on a `UnionQuickFlat` applies trimming correctly.
#[test]
#[cfg_attr(miri, ignore = "Calls RSYieldableMetric_Concat FFI in push_borrowed")]
fn into_trimmed_quick_flat_trims_asc() {
    // 3 children with est [2, 2, 2], limit=1.
    // Asc scan from child[1]: child[1].est=2 > 1 → keep=2.
    let (children, _data) = create_mock_3([1, 2], [3, 4], [5, 6]);
    let union = UnionQuickFlat::new(children);
    let mut trimmed = union.into_trimmed(1, true).unwrap();

    assert_eq!(trimmed.num_children_total(), 3, "all children stay alive");
    let mut docs = Vec::new();
    while let Some(r) = trimmed.read().unwrap() {
        docs.push(r.doc_id);
    }
    // Active window [0..2), reads in reverse: child[1] then child[0].
    assert_eq!(docs, [3, 4, 1, 2]);
}
