#!/usr/bin/env python3
"""Deterministically apply the auto-backport CREATE agent's manifest.

Privilege separation: the Codex agent runs with **no GitHub token and no command
network** — all it does is cherry-pick each target onto a local branch in the
pre-made clone and describe the result in a manifest JSON. This script is the
only component that holds the write token; it performs every mutation (push,
`gh pr create`, labels, the summary comment) from that manifest.

Because the manifest is authored by a prompt-injectable agent, every field is
treated as **data**, never as a command: branch names must match the exact
`backport-agent/pr-<pr>-to-<target>` shape, each target must be one the resolve
step actually resolved, PR title/body are built here from templates (the agent
only supplies the free-text conflict log, which lands in the PR body), and every
`git`/`gh` call is made with argument arrays — never shell-interpolated strings.

Env contract (set by task-backport_pr-agent.yml):
- GH_TOKEN, GH_REPO, GITHUB_REPOSITORY -- the scoped App token + repo, for `gh`.
- BACKPORT_CONTEXT_FILE -- the resolve step's context JSON (pr, sha, title, url,
  body, targets).
- BACKPORT_MANIFEST_FILE -- the agent's manifest JSON.
- BACKPORT_WORK -- the pre-made git clone the agent cherry-picked in.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common  # noqa: E402

# Same release-branch shape the resolve step validates targets against; a branch
# name is only ever `backport-agent/pr-<pr>-to-<target>` with a valid target.
TARGET_RE = re.compile(r"^\d{1,4}\.\d{1,4}(?:-[A-Za-z0-9._-]{1,64})?$")
VALID_STATUSES = {"clean", "conflicts", "skipped"}


def git(work: str, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    """Run `git -C <work> <args>` with an argument array (no shell)."""
    return subprocess.run(["git", "-C", work, *args],
                          capture_output=True, text=True, check=check)


def configure_push_auth(work: str, token: str) -> None:
    """Wire the App token as the push credential for the clone's origin.

    GitHub App tokens must be presented as HTTP basic `x-access-token:<token>`;
    a bearer header is rejected. Done here (not in the agent) so the token never
    enters the agent's environment.
    """
    import base64
    header = "AUTHORIZATION: basic " + base64.b64encode(
        f"x-access-token:{token}".encode()).decode()
    git(work, "config", "http.https://github.com/.extraheader", header)


def branch_for(pr: int, target: str) -> str:
    return f"backport-agent/pr-{pr}-to-{target}"


def release_notes_block(original_body: str) -> str:
    """Replicate the original PR's release-notes checkbox state (exactly one is
    checked, per the PR template). Falls back to 'requires' — the conservative
    choice that forces a human to reconsider — if neither line is found checked.
    """
    requires = "- [ ] This PR requires release notes"
    does_not = "- [ ] This PR does not require release notes"
    body = original_body or ""
    if re.search(r"^\s*-\s*\[[xX]\]\s*This PR requires release notes", body, re.M):
        requires = "- [x] This PR requires release notes"
    elif re.search(r"^\s*-\s*\[[xX]\]\s*This PR does not require release notes", body, re.M):
        does_not = "- [x] This PR does not require release notes"
    else:
        requires = "- [x] This PR requires release notes"
    return f"{requires}\n{does_not}"


def pr_body(ctx: dict, entry: dict) -> str:
    """Build the backport PR body from templates + the agent's conflict log."""
    pr, sha = ctx["pr"], ctx["sha"]
    lines = [
        f"Backport of #{pr} to `{entry['target']}`.",
        "",
        "## Original PR",
        f"- Title: {ctx.get('title', '')}",
        f"- Link: {ctx.get('url', '')}",
        f"- Merge commit: `{sha}`",
        "",
        "## Cherry-pick result",
    ]
    conflict_log = entry.get("conflict_log") or []
    if entry["status"] == "conflicts" and conflict_log:
        lines.append(f"- Resolved {len(conflict_log)} conflict(s) — see Conflict Log below.")
        lines += ["", "## Conflict Log"]
        for c in conflict_log:
            if not isinstance(c, dict):
                continue
            lines += [
                f"### `{c.get('path', '')}`",
                f"- **Conflict:** {c.get('conflict', '')}",
                f"- **Why it conflicted:** {c.get('why', '')}",
                f"- **Resolution:** {c.get('resolution', '')}",
                f"- **Rationale:** {c.get('rationale', '')}",
            ]
    else:
        lines.append("- Clean cherry-pick — no conflicts.")
    lines += ["", "## Release notes", "", release_notes_block(ctx.get("body", "")),
              "", "🤖 Generated by the auto-backport workflow."]
    return "\n".join(lines)


def existing_pr(branch: str) -> str | None:
    """`<state> <url>` of a same-repo PR already on this head branch, else None.

    Filters to `isCrossRepository == false` so a fork PR reusing the predictable
    branch name can't make us treat the slot as taken (or skip a real backport).
    """
    out = common.gh(
        "pr", "list", "--head", branch, "--state", "all", "--limit", "100",
        "--json", "url,state,isCrossRepository",
        "--jq", '[.[] | select(.isCrossRepository == false)] | .[0] | select(.) '
                '| "\\(.state) \\(.url)"',
        check=False,
    )
    return out.strip() or None


def apply_target(ctx: dict, work: str, entry: dict) -> dict:
    """Push + open the PR for one manifest entry. Returns a summary row."""
    pr = ctx["pr"]
    target = entry.get("target", "")
    status = entry.get("status", "")
    row = {"target": target, "status": "skipped", "detail": ""}

    if not TARGET_RE.match(target) or target not in ctx["targets"]:
        row["detail"] = f"invalid/unknown target {target!r}"
        return row
    if status not in VALID_STATUSES:
        row["detail"] = f"invalid status {status!r}"
        return row
    if status == "skipped":
        row["detail"] = entry.get("reason", "skipped by agent")
        return row

    branch = branch_for(pr, target)
    if entry.get("branch") != branch:
        row["detail"] = f"branch {entry.get('branch')!r} != expected {branch!r}"
        return row

    # The agent must actually have produced the local branch.
    if git(work, "rev-parse", "--verify", f"refs/heads/{branch}", check=False).returncode != 0:
        row["detail"] = "agent did not produce the branch"
        return row
    # Target must still exist on origin.
    if git(work, "ls-remote", "--exit-code", "--heads", "origin", target,
           check=False).returncode != 0:
        row["detail"] = f"no such branch {target}"
        return row
    # Idempotency: never re-open / force over an existing backport PR.
    if (ex := existing_pr(branch)):
        row["detail"] = f"already {ex}"
        return row

    # Push the agent's branch — plain (non-force) push of a fresh ref only.
    push = git(work, "push", "origin", f"refs/heads/{branch}:refs/heads/{branch}",
               check=False)
    if push.returncode != 0:
        row["detail"] = f"push failed: {push.stderr.strip()[:200]}"
        return row

    title = f"[{target}] {ctx.get('title', '')}"
    body_file = os.path.join(os.environ["RUNNER_TEMP"], f"backport-body-{target}.md")
    with open(body_file, "w") as f:
        f.write(pr_body(ctx, entry))
    created = common.gh("pr", "create", "--base", target, "--head", branch,
                        "--title", title, "--body-file", body_file, check=False)
    url = created.strip().splitlines()[-1] if created.strip() else ""
    if not url.startswith("http"):
        row["status"] = "error"
        row["detail"] = "gh pr create produced no URL"
        return row

    labels = ["auto-backport"] + (["auto-backport-conflicts"] if status == "conflicts" else [])
    for label in labels:
        common.gh("pr", "edit", url, "--add-label", label, check=False)

    row["status"] = f"conflicts({len(entry.get('conflict_log') or [])})" \
        if status == "conflicts" else "clean"
    row["detail"] = url
    return row


def summary_comment(pr: int, sha: str, rows: list[dict]) -> str:
    lines = ["🤖 Auto-backport summary", "", "| Target | Status | Backport PR |",
             "|---|---|---|"]
    for r in rows:
        detail = r["detail"]
        cell = f"#{detail.rsplit('/', 1)[-1]}" if detail.startswith("http") else detail
        lines.append(f"| `{r['target']}` | {r['status']} | {cell} |")
    lines += ["", f"(PR #{pr}, `{sha[:9]}` — generated by the auto-backport workflow.)"]
    return "\n".join(lines)


def main() -> int:
    ctx = json.loads(Path(os.environ["BACKPORT_CONTEXT_FILE"]).read_text())
    manifest_path = os.environ["BACKPORT_MANIFEST_FILE"]
    work = os.environ["BACKPORT_WORK"]
    token = os.environ["GH_TOKEN"]

    if not os.path.exists(manifest_path):
        common.log("No manifest produced by the agent; nothing to apply.")
        return 0
    manifest = json.loads(Path(manifest_path).read_text())
    entries = manifest.get("targets") or []
    if not isinstance(entries, list):
        common.log("Malformed manifest: 'targets' is not a list.")
        return 1

    configure_push_auth(work, token)

    rows = [apply_target(ctx, work, e) for e in entries if isinstance(e, dict)]

    if rows:
        comment_file = os.path.join(os.environ["RUNNER_TEMP"], "backport-summary.md")
        with open(comment_file, "w") as f:
            f.write(summary_comment(ctx["pr"], ctx["sha"], rows))
        common.gh("pr", "comment", str(ctx["pr"]), "--body-file", comment_file, check=False)

    common.log("Auto-backport apply summary:")
    for r in rows:
        common.log(f"  {r['target']:<12} {r['status']:<14} {r['detail']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
