#define MYID                             1
#define HASHFUNC                         2
#define STRING                           3
#define NUMSLOTS                         4
#define INTEGER                          5
#define HASREPLICATION                   6
#define RANGES                           7
#define SHARD                            8
#define SLOTRANGE                        9
#define ADDR                            10
#define UNIXADDR                        11
#define MASTER                          12
