#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>

#include "parse.h"
#include "parser.h"
#include "../query_node.h"
#include "../stopwords.h"

/* forward declarations of stuff generated by lemon */

#define RSQuery_Parse RSQueryParser_ // weird Lemon quirk.. oh well..
#define RSQuery_ParseAlloc RSQueryParser_Alloc
#define RSQuery_ParseFree RSQueryParser_Free

void RSQuery_Parse(void *yyp, int yymajor, QueryToken yyminor, QueryParseCtx *ctx);
void *RSQuery_ParseAlloc(void *(*mallocProc)(size_t));
void RSQuery_ParseFree(void *p, void (*freeProc)(void *));




static const char _query_actions[] = {
	0, 1, 0, 1, 1, 1, 2, 1,
	10, 1, 11, 1, 12, 1, 13, 1,
	14, 1, 15, 1, 16, 1, 17, 1,
	18, 1, 19, 1, 20, 1, 21, 1,
	22, 1, 23, 1, 24, 1, 25, 1,
	26, 1, 27, 1, 28, 1, 29, 1,
	30, 1, 31, 1, 32, 1, 33, 1,
	34, 2, 2, 3, 2, 2, 4, 2,
	2, 5, 2, 2, 6, 2, 2, 7,
	2, 2, 8, 2, 2, 9, 0
};

static const short _query_key_offsets[] = {
	0, 10, 20, 21, 22, 24, 34, 72,
	83, 93, 94, 97, 100, 102, 116, 117,
	127, 137, 149, 0
};

static const char _query_trans_keys[] = {
	9, 13, 32, 47, 58, 64, 91, 96,
	123, 126, 9, 13, 32, 47, 58, 64,
	91, 96, 123, 126, 110, 102, 48, 57,
	9, 13, 32, 47, 58, 64, 91, 96,
	123, 126, 32, 34, 36, 37, 39, 40,
	41, 42, 43, 45, 58, 59, 61, 64,
	91, 92, 93, 95, 105, 123, 124, 125,
	126, 127, 0, 8, 9, 13, 14, 31,
	33, 47, 48, 57, 60, 63, 94, 96,
	42, 92, 96, 0, 47, 58, 64, 91,
	94, 123, 127, 92, 96, 0, 47, 58,
	64, 91, 94, 123, 127, 105, 105, 48,
	57, 46, 48, 57, 48, 57, 42, 46,
	92, 96, 0, 47, 48, 57, 58, 64,
	91, 94, 123, 127, 62, 92, 96, 0,
	47, 58, 64, 91, 94, 123, 127, 9,
	13, 32, 47, 58, 64, 91, 96, 123,
	126, 42, 92, 96, 110, 0, 47, 58,
	64, 91, 94, 123, 127, 42, 92, 96,
	102, 0, 47, 58, 64, 91, 94, 123,
	127, 0
};

static const char _query_single_lengths[] = {
	0, 0, 1, 1, 0, 0, 24, 3,
	2, 1, 1, 1, 0, 4, 1, 2,
	0, 4, 4, 0
};

static const char _query_range_lengths[] = {
	5, 5, 0, 0, 1, 5, 7, 4,
	4, 0, 1, 1, 1, 5, 0, 4,
	5, 4, 4, 0
};

static const char _query_index_offsets[] = {
	0, 6, 12, 14, 16, 18, 24, 56,
	64, 71, 73, 76, 79, 81, 91, 93,
	100, 106, 115, 0
};

static const char _query_trans_cond_spaces[] = {
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, 0
};

static const short _query_trans_offsets[] = {
	0, 1, 2, 3, 4, 5, 6, 7,
	8, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18, 19, 20, 21, 22, 23,
	24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39,
	40, 41, 42, 43, 44, 45, 46, 47,
	48, 49, 50, 51, 52, 53, 54, 55,
	56, 57, 58, 59, 60, 61, 62, 63,
	64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79,
	80, 81, 82, 83, 84, 85, 86, 87,
	88, 89, 90, 91, 92, 93, 94, 95,
	96, 97, 98, 99, 100, 101, 102, 103,
	104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119,
	120, 121, 122, 123, 124, 125, 126, 127,
	128, 129, 130, 131, 132, 133, 134, 135,
	136, 137, 138, 139, 140, 141, 0
};

static const char _query_trans_lengths[] = {
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 0
};

static const char _query_cond_keys[] = {
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0
};

static const char _query_cond_targs[] = {
	7, 7, 7, 7, 7, 6, 8, 8,
	8, 8, 8, 6, 3, 6, 6, 6,
	12, 6, 15, 15, 15, 15, 15, 6,
	6, 6, 8, 6, 9, 6, 6, 6,
	9, 10, 6, 6, 14, 15, 6, 16,
	6, 7, 17, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 13, 6, 6, 7,
	6, 0, 6, 6, 6, 6, 6, 7,
	1, 6, 6, 6, 6, 6, 8, 2,
	6, 2, 11, 6, 4, 11, 6, 12,
	6, 6, 4, 0, 6, 6, 13, 6,
	6, 6, 7, 6, 6, 5, 6, 6,
	6, 6, 6, 15, 7, 7, 7, 7,
	7, 6, 6, 0, 6, 18, 6, 6,
	6, 6, 7, 6, 0, 6, 7, 6,
	6, 6, 6, 7, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 0
};

static const char _query_cond_actions[] = {
	75, 75, 75, 75, 75, 55, 63, 63,
	63, 63, 63, 55, 0, 55, 9, 55,
	0, 53, 60, 60, 60, 60, 60, 55,
	37, 11, 72, 31, 72, 15, 17, 29,
	72, 69, 23, 25, 0, 72, 33, 0,
	35, 72, 75, 19, 13, 21, 27, 41,
	41, 37, 41, 39, 57, 39, 39, 75,
	43, 0, 55, 55, 55, 55, 55, 75,
	0, 55, 55, 55, 55, 55, 63, 0,
	49, 0, 5, 47, 0, 5, 45, 0,
	45, 43, 0, 0, 45, 45, 57, 45,
	45, 45, 75, 7, 49, 0, 55, 55,
	55, 55, 55, 60, 75, 75, 75, 75,
	75, 49, 43, 0, 51, 75, 51, 51,
	51, 51, 75, 43, 0, 51, 66, 51,
	51, 51, 51, 75, 55, 55, 55, 55,
	53, 55, 55, 55, 49, 47, 45, 45,
	45, 49, 55, 49, 51, 51, 0
};

static const char _query_to_state_actions[] = {
	0, 0, 0, 0, 0, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0
};

static const char _query_from_state_actions[] = {
	0, 0, 0, 0, 0, 0, 3, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0
};

static const char _query_eof_trans_indexed[] = {
	7, 7, 7, 7, 9, 7, 0, 7,
	7, 27, 28, 29, 29, 29, 27, 7,
	27, 31, 31, 0
};

static const short _query_eof_trans_direct[] = {
	125, 126, 127, 128, 129, 130, 0, 131,
	132, 133, 134, 135, 136, 137, 138, 139,
	140, 141, 142, 0
};

static const char _query_nfa_targs[] = {
	0, 0
};

static const char _query_nfa_offsets[] = {
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0
};

static const char _query_nfa_push_actions[] = {
	0, 0
};

static const char _query_nfa_pop_trans[] = {
	0, 0
};

static const int query_start = 6;
static const int query_first_final = 6;
static const int query_error = -1;

static const int query_en_main = 6;



QueryNode *RSQuery_ParseRaw(QueryParseCtx *q) {
	void *pParser = RSQuery_ParseAlloc(rm_malloc);
	
	
	int cs, act;
	const char* ts = q->raw;
	const char* te = q->raw + q->len;
	
	{
		cs = (int)query_start;
		ts = 0;
		te = 0;
		act = 0;
	}
	
	QueryToken tok = {.len = 0, .pos = 0, .s = 0};
	
	//parseCtx ctx = {.root = NULL, .ok = 1, .errorMsg = NULL, .q = q};
	const char* p = q->raw;
	const char* pe = q->raw + q->len;
	const char* eof = pe;
	
	
	{
		int _klen;
		unsigned int _trans = 0;
		unsigned int _cond = 0;
		const char *_acts;
		unsigned int _nacts;
		const char *_keys;
		const char *_ckeys;
		int _cpc;
		{
			
			if ( p == pe )
			goto _test_eof;
			_resume:  {
				_acts = ( _query_actions + (_query_from_state_actions[cs]));
				_nacts = (unsigned int)(*( _acts));
				_acts += 1;
				while ( _nacts > 0 ) {
					switch ( (*( _acts)) ) {
						case 1:  {
							{
								{ts = p;}}
							break; }
					}
					_nacts -= 1;
					_acts += 1;
				}
				
				_keys = ( _query_trans_keys + (_query_key_offsets[cs]));
				_trans = (unsigned int)_query_index_offsets[cs];
				
				_klen = (int)_query_single_lengths[cs];
				if ( _klen > 0 ) {
					const char *_lower;
					const char *_mid;
					const char *_upper;
					_lower = _keys;
					_upper = _keys + _klen - 1;
					while ( 1 ) {
						if ( _upper < _lower )
						break;
						
						_mid = _lower + ((_upper-_lower) >> 1);
						if ( ( (*( p))) < (*( _mid)) )
						_upper = _mid - 1;
						else if ( ( (*( p))) > (*( _mid)) )
						_lower = _mid + 1;
						else {
							_trans += (unsigned int)(_mid - _keys);
							goto _match;
						}
					}
					_keys += _klen;
					_trans += (unsigned int)_klen;
				}
				
				_klen = (int)_query_range_lengths[cs];
				if ( _klen > 0 ) {
					const char *_lower;
					const char *_mid;
					const char *_upper;
					_lower = _keys;
					_upper = _keys + (_klen<<1) - 2;
					while ( 1 ) {
						if ( _upper < _lower )
						break;
						
						_mid = _lower + (((_upper-_lower) >> 1) & ~1);
						if ( ( (*( p))) < (*( _mid)) )
						_upper = _mid - 2;
						else if ( ( (*( p))) > (*( _mid + 1)) )
						_lower = _mid + 2;
						else {
							_trans += (unsigned int)((_mid - _keys)>>1);
							goto _match;
						}
					}
					_trans += (unsigned int)_klen;
				}
				
			}
			_match:  {
				_ckeys = ( _query_cond_keys + (_query_trans_offsets[_trans]));
				_klen = (int)_query_trans_lengths[_trans];
				_cond = (unsigned int)_query_trans_offsets[_trans];
				
				_cpc = 0;
				{
					const char *_lower;
					const char *_mid;
					const char *_upper;
					_lower = _ckeys;
					_upper = _ckeys + _klen - 1;
					while ( 1 ) {
						if ( _upper < _lower )
						break;
						
						_mid = _lower + ((_upper-_lower) >> 1);
						if ( _cpc < (int)(*( _mid)) )
						_upper = _mid - 1;
						else if ( _cpc > (int)(*( _mid)) )
						_lower = _mid + 1;
						else {
							_cond += (unsigned int)(_mid - _ckeys);
							goto _match_cond;
						}
					}
					cs = -1;
					goto _again;
				}
			}
			_match_cond:  {
				cs = (int)_query_cond_targs[_cond];
				
				if ( _query_cond_actions[_cond] == 0 )
				goto _again;
				
				_acts = ( _query_actions + (_query_cond_actions[_cond]));
				_nacts = (unsigned int)(*( _acts));
				_acts += 1;
				while ( _nacts > 0 )
				{
					switch ( (*( _acts)) )
					{
						case 2:  {
							{
								{te = p+1;}}
							break; }
						case 3:  {
							{
								{act = 1;}}
							break; }
						case 4:  {
							{
								{act = 2;}}
							break; }
						case 5:  {
							{
								{act = 3;}}
							break; }
						case 6:  {
							{
								{act = 5;}}
							break; }
						case 7:  {
							{
								{act = 14;}}
							break; }
						case 8:  {
							{
								{act = 21;}}
							break; }
						case 9:  {
							{
								{act = 23;}}
							break; }
						case 10:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										tok.len = te - ts;
										tok.s = ts+1;
										RSQuery_Parse(pParser, ARROW, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 11:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										tok.s = ts;
										tok.len = te-ts;
										tok.numval = *ts == '-' ? -INFINITY : INFINITY;
										RSQuery_Parse(pParser, NUMBER, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 12:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, QUOTE, tok, q);  
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 13:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, OR, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 14:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, LP, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 15:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, RP, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 16:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, LB, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 17:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, RB, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 18:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, COLON, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 19:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, SEMICOLON, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 20:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, TILDE, tok, q);  
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 21:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, STAR, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 22:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, PERCENT, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 23:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, LSQB, tok, q);  
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}  
									}}}
							break; }
						case 24:  {
							{
								{te = p+1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, RSQB, tok, q);   
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										} 
									}}}
							break; }
						case 25:  {
							{
								{te = p+1;}}
							break; }
						case 26:  {
							{
								{te = p+1;}}
							break; }
						case 27:  {
							{
								{te = p+1;}}
							break; }
						case 28:  {
							{
								{te = p+1;{
										
										tok.len = te-ts - 1;
										tok.s = ts;
										tok.numval = 0;
										tok.pos = ts-q->raw;
										
										RSQuery_Parse(pParser, PREFIX, tok, q);
										
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 29:  {
							{
								{te = p;p = p - 1;{
										
										tok.s = ts;
										tok.len = te-ts;
										char *ne = (char*)te;
										tok.numval = strtod(tok.s, &ne);
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, NUMBER, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
										
									}}}
							break; }
						case 30:  {
							{
								{te = p;p = p - 1;{
										
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, MINUS, tok, q);  
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 31:  {
							{
								{te = p;p = p - 1;}}
							break; }
						case 32:  {
							{
								{te = p;p = p - 1;{
										
										tok.len = te-ts;
										tok.s = ts;
										tok.numval = 0;
										tok.pos = ts-q->raw;
										if (!StopWordList_Contains(q->opts->stopwords, tok.s, tok.len)) {
											RSQuery_Parse(pParser, TERM, tok, q);
										} else {
											RSQuery_Parse(pParser, STOPWORD, tok, q);
										}
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
									}}}
							break; }
						case 33:  {
							{
								{p = ((te))-1;
									{
										
										tok.s = ts;
										tok.len = te-ts;
										char *ne = (char*)te;
										tok.numval = strtod(tok.s, &ne);
										tok.pos = ts-q->raw;
										RSQuery_Parse(pParser, NUMBER, tok, q);
										if (!QPCTX_ISOK(q)) {
											{p+= 1; goto _out; }
										}
										
									}}}
							break; }
						case 34:  {
							{
								{switch( act ) {
										case 1:  {
											p = ((te))-1;
											{
												
												tok.s = ts;
												tok.len = te-ts;
												char *ne = (char*)te;
												tok.numval = strtod(tok.s, &ne);
												tok.pos = ts-q->raw;
												RSQuery_Parse(pParser, NUMBER, tok, q);
												if (!QPCTX_ISOK(q)) {
													{p+= 1; goto _out; }
												}
												
											} break; }
										case 2:  {
											p = ((te))-1;
											{
												
												tok.pos = ts-q->raw;
												tok.len = te - (ts + 1);
												tok.s = ts+1;
												RSQuery_Parse(pParser, MODIFIER, tok, q);
												if (!QPCTX_ISOK(q)) {
													{p+= 1; goto _out; }
												}
											} break; }
										case 3:  {
											p = ((te))-1;
											{
												
												tok.pos = ts-q->raw;
												tok.len = te - (ts + 1);
												tok.s = ts+1;
												RSQuery_Parse(pParser, ATTRIBUTE, tok, q);
												if (!QPCTX_ISOK(q)) {
													{p+= 1; goto _out; }
												}
											} break; }
										case 5:  {
											p = ((te))-1;
											{
												
												tok.pos = ts-q->raw;
												tok.s = ts;
												tok.len = te-ts;
												tok.numval = *ts == '-' ? -INFINITY : INFINITY;
												RSQuery_Parse(pParser, NUMBER, tok, q);
												if (!QPCTX_ISOK(q)) {
													{p+= 1; goto _out; }
												}
											} break; }
										case 14:  {
											p = ((te))-1;
											{
												
												tok.pos = ts-q->raw;
												RSQuery_Parse(pParser, MINUS, tok, q);  
												if (!QPCTX_ISOK(q)) {
													{p+= 1; goto _out; }
												}
											} break; }
										case 23:  {
											p = ((te))-1;
											{
												
												tok.len = te-ts;
												tok.s = ts;
												tok.numval = 0;
												tok.pos = ts-q->raw;
												if (!StopWordList_Contains(q->opts->stopwords, tok.s, tok.len)) {
													RSQuery_Parse(pParser, TERM, tok, q);
												} else {
													RSQuery_Parse(pParser, STOPWORD, tok, q);
												}
												if (!QPCTX_ISOK(q)) {
													{p+= 1; goto _out; }
												}
											} break; }
										default: {
											p = ((te))-1;
											break; }
									}}
							}
							break; }
					}
					_nacts -= 1;
					_acts += 1;
				}
				
				
			}
			_again:  {
				_acts = ( _query_actions + (_query_to_state_actions[cs]));
				_nacts = (unsigned int)(*( _acts));
				_acts += 1;
				while ( _nacts > 0 ) {
					switch ( (*( _acts)) ) {
						case 0:  {
							{
								{ts = 0;}}
							break; }
					}
					_nacts -= 1;
					_acts += 1;
				}
				
				p += 1;
				if ( p != pe )
				goto _resume;
			}
			_test_eof:  { {}
				if ( p == eof )
				{
					if ( _query_eof_trans_direct[cs] > 0 ) {
						_trans = (unsigned int)_query_eof_trans_direct[cs] - 1;
						_cond = (unsigned int)_query_trans_offsets[_trans];
						goto _match_cond;
					}
				}
				
			}
			_out:  { {}
			}
		}
	}
	
	
	if (QPCTX_ISOK(q)) {
		RSQuery_Parse(pParser, 0, tok, q);
	}
	RSQuery_ParseFree(pParser, rm_free);
	if (!QPCTX_ISOK(q) && q->root) {
		QueryNode_Free(q->root);
		q->root = NULL;
	}
	return q->root;
}

