
#line 1 "lexer.rl"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>

#include "parse.h"
#include "parser.h"
#include "../query_node.h"

/* forward declarations of stuff generated by lemon */
void Parse(void *yyp, int yymajor, QueryToken yyminor, parseCtx *ctx);
void *ParseAlloc(void *(*mallocProc)(size_t));
void ParseFree(void *p, void (*freeProc)(void *));


#line 158 "lexer.rl"



#line 24 "lexer.c"
static const char _query_actions[] = {
	0, 1, 2, 1, 3, 1, 7, 1, 
	8, 1, 9, 1, 10, 1, 11, 1, 
	12, 1, 13, 1, 14, 1, 15, 1, 
	16, 1, 17, 1, 18, 1, 19, 1, 
	20, 1, 21, 1, 22, 1, 23, 2, 
	0, 1, 2, 3, 4, 2, 3, 5, 
	2, 3, 6
};

static const char _query_key_offsets[] = {
	0, 0, 1, 2, 3, 5, 9, 15, 
	44, 52, 55, 58, 60, 71, 77, 86
};

static const char _query_trans_keys[] = {
	105, 110, 102, 48, 57, 65, 90, 97, 
	122, 48, 57, 65, 90, 97, 122, 32, 
	34, 39, 40, 41, 42, 43, 45, 58, 
	64, 91, 93, 105, 124, 126, 0, 8, 
	9, 13, 14, 47, 48, 57, 59, 63, 
	92, 96, 123, 127, 0, 47, 58, 64, 
	91, 96, 123, 127, 105, 48, 57, 46, 
	48, 57, 48, 57, 46, 0, 47, 48, 
	57, 58, 64, 91, 96, 123, 127, 48, 
	57, 65, 90, 97, 122, 110, 0, 47, 
	58, 64, 91, 96, 123, 127, 102, 0, 
	47, 58, 64, 91, 96, 123, 127, 0
};

static const char _query_single_lengths[] = {
	0, 1, 1, 1, 0, 0, 0, 15, 
	0, 1, 1, 0, 1, 0, 1, 1
};

static const char _query_range_lengths[] = {
	0, 0, 0, 0, 1, 2, 3, 7, 
	4, 1, 1, 1, 5, 3, 4, 4
};

static const char _query_index_offsets[] = {
	0, 0, 2, 4, 6, 8, 11, 15, 
	38, 43, 46, 49, 51, 58, 62, 68
};

static const char _query_indicies[] = {
	0, 1, 3, 2, 4, 2, 6, 5, 
	7, 7, 1, 8, 8, 8, 1, 10, 
	11, 12, 13, 14, 15, 12, 16, 18, 
	19, 20, 21, 22, 23, 24, 1, 10, 
	1, 17, 1, 1, 1, 9, 2, 2, 
	2, 2, 9, 0, 26, 25, 28, 26, 
	27, 6, 27, 28, 27, 17, 27, 27, 
	27, 9, 8, 8, 8, 29, 31, 30, 
	30, 30, 30, 9, 32, 30, 30, 30, 
	30, 9, 0
};

static const char _query_trans_targs[] = {
	2, 0, 7, 3, 7, 7, 11, 6, 
	13, 8, 7, 7, 1, 7, 7, 7, 
	9, 12, 7, 5, 7, 7, 14, 7, 
	7, 7, 10, 7, 4, 7, 7, 15, 
	8
};

static const char _query_trans_actions[] = {
	0, 0, 37, 0, 5, 35, 0, 0, 
	0, 48, 25, 7, 0, 11, 13, 19, 
	45, 3, 15, 0, 21, 23, 0, 9, 
	17, 31, 3, 27, 0, 29, 33, 0, 
	42
};

static const char _query_to_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 39, 
	0, 0, 0, 0, 0, 0, 0, 0
};

static const char _query_from_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 1, 
	0, 0, 0, 0, 0, 0, 0, 0
};

static const char _query_eof_trans[] = {
	0, 0, 3, 3, 6, 0, 0, 0, 
	3, 26, 28, 28, 28, 30, 31, 31
};

static const int query_start = 7;
static const int query_first_final = 7;
static const int query_error = 0;

static const int query_en_main = 7;


#line 161 "lexer.rl"



QueryNode *Query_Parse(Query *q, char **err) {
  void *pParser = ParseAlloc(malloc);

  
  int cs, act;
  const char* ts = q->raw;
  const char* te = q->raw + q->len;
  
#line 133 "lexer.c"
	{
	cs = query_start;
	ts = 0;
	te = 0;
	act = 0;
	}

#line 172 "lexer.rl"
  QueryToken tok = {};
  
  parseCtx ctx = {.root = NULL, .ok = 1, .errorMsg = NULL, .q = q};
  const char* p = q->raw;
  const char* pe = q->raw + q->len;
  const char* eof = pe;
  
  
#line 150 "lexer.c"
	{
	int _klen;
	unsigned int _trans;
	const char *_acts;
	unsigned int _nacts;
	const char *_keys;

	if ( p == pe )
		goto _test_eof;
	if ( cs == 0 )
		goto _out;
_resume:
	_acts = _query_actions + _query_from_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 2:
#line 1 "NONE"
	{ts = p;}
	break;
#line 171 "lexer.c"
		}
	}

	_keys = _query_trans_keys + _query_key_offsets[cs];
	_trans = _query_index_offsets[cs];

	_klen = _query_single_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + _klen - 1;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + ((_upper-_lower) >> 1);
			if ( (*p) < *_mid )
				_upper = _mid - 1;
			else if ( (*p) > *_mid )
				_lower = _mid + 1;
			else {
				_trans += (unsigned int)(_mid - _keys);
				goto _match;
			}
		}
		_keys += _klen;
		_trans += _klen;
	}

	_klen = _query_range_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + (_klen<<1) - 2;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + (((_upper-_lower) >> 1) & ~1);
			if ( (*p) < _mid[0] )
				_upper = _mid - 2;
			else if ( (*p) > _mid[1] )
				_lower = _mid + 2;
			else {
				_trans += (unsigned int)((_mid - _keys)>>1);
				goto _match;
			}
		}
		_trans += _klen;
	}

_match:
	_trans = _query_indicies[_trans];
_eof_trans:
	cs = _query_trans_targs[_trans];

	if ( _query_trans_actions[_trans] == 0 )
		goto _again;

	_acts = _query_actions + _query_trans_actions[_trans];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 )
	{
		switch ( *_acts++ )
		{
	case 3:
#line 1 "NONE"
	{te = p+1;}
	break;
	case 4:
#line 59 "lexer.rl"
	{act = 3;}
	break;
	case 5:
#line 107 "lexer.rl"
	{act = 9;}
	break;
	case 6:
#line 144 "lexer.rl"
	{act = 15;}
	break;
	case 7:
#line 59 "lexer.rl"
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    Parse(pParser, NUMBER, tok, &ctx);
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }}
	break;
	case 8:
#line 71 "lexer.rl"
	{te = p+1;{
    tok.pos = ts-q->raw;
    Parse(pParser, QUOTE, tok, &ctx);  
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }}
	break;
	case 9:
#line 78 "lexer.rl"
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    Parse(pParser, OR, tok, &ctx);
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }}
	break;
	case 10:
#line 85 "lexer.rl"
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    Parse(pParser, LP, tok, &ctx);
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }}
	break;
	case 11:
#line 92 "lexer.rl"
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    Parse(pParser, RP, tok, &ctx);
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }}
	break;
	case 12:
#line 99 "lexer.rl"
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     Parse(pParser, COLON, tok, &ctx);
     if (!ctx.ok) {
      {p++; goto _out; }
    }
   }}
	break;
	case 13:
#line 114 "lexer.rl"
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    Parse(pParser, TILDE, tok, &ctx);  
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }}
	break;
	case 14:
#line 121 "lexer.rl"
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    Parse(pParser, STAR, tok, &ctx);    
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }}
	break;
	case 15:
#line 128 "lexer.rl"
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    Parse(pParser, LSQB, tok, &ctx);  
    if (!ctx.ok) {
      {p++; goto _out; }
    }  
  }}
	break;
	case 16:
#line 135 "lexer.rl"
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    Parse(pParser, RSQB, tok, &ctx);   
    if (!ctx.ok) {
      {p++; goto _out; }
    } 
  }}
	break;
	case 17:
#line 142 "lexer.rl"
	{te = p+1;}
	break;
	case 18:
#line 38 "lexer.rl"
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    Parse(pParser, NUMBER, tok, &ctx);
    if (!ctx.ok) {
      {p++; goto _out; }
    }
    
  }}
	break;
	case 19:
#line 50 "lexer.rl"
	{te = p;p--;{
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    Parse(pParser, MODIFIER, tok, &ctx);
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }}
	break;
	case 20:
#line 107 "lexer.rl"
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    Parse(pParser, MINUS, tok, &ctx);  
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }}
	break;
	case 21:
#line 144 "lexer.rl"
	{te = p;p--;{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    if (!isStopword(tok.s, tok.len, q->stopwords)) {
        Parse(pParser, TERM, tok, &ctx);
    } 
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }}
	break;
	case 22:
#line 38 "lexer.rl"
	{{p = ((te))-1;}{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    Parse(pParser, NUMBER, tok, &ctx);
    if (!ctx.ok) {
      {p++; goto _out; }
    }
    
  }}
	break;
	case 23:
#line 1 "NONE"
	{	switch( act ) {
	case 0:
	{{cs = 0;goto _again;}}
	break;
	case 3:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    Parse(pParser, NUMBER, tok, &ctx);
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }
	break;
	case 9:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    Parse(pParser, MINUS, tok, &ctx);  
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }
	break;
	case 15:
	{{p = ((te))-1;}
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    if (!isStopword(tok.s, tok.len, q->stopwords)) {
        Parse(pParser, TERM, tok, &ctx);
    } 
    if (!ctx.ok) {
      {p++; goto _out; }
    }
  }
	break;
	}
	}
	break;
#line 473 "lexer.c"
		}
	}

_again:
	_acts = _query_actions + _query_to_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 0:
#line 1 "NONE"
	{ts = 0;}
	break;
	case 1:
#line 1 "NONE"
	{act = 0;}
	break;
#line 490 "lexer.c"
		}
	}

	if ( cs == 0 )
		goto _out;
	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	if ( _query_eof_trans[cs] > 0 ) {
		_trans = _query_eof_trans[cs] - 1;
		goto _eof_trans;
	}
	}

	_out: {}
	}

#line 180 "lexer.rl"
  

  if (ctx.ok) {
    Parse(pParser, 0, tok, &ctx);
  }
  ParseFree(pParser, free);
  if (err) {
    *err = ctx.errorMsg;
  }

  if (ctx.root) {
    q->root = ctx.root;
  }
  return ctx.root;
}

