#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>

#include "parse.h"
#include "parser.h"
#include "../query_node.h"

/* forward declarations of stuff generated by lemon */
void Parse(void *yyp, int yymajor, QueryToken yyminor, parseCtx *ctx);
void *ParseAlloc(void *(*mallocProc)(size_t));
void ParseFree(void *p, void (*freeProc)(void *));

QueryNode *Query_Parse(Query *q, char **err) {
  void *pParser = ParseAlloc(malloc);
  int t = 0;

  QueryToken tok = {0, 0};
  QueryTokenizer qt = NewQueryTokenizer(q->raw, q->len, q->stopwords);
  parseCtx ctx = {.root = NULL, .ok = 1, .errorMsg = NULL, .q = q};

  while (0 != (t = QueryTokenizer_Next(&qt, &tok)) && ctx.ok) {
    
    Parse(pParser, t, tok, &ctx);
  }

  if (ctx.ok) {
    Parse(pParser, 0, tok, &ctx);
  }
  ParseFree(pParser, free);
  if (err) {
    *err = ctx.errorMsg;
  }

  if (ctx.root) {
    q->root = ctx.root;
  }
  return ctx.root;
}
