#define LOWEST                           1
#define LP                               2
#define LB                               3
#define LSQB                             4
#define RP                               5
#define RB                               6
#define RSQB                             7
#define MODIFIER                         8
#define TILDE                            9
#define MINUS                           10
#define TEXTEXPR                        11
#define OR                              12
#define ORX                             13
#define TERM                            14
#define AND                             15
#define QUOTE                           16
#define ARROW                           17
#define COLON                           18
#define NUMBER                          19
#define SIZE                            20
#define STOPWORD                        21
#define STAR                            22
#define TAGLIST                         23
#define TERMLIST                        24
#define PREFIX                          25
#define PERCENT                         26
#define ATTRIBUTE                       27
#define AS_S                            28
#define AS_T                            29
#define SEMICOLON                       30
