#define LOWEST                           1
#define TILDE                            2
#define TAGLIST                          3
#define QUOTE                            4
#define MODIFIER                         5
#define MINUS                            6
#define NUMBER                           7
#define SIZE                             8
#define STOPWORD                         9
#define STAR                            10
#define TERMLIST                        11
#define TERM                            12
#define PREFIX                          13
#define PERCENT                         14
#define ATTRIBUTE                       15
#define LP                              16
#define RP                              17
#define COLON                           18
#define AND                             19
#define OR                              20
#define ORX                             21
#define TEXTEXPR                        22
#define ARROW                           23
#define TOP_K                           24
#define AS                              25
#define SEMICOLON                       26
#define LB                              27
#define RB                              28
#define LSQB                            29
#define RSQB                            30
