#define TILDE                           1
#define TERM                            2
#define QUOTE                           3
#define COLON                           4
#define MINUS                           5
#define NUMBER                          6
#define MODIFIER                        7
#define AND                             8
#define TERMLIST                        9
#define LP                             10
#define RP                             11
#define OR                             12
#define STAR                           13
#define LSQB                           14
#define RSQB                           15
