/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
*/

use std::ffi::{CStr, CString, c_char};
use std::ptr::NonNull;
use std::sync::OnceLock;
use std::time::SystemTime;
use tracing::level_filters::LevelFilter;

/// Parses a redis `loglevel` config value into a `tracing` level.
///
/// # Panics
///
/// Panics if `level` is not valid UTF-8, or is not one of the redis log levels
/// `debug`, `verbose`, `notice`, or `warning`.
///
/// # Safety
///
/// `level` must point to a valid, null-terminated C string.
unsafe fn parse_level(level: *const c_char) -> LevelFilter {
    // Safety: the caller guarantees a valid, null-terminated C string.
    let level = unsafe { CStr::from_ptr(level) };
    let level = level.to_str().expect("redis loglevel must be valid UTF-8");

    match level {
        "debug" => LevelFilter::TRACE,
        "verbose" => LevelFilter::DEBUG,
        "notice" => LevelFilter::INFO,
        "warning" => LevelFilter::WARN,
        "nothing" => LevelFilter::OFF,
        other => panic!("invalid redis loglevel: {other:?}"),
    }
}

/// Initializes a global subscriber that reports Rust `tracing` traces through `redismodule` logging.
///
/// `level` is the initial redis `loglevel` config value the filter is set to.
///
/// # Safety
///
/// `level` must point to a valid, null-terminated C string.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn TracingRedisModule_Init(
    ctx: Option<NonNull<redis_module::RedisModuleCtx>>,
    level: *const c_char,
) {
    // Safety: forwarded to the caller's contract on `level`.
    let level = unsafe { parse_level(level) };
    tracing_redismodule::init(ctx, level);
}

/// Updates the `tracing` log level filter from a redis `loglevel` config value
/// (one of `debug`, `verbose`, `notice`, `warning`).
///
/// # Safety
///
/// `level` must point to a valid, null-terminated C string.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn TracingRedisModule_SetLogLevel(level: *const c_char) {
    // Safety: forwarded to the caller's contract on `level`.
    let level = unsafe { parse_level(level) };
    tracing_redismodule::set_log_level(level);
}

/// Details of a Rust panic, stashed by the hook installed in
/// [`RustPanicHook_Init`] and emitted inside the crash report by
/// [`AddToInfo_RustBacktrace`].
///
/// Strings are stored as-is, without truncation. `payload` and `location`
/// match the rendering of the hook's `tracing::error!` log line: the literal
/// `None` for a non-string payload or a missing location. `recorded_at` is
/// captured at hook time, in the [`format_utc_timestamp`] format.
///
/// The stash outlives the panic: a panic crossing an `extern "C"` boundary
/// aborts right away, but a panic that unwinds and is caught, or one on a
/// Rust-only thread, leaves the stash populated until a later, possibly
/// unrelated crash — where it reads as that crash's cause. `recorded_at`
/// lets the reader tell the two apart by comparing it against the crash log
/// line's own timestamp prefix.
struct StashedPanic {
    payload: String,
    location: String,
    recorded_at: String,
}

/// The process-wide stash, written by the hook installed in
/// [`RustPanicHook_Init`] and read by [`AddToInfo_RustBacktrace`].
///
/// A [`OnceLock`] rather than a mutex: [`AddToInfo_RustBacktrace`] runs from
/// Redis's fatal signal handler, where pthread_mutex_lock is not
/// async-signal-safe. First-write-wins: the hook fires twice per crash (the
/// real panic, then the nested "panic in a function that cannot unwind"
/// panic at the `extern "C"` boundary), and the second `set` is dropped.
static PANIC_STASH: OnceLock<StashedPanic> = OnceLock::new();

/// Initialize RediSearch's panic hook, without replaacing the pre-existing panic hook (if any).
///
/// Panic messages will be logged through `tracing` at the `ERROR` level, and
/// stashed in [`PANIC_STASH`] for [`AddToInfo_RustBacktrace`] to include in
/// the crash report.
#[unsafe(no_mangle)]
pub extern "C" fn RustPanicHook_Init() {
    let previous_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(move |panic_info| {
        // We don't capture a backtrace here, since it should be included
        // in the crash report generated by the module info function
        // if `for_crash_report` is set to `true`.
        tracing::error!(
            panic.payload = panic_info.payload_as_str(),
            panic.location = panic_info.location().map(|l| l.to_string()),
            "A panic occurred in the Rust code",
        );

        // The log line above lands above the crash report's START marker,
        // outside the span users are asked to copy; the stash rides the
        // module INFO callback instead, which runs inside the report.
        // A failed `set` means a panic was already stashed — first-write-wins.
        let _ = PANIC_STASH.set(StashedPanic {
            payload: panic_info.payload_as_str().unwrap_or("None").to_owned(),
            location: panic_info
                .location()
                .map_or_else(|| "None".to_owned(), |l| l.to_string()),
            recorded_at: format_utc_timestamp(SystemTime::now()),
        });

        // Invoke the previous panic hook, if any.
        previous_hook(panic_info);
    }));
}

/// Formats `now` as `YYYY-MM-DD HH:MM:SS UTC`: ISO-8601 with a space
/// separator, seconds precision, literal ` UTC` suffix.
fn format_utc_timestamp(now: SystemTime) -> String {
    chrono::DateTime::<chrono::Utc>::from(now)
        .format("%Y-%m-%d %H:%M:%S UTC")
        .to_string()
}

/// Converts `value` into the null-terminated C string expected by the
/// `RedisModule_Info*` functions.
///
/// For perf purposes, we strive to avoid allocating a new string if
/// possible—i.e. if `value` doesn't contain any null bytes. Interior null
/// bytes are replaced with `?`.
fn info_cstring(value: String) -> CString {
    match CString::new(value) {
        Ok(cstr) => cstr,
        Err(err) => {
            let mut bytes = err.into_vec();
            for byte in &mut bytes {
                if *byte == 0 {
                    *byte = b'?';
                }
            }
            // SAFETY: We just replaced all null bytes with '?'.
            unsafe { CString::from_vec_unchecked(bytes) }
        }
    }
}

/// Add the current backtrace as a new section to the report printed
/// by RediSearch's INFO command.
///
/// When a Rust panic was stashed in [`PANIC_STASH`], its details are emitted
/// in the same section, ahead of the backtrace.
///
/// # Safety
///
/// `ctx` must be a valid pointer to a `RedisModuleInfoCtx`.
#[unsafe(no_mangle)]
pub extern "C" fn AddToInfo_RustBacktrace(ctx: Option<NonNull<redis_module::RedisModuleInfoCtx>>) {
    let Some(ctx) = ctx else {
        return;
    };

    let backtrace_cstr = info_cstring(std::backtrace::Backtrace::force_capture().to_string());

    // SAFETY: `RedisModule_InfoAddSection` has been initialized during module load.
    let info_add_section = unsafe { redis_module::RedisModule_InfoAddSection.unwrap() };
    // SAFETY: `RedisModule_InfoAddFieldCString` has been initialized during module load.
    let info_add_field_cstring = unsafe { redis_module::RedisModule_InfoAddFieldCString.unwrap() };

    // SAFETY: `ctx` is a valid pointer to a `RedisModuleInfoCtx`.
    unsafe { info_add_section(ctx.as_ptr(), c"rust_backtrace".as_ptr()) };

    // `get` yields None if a crash races the first panic's `set`, losing the
    // fields rather than blocking the report.
    if let Some(stashed) = PANIC_STASH.get() {
        let payload = info_cstring(stashed.payload.clone());
        let location = info_cstring(stashed.location.clone());
        let recorded_at = info_cstring(stashed.recorded_at.clone());
        // SAFETY: `ctx` is a valid pointer and `payload` is a valid null-terminated C string.
        unsafe {
            info_add_field_cstring(ctx.as_ptr(), c"panic_payload".as_ptr(), payload.as_ptr())
        };
        // SAFETY: `ctx` is a valid pointer and `location` is a valid null-terminated C string.
        unsafe {
            info_add_field_cstring(ctx.as_ptr(), c"panic_location".as_ptr(), location.as_ptr())
        };
        // SAFETY: `ctx` is a valid pointer and `recorded_at` is a valid null-terminated C string.
        unsafe {
            info_add_field_cstring(
                ctx.as_ptr(),
                c"panic_recorded_at".as_ptr(),
                recorded_at.as_ptr(),
            )
        };
    }

    // SAFETY: `ctx` is a valid pointer and `backtrace_cstr` is a valid null-terminated C string.
    unsafe { info_add_field_cstring(ctx.as_ptr(), c"backtrace".as_ptr(), backtrace_cstr.as_ptr()) };
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{Duration, UNIX_EPOCH};

    fn stashed_panic(payload: &str) -> StashedPanic {
        StashedPanic {
            payload: payload.to_owned(),
            location: "src/crash.rs:1:1".to_owned(),
            recorded_at: "2026-01-01 00:00:00 UTC".to_owned(),
        }
    }

    // The hook fires twice per crash (the real panic, then the nested
    // "cannot unwind" panic at the `extern "C"` boundary): the stash must
    // keep the first panic's details.
    #[test]
    fn stash_is_first_write_wins() {
        let stash: OnceLock<StashedPanic> = OnceLock::new();
        assert!(stash.get().is_none());

        let _ = stash.set(stashed_panic("first"));
        let _ = stash.set(stashed_panic("second"));

        assert_eq!(stash.get().map(|s| s.payload.as_str()), Some("first"));
    }

    // Pins the crash-report timestamp format; the conversion itself is
    // chrono's.
    #[test]
    fn formats_timestamp_as_utc() {
        assert_eq!(format_utc_timestamp(UNIX_EPOCH), "1970-01-01 00:00:00 UTC");
        assert_eq!(
            format_utc_timestamp(UNIX_EPOCH + Duration::from_secs(1_000_000_000)),
            "2001-09-09 01:46:40 UTC"
        );
    }

    #[test]
    fn info_cstring_replaces_interior_null_bytes() {
        assert_eq!(info_cstring("a\0b".to_owned()).to_bytes(), b"a?b");
        assert_eq!(info_cstring("clean".to_owned()).to_bytes(), b"clean");
    }
}
