/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
*/

//! Scan all source files to check if they are prefixed with the expected license header.
//!
//! Rust, C and C++ files carry the header as a block comment; Python files carry the same
//! text as `#` comments. Generated and vendored files are exempt, since their content is
//! either overwritten on the next regeneration or covered by an upstream license.
//!
//! If invoked with `--fix` as an argument, it'll prepend the license header to
//! all files that are missing one. `--root <path>` overrides the scan root, which
//! otherwise is the closest ancestor of the current directory containing `.git`.
use std::{
    env,
    fs::{self, read_to_string, write},
    path::{Path, PathBuf},
};

const LICENSE_HEADER: &str = "\
/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
*/
";

const LICENSE_HEADER_HASH: &str = "\
# Copyright (c) 2006-Present, Redis Ltd.
# All rights reserved.
#
# Licensed under your choice of the Redis Source Available License 2.0
# (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
# GNU Affero General Public License v3 (AGPLv3).
";

/// Directories skipped wherever they occur, identified by name alone.
const SKIPPED_DIR_NAMES: &[&str] = &[".git", "target"];

/// Directories skipped by their path relative to the scan root.
const SKIPPED_DIRS: &[&str] = &[
    // Third-party sources, vendored under their own licenses.
    "deps",
    "src/redisearch_rs/thin_vec",
    "src/redisearch_rs/generational_slab",
    "src/redisearch_rs/utf8parse",
    // Generated by cheadergen from the `*_ffi` crates, which carry the header themselves.
    "src/redisearch_rs/headers",
    // Build output.
    "bin",
];

/// Files skipped by their path relative to the scan root.
const SKIPPED_FILES: &[&str] = &[
    // Copied verbatim from Redis, which ships this header without a license block so that
    // modules under any license can include it.
    "src/redismodule.h",
    // Generated by Lemon from the neighbouring `parser.y`, which carries the header.
    "src/query_parser/v1/parser.c",
    "src/query_parser/v1/parser.h",
    "src/query_parser/v2/parser.c",
    "src/query_parser/v2/parser.h",
    "src/aggregate/expr/parser.c",
    "src/aggregate/expr/parser.h",
    // Generated by Ragel from the neighbouring `lexer.rl`, which carries the header.
    "src/query_parser/v1/lexer.c",
    "src/query_parser/v2/lexer.c",
    "src/aggregate/expr/lexer.c",
    // Generated by `srcutil/gen_command_info.py`, which carries the header.
    "src/command_info/command_info.c",
    "src/command_info/command_info.h",
    // The Lemon parser generator itself, third-party and public domain.
    "srcutil/lemon.c",
    "srcutil/lempar.c",
    // Copied from the Rust standard library; see the module docs for its license.
    "src/redisearch_rs/inverted_index/src/controlled_cursor.rs",
    // Carry a different grant to the one above, which only a human may change: the wording
    // Redis upstream uses, and an older RSALv2-or-SSPLv1 grant that does not offer AGPLv3.
    "src/rejson_api.h",
    "src/util/strconv.h",
];

/// How a source file spells comments, and therefore which rendering of the header it carries.
#[derive(Clone, Copy, PartialEq, Eq)]
enum CommentStyle {
    /// A `/* ... */` block, used by Rust, C and C++.
    Block,
    /// A run of `#` lines, used by Python.
    Hash,
}

impl CommentStyle {
    /// The style for `extension`, or [`None`] if files with that extension are not checked.
    fn for_extension(extension: &str) -> Option<Self> {
        match extension {
            "rs" | "c" | "h" | "cpp" | "hpp" | "cc" | "cxx" => Some(Self::Block),
            "py" => Some(Self::Hash),
            _ => None,
        }
    }

    const fn header(self) -> &'static str {
        match self {
            Self::Block => LICENSE_HEADER,
            Self::Hash => LICENSE_HEADER_HASH,
        }
    }
}

fn main() {
    let args: Vec<String> = env::args().collect();
    let fix = args.iter().any(|arg| arg == "--fix");
    let root = match args.iter().position(|arg| arg == "--root") {
        Some(i) => PathBuf::from(args.get(i + 1).expect("--root needs a path argument")),
        None => repo_root(),
    };
    let mut bad_files = Vec::new();

    visit_dir(&root, &root, fix, &mut bad_files);

    if bad_files.is_empty() {
        println!("✅ All source files contain the license header.");
    } else {
        println!("❌ The following files are missing the license header:");
        for file in &bad_files {
            println!(" - {}", file.display());
        }
        println!("Run `cargo license-fix` to prepend the expected header to all those files.");
        if !fix {
            std::process::exit(1);
        }
    }
}

/// The closest ancestor of the current directory that contains `.git`.
///
/// In a worktree `.git` is a file rather than a directory, so its kind is not checked.
fn repo_root() -> PathBuf {
    let current_dir = env::current_dir().expect("Failed to get current dir");
    current_dir
        .ancestors()
        .find(|dir| dir.join(".git").exists())
        .map(Path::to_path_buf)
        .expect("Failed to find the repository root; pass --root instead")
}

fn visit_dir(root: &Path, dir: &Path, fix: bool, bad_files: &mut Vec<PathBuf>) {
    for entry in fs::read_dir(dir).expect("Failed to read directory") {
        let entry = entry.expect("Failed to read entry");
        let path = entry.path();
        let relative = path.strip_prefix(root).unwrap_or(&path).to_owned();
        let relative = relative.to_string_lossy().replace('\\', "/");

        if path.is_dir() {
            let name = path
                .file_name()
                .and_then(|s| s.to_str())
                .unwrap_or_default();
            if SKIPPED_DIR_NAMES.contains(&name) || SKIPPED_DIRS.contains(&relative.as_str()) {
                continue;
            }
            visit_dir(root, &path, fix, bad_files);
        } else if SKIPPED_FILES.contains(&relative.as_str()) {
            continue;
        } else if let Some(style) = path
            .extension()
            .and_then(|s| s.to_str())
            .and_then(CommentStyle::for_extension)
        {
            check_file(&path, style, fix, bad_files);
        }
    }
}

fn check_file(path: &Path, style: CommentStyle, fix: bool, bad_files: &mut Vec<PathBuf>) {
    let content = read_to_string(path).unwrap_or_default();
    // Empty files carry no code to license; `__init__.py` package markers are the common case.
    if content.trim().is_empty() {
        return;
    }

    let (prologue, body) = split_prologue(&content, style);
    // The trailing newline is left off so that a header closed as `*/#pragma once` still counts.
    if normalize(body).starts_with(style.header().trim_end()) {
        return;
    }

    if fix {
        let new_content = format!("{prologue}{}\n{body}", style.header());
        write(path, new_content).expect("Failed to write file");
        println!("🛠️  Fixed: {}", path.display());
    } else {
        bad_files.push(path.to_path_buf());
    }
}

/// Rewrite the spellings that vary across the tree but do not change the header's text.
///
/// Part of the C sources use CRLF, the block comment is closed as both `*/` and ` */`, and a
/// few files open with a blank line.
fn normalize(content: &str) -> String {
    content
        .replace('\r', "")
        .replace("\n */", "\n*/")
        .trim_start_matches('\n')
        .to_owned()
}

/// Split off the lines that must stay above the license header, returning them with the rest.
///
/// A Python shebang only works on the first line, and PEP 263 only honours an encoding
/// declaration on the first two lines, so both outrank the header.
fn split_prologue(content: &str, style: CommentStyle) -> (&str, &str) {
    if style != CommentStyle::Hash {
        return ("", content);
    }

    let mut offset = 0;
    for (index, line) in content.split_inclusive('\n').take(2).enumerate() {
        let is_shebang = index == 0 && line.starts_with("#!");
        if is_shebang || is_coding_declaration(line) {
            offset += line.len();
        } else {
            break;
        }
    }
    content.split_at(offset)
}

/// Whether `line` is a PEP 263 encoding declaration, such as `# -*- coding: utf-8 -*-`.
fn is_coding_declaration(line: &str) -> bool {
    let Some(rest) = line.strip_prefix('#') else {
        return false;
    };
    let Some(rest) = rest.find("coding").map(|i| &rest[i + "coding".len()..]) else {
        return false;
    };
    rest.starts_with([':', '='])
}
