#define LOWEST                           1
#define TILDE                            2
#define TAGLIST                          3
#define QUOTE                            4
#define COLON                            5
#define MINUS                            6
#define NUMBER                           7
#define STOPWORD                         8
#define TERMLIST                         9
#define TERM                            10
#define PREFIX                          11
#define SUFFIX                          12
#define CONTAINS                        13
#define PERCENT                         14
#define ATTRIBUTE                       15
#define LP                              16
#define RP                              17
#define MODIFIER                        18
#define AND                             19
#define OR                              20
#define ORX                             21
#define ARROW                           22
#define STAR                            23
#define SEMICOLON                       24
#define LB                              25
#define RB                              26
#define LSQB                            27
#define RSQB                            28
