#define LOWEST                           1
#define TILDE                            2
#define TAGLIST                          3
#define QUOTE                            4
#define COLON                            5
#define MINUS                            6
#define NUMBER                           7
#define STOPWORD                         8
#define TERMLIST                         9
#define TERM                            10
#define PREFIX                          11
#define PERCENT                         12
#define ATTRIBUTE                       13
#define LP                              14
#define RP                              15
#define MODIFIER                        16
#define AND                             17
#define OR                              18
#define ORX                             19
#define ARROW                           20
#define STAR                            21
#define SEMICOLON                       22
#define LB                              23
#define RB                              24
#define LSQB                            25
#define RSQB                            26
