/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
*/

//! Line counting and macro detection for C and C++ sources.

/// Returns `src` with every comment replaced by spaces, keeping newlines so
/// that line numbers are preserved. String and character literals are kept
/// verbatim, so comment markers inside them are not mistaken for comments.
pub fn strip_comments(src: &str) -> String {
    #[derive(PartialEq)]
    enum State {
        Code,
        LineComment,
        BlockComment,
        Literal(char),
    }

    let mut out = String::with_capacity(src.len());
    let mut state = State::Code;
    let mut chars = src.chars().peekable();
    while let Some(c) = chars.next() {
        match state {
            State::Code => match (c, chars.peek()) {
                ('/', Some('/')) => {
                    chars.next();
                    out.push_str("  ");
                    state = State::LineComment;
                }
                ('/', Some('*')) => {
                    chars.next();
                    out.push_str("  ");
                    state = State::BlockComment;
                }
                ('"' | '\'', _) => {
                    out.push(c);
                    state = State::Literal(c);
                }
                _ => out.push(c),
            },
            State::LineComment => {
                if c == '\n' {
                    out.push('\n');
                    state = State::Code;
                }
            }
            State::BlockComment => {
                if c == '*' && chars.peek() == Some(&'/') {
                    chars.next();
                    out.push_str("  ");
                    state = State::Code;
                } else {
                    out.push(if c == '\n' { '\n' } else { ' ' });
                }
            }
            State::Literal(quote) => {
                out.push(c);
                if c == '\\' {
                    if let Some(escaped) = chars.next() {
                        out.push(escaped);
                    }
                } else if c == quote || c == '\n' {
                    // An unterminated literal cannot span lines; recovering at
                    // the newline keeps a stray quote from swallowing the file.
                    state = State::Code;
                }
            }
        }
    }
    out
}

/// Counts the lines of `src` that hold code, ignoring blank lines, comments
/// and `#include` directives.
pub fn count_code_lines(src: &str) -> u64 {
    strip_comments(src)
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !is_include(line))
        .count() as u64
}

fn is_include(line: &str) -> bool {
    line.strip_prefix('#')
        .is_some_and(|rest| rest.trim_start().starts_with("include"))
}

/// Counts the lines of `src` that start with an invocation of one of the
/// `macros`, e.g. `TEST_F(Suite, Name)`.
///
/// Only invocations at the start of a line count, which skips both the
/// macros' `#define`s and any mention of them in the middle of an expression.
pub fn count_macro_invocations(src: &str, macros: &[&str]) -> u64 {
    strip_comments(src)
        .lines()
        .filter(|line| {
            let line = line.trim_start();
            macros.iter().any(|name| {
                line.strip_prefix(name)
                    .is_some_and(|rest| rest.trim_start().starts_with('('))
            })
        })
        .count() as u64
}

/// Whether `src` was produced by a code generator rather than written by hand.
///
/// `sibling_exists` reports whether a file with the given path exists in the
/// same tree; a `.c` file next to a Ragel (`.rl`) or Lemon (`.y`) grammar of
/// the same name is that grammar's output.
pub fn is_generated(path: &str, src: &str, sibling_exists: impl Fn(&str) -> bool) -> bool {
    if let Some(stem) = path.strip_suffix(".c")
        && (sibling_exists(&format!("{stem}.rl")) || sibling_exists(&format!("{stem}.y")))
    {
        return true;
    }
    src.lines()
        .take(30)
        .any(|line| line.to_ascii_lowercase().contains("generated by"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ignores_comments_blank_lines_and_includes() {
        let src = r#"
#include <stdio.h>
# include "foo.h"
// a comment
/* a
   block */
int x = 1; /* trailing */
const char *s = "// not a comment";
const char *t = "/* nor this */";
char c = '"';
int y = 2;
"#;
        assert_eq!(count_code_lines(src), 5);
    }

    #[test]
    fn code_after_block_comment_on_same_line_counts() {
        assert_eq!(count_code_lines("/* x */ int a;\n/* y\n */ int b;\n"), 2);
    }

    #[test]
    fn finds_macro_invocations_at_line_start() {
        let src = r#"
#define TESTFUNC(f) f()
TEST_F(Suite, A) {}
  TEST (Suite, B) {}
// TEST(Suite, C) {}
x = TEST(1);
TESTS_RUN();
"#;
        assert_eq!(count_macro_invocations(src, &["TEST", "TEST_F"]), 2);
        assert_eq!(count_macro_invocations(src, &["TESTFUNC"]), 0);
    }

    #[test]
    fn detects_generated_files() {
        assert!(is_generated("p/lexer.c", "", |p| p == "p/lexer.rl"));
        assert!(is_generated("p/parser.c", "", |p| p == "p/parser.y"));
        assert!(is_generated(
            "a.c",
            "// This file is generated by gen.py\n",
            |_| false
        ));
        assert!(!is_generated("a.c", "int main() {}\n", |_| false));
    }
}
