[package]
name = "inverted_index_bencher"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[[bench]]
name = "encoding_decoding"
harness = false

[[bench]]
name = "garbage_collection"
harness = false

[[bench]]
name = "add_record"
harness = false

[dependencies]
buffer.workspace = true
criterion.workspace = true
ffi.workspace = true
rqe_core.workspace = true
index_result.workspace = true
inverted_index.workspace = true
query_term.workspace = true
itertools.workspace = true
redis_mock.workspace = true
workspace_hack.workspace = true
