/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
*/

//! Query node types, flags, and QAST validation flags.
//!
//! # Why is this a separate crate?
//!
//! `QueryNodeType`, `QueryNodeFlags`, and `QASTValidationFlags` are the source
//! of truth for query node type discriminants, per-node flags, and AST-level
//! validation flags, shared between Rust and C. cheadergen generates the C
//! header (`query_node_type.h`) from this crate, and the C headers
//! `query_node.h` and `query.h` include it.
//!
//! If these types lived inside a larger crate, its generated header would need
//! to include `query_node.h` (for types used in function signatures), while
//! `query_node.h` would need to include that header (for `QueryNodeType`),
//! creating a circular include.
//!
//! By placing the enums in their own crate with their own header, we break
//! the cycle: `query_node.h` includes `query_node_type.h` (tiny, no other
//! includes), and other generated headers can include `query_node.h` without
//! circularity.

use std::ffi::c_char;

use enumflags2::bitflags;

use rqe_core::{FieldIndex, FieldMask};

/// The type of a query node.
///
/// This enum is the single source of truth for query node type discriminants.
/// The C-side definition is generated by cheadergen from this Rust enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
#[cheadergen::config(export, prefix_with_name)]
pub enum QueryNodeType {
    Phrase = 1,
    Union = 2,
    Token = 3,
    Numeric = 4,
    Not = 5,
    Optional = 6,
    Geo = 7,
    Geometry = 8,
    Prefix = 9,
    Ids = 10,
    Wildcard = 11,
    Tag = 12,
    Fuzzy = 13,
    LexRange = 14,
    Vector = 15,
    WildcardQuery = 16,
    Null = 17,
    Missing = 18,
    Max = 19,
}

impl QueryNodeType {
    /// Returns the name of this query node type as a static string.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Phrase => "PHRASE",
            Self::Union => "UNION",
            Self::Token => "TOKEN",
            Self::Numeric => "NUMERIC",
            Self::Not => "NOT",
            Self::Optional => "OPTIONAL",
            Self::Geo => "GEO",
            Self::Geometry => "GEOMETRY",
            Self::Prefix => "PREFIX",
            Self::Ids => "IDS",
            Self::Wildcard => "WILDCARD",
            Self::Tag => "TAG",
            Self::Fuzzy => "FUZZY",
            Self::LexRange => "LEXRANGE",
            Self::Vector => "VECTOR",
            Self::WildcardQuery => "WILDCARD_QUERY",
            Self::Null => "NULL",
            Self::Missing => "MISSING",
            Self::Max => "MAX",
        }
    }
}

impl std::fmt::Display for QueryNodeType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<u32> for QueryNodeType {
    type Error = u32;

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::Phrase),
            2 => Ok(Self::Union),
            3 => Ok(Self::Token),
            4 => Ok(Self::Numeric),
            5 => Ok(Self::Not),
            6 => Ok(Self::Optional),
            7 => Ok(Self::Geo),
            8 => Ok(Self::Geometry),
            9 => Ok(Self::Prefix),
            10 => Ok(Self::Ids),
            11 => Ok(Self::Wildcard),
            12 => Ok(Self::Tag),
            13 => Ok(Self::Fuzzy),
            14 => Ok(Self::LexRange),
            15 => Ok(Self::Vector),
            16 => Ok(Self::WildcardQuery),
            17 => Ok(Self::Null),
            18 => Ok(Self::Missing),
            19 => Ok(Self::Max),
            other => Err(other),
        }
    }
}

/// Flags indicating which syntax features are enabled for a query AST.
///
/// This enum is the single source of truth for QAST validation flag bits.
/// The C-side definition is generated by cheadergen from this Rust enum.
#[cheadergen::config(export)]
pub type QASTValidationFlagsSet = enumflags2::BitFlags<QASTValidationFlags>;

/// Per-AST flags stored in `QueryAST::validationFlags` (C struct defined in
/// `query.h`) that control which syntax features are allowed during query
/// validation (weight attributes, vector queries, etc.).
///
/// This enum is the single source of truth for QAST validation flag bits.
/// The C-side definition is generated by cheadergen from this Rust enum.
#[bitflags]
#[repr(u32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
#[cheadergen::config(export, prefix_with_name)]
pub enum QASTValidationFlags {
    /// Weight attribute is not allowed.
    NoWeight = 0x01,
    /// Vector queries are not allowed.
    NoVector = 0x02,
}

/// Bitflags for per-node query options.
///
/// This enum is the single source of truth for query node flag bits.
/// The C-side definition is generated by cheadergen from this Rust enum.
#[cheadergen::config(export)]
pub type QueryNodeFlagsSet = enumflags2::BitFlags<QueryNodeFlags>;

/// Per-node flags stored in [`QueryNodeOptions::flags`] that control how
/// an individual query node is evaluated (verbatim matching, tag semantics,
/// vector distance handling, etc.).
///
/// This enum is the single source of truth for query node flag bits.
/// The C-side definition is generated by cheadergen from this Rust enum.
#[bitflags]
#[repr(u32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
#[cheadergen::config(export, prefix_with_name)]
pub enum QueryNodeFlags {
    /// Prevents stemming, synonym expansion, and other query-time token
    /// transformations. Set automatically for numeric/size literals and
    /// for parameters that resolve to numeric values.
    Verbatim = 0x01,
    /// Indicates that the `inOrder` option was explicitly set via a query
    /// attribute, so it should be checked even when not at the top level.
    OverriddenInOrder = 0x02,
    /// The node can produce a distance metric (e.g. vector similarity
    /// score). Enables the `yield_distance_as` query attribute.
    YieldsDistance = 0x04,
    /// The tag field backing this node indexes empty values, so empty
    /// documents should be matched. Only meaningful when [`Self::IsTag`] is set.
    IndexesEmpty = 0x08,
    /// The node is under a TAG index. Used together with [`Self::IndexesEmpty`]
    /// to decide whether empty-value documents are included.
    IsTag = 0x10,
    /// Marks this as the main vector node in a hybrid vector subquery.
    HybridVectorSubqueryNode = 0x20,
    /// Suppresses the automatic distance field in the result set. Set when
    /// no explicit `AS` alias is provided for the vector score field, so
    /// the internally generated name is hidden from the user.
    HideVectorDistanceField = 0x40,
}

/// Phonetic matching mode for a query node.
///
/// Controls whether phonetic expansion is applied when matching tokens
/// against indexed terms.
///
/// This enum is the single source of truth for phonetic mode values.
/// The C-side definition is generated by cheadergen from this Rust enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
#[cheadergen::config(export, prefix_with_name)]
pub enum PhoneticMode {
    /// Defer to the field declaration: if the field was created with
    /// phonetic matching, it is used; otherwise it is not.
    Default = 0,
    /// Force phonetic matching on, regardless of the field declaration.
    Enabled = 1,
    /// Force phonetic matching off, regardless of the field declaration.
    Disabled = 2,
}
/// Various modifiers and options that can apply to the entire query or any
/// sub-query of it.
#[repr(C)]
#[derive(Debug)]
#[cheadergen::config(export, rename_all = "camelCase")]
pub struct QueryNodeOptions {
    /// Bitflags controlling evaluation behavior for this node.
    pub flags: QueryNodeFlagsSet,
    /// Bitmask of fields this node matches against. Intersected with the
    /// top-level search field mask at evaluation time. Defaults to
    /// `RS_FIELDMASK_ALL`.
    pub field_mask: FieldMask,
    /// Index of the specific field this node targets (used by tag queries
    /// to pass the field index to the tag iterator).
    pub field_index: FieldIndex,
    /// Maximum allowed slop (distance between terms) for phrase matching.
    /// A value of `-1` means no local override (the top-level default
    /// applies).
    pub max_slop: i32,
    /// Whether child terms must appear in order within the slop window.
    pub in_order: i32,
    /// Scoring weight multiplier for this node. Defaults to `1.0`.
    pub weight: f64,
    /// Phonetic matching mode for this node.
    pub phonetic: PhoneticMode,
    /// Name of the distance field to emit in results (set via the
    /// `yield_distance_as` query attribute on vector nodes). Owned
    /// null-terminated C string, freed with `rm_free` when the query
    /// node is destroyed. `NULL` when no distance field is requested.
    pub dist_field: *mut c_char,
    /// Whether [`weight`](Self::weight) was explicitly set by the user in
    /// the query (as opposed to the default of `1.0`).
    pub explicit_weight: bool,
}
