/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
*/

//! The type of a query node.
//!
//! # Why is this a separate crate?
//!
//! `QueryNodeType` is the source of truth for query node type discriminants,
//! shared between Rust and C. cbindgen generates the C header
//! (`query_node_type.h`) from this crate, and the C header `query_node.h`
//! includes it.
//!
//! If `QueryNodeType` lived inside a larger crate, its cbindgen-generated
//! header would need to include `query_node.h` (for types used in function
//! signatures), while `query_node.h` would need to include that header (for
//! `QueryNodeType`), creating a circular include.
//!
//! By placing the enum in its own crate with its own header, we break the
//! cycle: `query_node.h` includes `query_node_type.h` (tiny, no other
//! includes), and other generated headers can include `query_node.h` without
//! circularity.

/// The type of a query node.
///
/// This enum is the single source of truth for query node type discriminants.
/// The C-side definition is generated by cbindgen from this Rust enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum QueryNodeType {
    Phrase = 1,
    Union = 2,
    Token = 3,
    Numeric = 4,
    Not = 5,
    Optional = 6,
    Geo = 7,
    Geometry = 8,
    Prefix = 9,
    Ids = 10,
    Wildcard = 11,
    Tag = 12,
    Fuzzy = 13,
    LexRange = 14,
    Vector = 15,
    WildcardQuery = 16,
    Null = 17,
    Missing = 18,
    Max = 19,
}

impl QueryNodeType {
    /// Returns the name of this query node type as a static string.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Phrase => "PHRASE",
            Self::Union => "UNION",
            Self::Token => "TOKEN",
            Self::Numeric => "NUMERIC",
            Self::Not => "NOT",
            Self::Optional => "OPTIONAL",
            Self::Geo => "GEO",
            Self::Geometry => "GEOMETRY",
            Self::Prefix => "PREFIX",
            Self::Ids => "IDS",
            Self::Wildcard => "WILDCARD",
            Self::Tag => "TAG",
            Self::Fuzzy => "FUZZY",
            Self::LexRange => "LEXRANGE",
            Self::Vector => "VECTOR",
            Self::WildcardQuery => "WILDCARD_QUERY",
            Self::Null => "NULL",
            Self::Missing => "MISSING",
            Self::Max => "MAX",
        }
    }
}

impl std::fmt::Display for QueryNodeType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<u32> for QueryNodeType {
    type Error = u32;

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::Phrase),
            2 => Ok(Self::Union),
            3 => Ok(Self::Token),
            4 => Ok(Self::Numeric),
            5 => Ok(Self::Not),
            6 => Ok(Self::Optional),
            7 => Ok(Self::Geo),
            8 => Ok(Self::Geometry),
            9 => Ok(Self::Prefix),
            10 => Ok(Self::Ids),
            11 => Ok(Self::Wildcard),
            12 => Ok(Self::Tag),
            13 => Ok(Self::Fuzzy),
            14 => Ok(Self::LexRange),
            15 => Ok(Self::Vector),
            16 => Ok(Self::WildcardQuery),
            17 => Ok(Self::Null),
            18 => Ok(Self::Missing),
            19 => Ok(Self::Max),
            other => Err(other),
        }
    }
}
