#!/bin/sh
''''[ ! -z $VIRTUAL_ENV ] && exec python -u -- "$0" ${1+"$@"}; command -v python3 > /dev/null && exec python3 -u -- "$0" ${1+"$@"}; exec python2 -u -- "$0" ${1+"$@"} # '''

import sys
import os
import click
import re
import json
import requests
import urllib3

HERE = os.path.dirname(__file__)
ROOT = os.path.abspath(os.path.join(HERE, "../.."))
READIES = os.path.abspath(os.path.join(ROOT, "deps/readies"))
sys.path.insert(0, READIES)
import paella

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


VERBOSE = 0
NOP = False
OPERETO3_URL = "opereto.qa.redislabs.com"


RLEC_PLATFORMS = {
    'xenial': { 
        'os':  'Linux-ubuntu16.04',
        'env': 'xenial-amd64-aws' },
    'bionic': {
        'os': 'Linux-ubuntu18.04',
        'env': 'bionic-amd64-aws' },
    'centos7': {
        'os': 'Linux-rhel7',
        'env': 'rhel7.7-x86_64-aws' },
#    'centos8': {
#        'os': 'Linux-rhel8',
#        'env': 'rhel8-x86_64-aws' },
    'rocky8': {
        'os': 'Linux-rhel8',
        'env': 'rhel8-x86_64-aws' }
}


class Command1(click.Command):
    def header(self):
        return r'''
                      █████                      █████           
                     ░░███                      ░░███            
  ████████  ██████   ███████    ██████   █████  ███████    █████ 
 ███░░███  ░░░░░███ ░░░███░    ███░░███ ███░░  ░░░███░    ███░░  
░███ ░███   ███████   ░███    ░███████ ░░█████   ░███    ░░█████ 
░███ ░███  ███░░███   ░███ ███░███░░░   ░░░░███  ░███ ███ ░░░░███
░░███████ ░░████████  ░░█████ ░░██████  ██████   ░░█████  ██████ 
 ░░░░░███  ░░░░░░░░    ░░░░░   ░░░░░░  ░░░░░░     ░░░░░  ░░░░░░  
     ░███                                                        
     █████                                                       
    ░░░░░                                                        

'''

    def footer(self):
        return '''

Other configuration:
RS_VERSIONS file includes Redis Enterprive versions for release tests.

'''

    def get_help(self, ctx):
        h = super().get_help(ctx)
        return self.header() + h + self.footer()


class Test:
    def __init__(self, token, test_fname, modver, snapshot, rlecver, osnick, light):
        global NOP, VERBOSE

        self.token = token
        self.test_fname = test_fname
        modver = re.sub(r'^v(.*)', r'\1', modver)
        self.modver = modver
        self.snapshot = snapshot
        self.rlecver = rlecver
        self.osnick = osnick
        self.light = light
        self.module_name = "RediSearchLight" if self.light else "RediSearch"

        ENV['SEARCH_VERSION'] = modver
        os.environ['SEARCH_DIR'] = 'redisearch'

        if not light:
            ENV['SEARCH_FILE_PREFIX'] = 'redisearch'
            ENV['SEARCH_DOWNLOAD_NAME'] = 'search'
            ENV['SEARCH_TEST_NAME'] = 'RediSearchEnterprise'
        else:
            ENV['SEARCH_FILE_PREFIX'] = 'redisearch-light'
            ENV['SEARCH_DOWNLOAD_NAME'] = 'searchlight'
            ENV['SEARCH_TEST_NAME'] = 'RedisearchLight'

        if snapshot:
            ENV['SEARCH_FILE_PREFIX'] = "snapshots/" + ENV['SEARCH_FILE_PREFIX']

        ENV['RLEC_VERSION'] = rlecver
        ENV['RLEC_ARCH'] = 'x86_64'
        
        ENV['REJSON_VERSION'] = '2.0.7'
        ENV['REJSON_DIR'] = 'rejson'
        ENV['REJSON_FILE_PREFIX'] = 'rejson'

        self.xtx_vars = ['SEARCH_VERSION', 'SEARCH_DIR', 'SEARCH_FILE_PREFIX',
                         'SEARCH_TEST_NAME', 'SEARCH_DOWNLOAD_NAME',
                         'RLEC_VERSION', 'RLEC_ENV', 'RLEC_OS', 'RLEC_ARCH',
                         'REJSON_VERSION', 'REJSON_DIR', 'REJSON_FILE_PREFIX']

    def run(self):
        found_osnick = False
        click.echo(f"Testing {self.module_name}/{self.modver} for RS {self.rlecver}:")
        for osnick in RLEC_PLATFORMS.keys():
            if self.osnick is None or osnick == self.osnick:
                found_osnick = True
                rlec_os = RLEC_PLATFORMS[osnick]['os']
                rlec_env = RLEC_PLATFORMS[osnick]['env']
                self.run_for_os(rlec_os, rlec_env)
        if not found_osnick:
            click.echo(f"    osnick {osnick}: not found")

    def run_for_os(self, rlec_os, rlec_env):
        ENV['RLEC_OS'] = rlec_os
        ENV['RLEC_ENV'] = rlec_env

        global NOP, VERBOSE
        var_args = ' '.join(map(lambda v: f"-e {v}", self.xtx_vars))
        
        try:
            if VERBOSE > 1:
                print(f'{READIES}/bin/xtx {var_args} {self.test_fname}')

            rest = sh(f'{READIES}/bin/xtx --strict {var_args} {self.test_fname}')
        except Exception as x:
            fatal(x)

        try:
            rest_json = json.loads(rest)
            if VERBOSE > 0:
                print(json.dumps(rest_json, indent=2))
        except Exception as x:
            print(rest)
            fatal(x)

        if NOP:
            click.echo(f"    {rlec_os}: https://{OPERETO3_URL}/ui#dashboard/flow/...")
            return 0

        res = requests.post(f"https://{OPERETO3_URL}/processes", verify=False,
                            headers={'Authorization': f'Bearer {self.token}',
                                     'Content-Type': 'application/json'},
                            data=rest)
        if not res.ok:
            click.echo(f"    {rlec_os}: error: {res.reason} [{res.status_code}]")
            return 1
        j = json.loads(res.content)
        if j['status'] != 'success':
            err = j['text']
            click.echo(f"    {rlec_os}: error: {err}")
            return 1

        self.id = j['data'][0]
        # click.echo(f"Tests running on {desc}")
        click.echo(f"    {rlec_os}: https://{OPERETO3_URL}/ui#dashboard/flow/{self.id}")
        return 0


@click.command(help='Invoke QA Automation tests', cls=Command1)
@click.option('--token', default=None, help='QA automation (Opereto) token (also: QA_AUTOMATION_TOKEN env var)')
@click.option('--test', '-t', default='common', help='Name of .json parameters file')
@click.option('--modver', '-m', default='master', help='Module version to test. Default: master')
@click.option('--snapshot', '-s', is_flag=True, default=False, help='Test a snapshoy module version')
@click.option('--rlecver', '-r', default=None, help='Test for a RLEC version`')
@click.option('--osnick', default=None, help='Test for OSNICK`')
@click.option('--light', is_flag=True, default=False, help='Test RediSearch Light')
@click.option('--quick', is_flag=True, default=False, help='Only test one RS version')
@click.option('--nop', is_flag=True, default=False, help='Dry run')
@click.option('--verbose', '-v', is_flag=True, default=False, help='Be verbose')
@click.option('--verbosity', type=int, default=0, help='Verbosity level')
def main(token, test, modver, snapshot, rlecver, osnick, light, quick, nop, verbose, verbosity, *args, **kwargs):
    global NOP, VERBOSE
    VERBOSE = 1 if verbose else verbosity
    NOP = nop

    if token is None:
        token = os.getenv('QA_AUTOMATION_TOKEN')
    if token is None and not nop:
        raise click.ClickException('QA automation token is missing.')
    test_fname = os.path.join(HERE, f'{test}.json')
    if not os.path.exists(test_fname):
        raise click.ClickException(f"Invalid test name: {test}")

    if rlecver is not None:
        Test(token, test_fname, modver, snapshot, rlecver, osnick, light).run()
    else:
        rs_versions = paella.flines(os.path.join(HERE, 'RS_VERSIONS'))
        if quick:
            rs_versions = [rs_versions[0]]
        for rlecver in rs_versions:
            Test(token, test_fname, modver, snapshot, rlecver, osnick, light).run()


if __name__ == '__main__':
    main()
