/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
*/

//! The type of a query iterator.
//!
//! # Why is this a separate crate?
//!
//! `IteratorType` is the source of truth for iterator type discriminants, shared
//! between Rust and C. cbindgen generates the C header (`iterator_type.h`)
//! from this crate, and the C header `iterator_api.h` includes it.
//!
//! If `IteratorType` lived inside `rqe_iterators`, its cbindgen-generated header
//! (`iterators_rs.h`) would need to include `iterator_api.h` (for `QueryIterator`
//! used in function signatures), while `iterator_api.h` would need to include
//! `iterators_rs.h` (for `IteratorType`), creating a circular include.
//!
//! By placing the enum in its own crate with its own header, we break the cycle:
//! `iterator_api.h` includes `iterator_type.h` (tiny, no other includes),
//! and `iterators_rs.h` includes `iterator_api.h` (which already has the enum).
//!
//! This crate can be deleted once `QueryIterator` is fully ported to Rust and the
//! circular dependency no longer exists.

/// The type of a query iterator.
///
/// This enum is the single source of truth for iterator type discriminants.
/// The C-side definition is generated by cbindgen from this Rust enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum IteratorType {
    InvIdxNumeric = 0,
    InvIdxTerm = 1,
    InvIdxWildcard = 2,
    InvIdxMissing = 3,
    InvIdxTag = 4,
    Hybrid = 5,
    Union = 6,
    Intersect = 7,
    Not = 8,
    NotOptimized = 9,
    Optional = 10,
    OptionalOptimized = 11,
    Wildcard = 12,
    Empty = 13,
    IdListSorted = 14,
    IdListUnsorted = 15,
    MetricSortedById = 16,
    MetricSortedByScore = 17,
    Profile = 18,
    Optimus = 19,
    GeoShape = 20,
    /// Used only in tests.
    Mock = 21,
    Max = 22,
}

impl IteratorType {
    /// Returns `true` for leaf iterators (no children to profile).
    ///
    /// Leaf iterators have no `ProfileChildren` callback in the C vtable.
    /// Compound iterators have children that must be profiled recursively.
    pub const fn is_leaf(self) -> bool {
        match self {
            Self::InvIdxNumeric
            | Self::InvIdxTerm
            | Self::InvIdxWildcard
            | Self::InvIdxMissing
            | Self::InvIdxTag
            | Self::Wildcard
            | Self::Empty
            | Self::IdListSorted
            | Self::IdListUnsorted
            | Self::MetricSortedById
            | Self::MetricSortedByScore
            | Self::Profile
            | Self::GeoShape
            | Self::Mock => true,

            Self::Hybrid
            | Self::Union
            | Self::Intersect
            | Self::Not
            | Self::NotOptimized
            | Self::Optional
            | Self::OptionalOptimized
            | Self::Optimus => false,

            Self::Max => unreachable!(),
        }
    }

    /// Returns the name of this iterator type as a static string.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::InvIdxNumeric => "INV_IDX_NUMERIC",
            Self::InvIdxTerm => "INV_IDX_TERM",
            Self::InvIdxWildcard => "INV_IDX_WILDCARD",
            Self::InvIdxMissing => "INV_IDX_MISSING",
            Self::InvIdxTag => "INV_IDX_TAG",
            Self::Hybrid => "HYBRID",
            Self::Union => "UNION",
            Self::Intersect => "INTERSECT",
            Self::Not => "NOT",
            Self::NotOptimized => "NOT_OPTIMIZED",
            Self::Optional => "OPTIONAL",
            Self::OptionalOptimized => "OPTIONAL_OPTIMIZED",
            Self::Wildcard => "WILDCARD",
            Self::Empty => "EMPTY",
            Self::IdListSorted => "ID_LIST_SORTED",
            Self::IdListUnsorted => "ID_LIST_UNSORTED",
            Self::MetricSortedById => "METRIC_SORTED_BY_ID",
            Self::MetricSortedByScore => "METRIC_SORTED_BY_SCORE",
            Self::Profile => "PROFILE",
            Self::Optimus => "OPTIMUS",
            Self::GeoShape => "GEO_SHAPE",
            Self::Mock => "MOCK",
            Self::Max => "MAX",
        }
    }
}

impl std::fmt::Display for IteratorType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<u32> for IteratorType {
    type Error = u32;

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::InvIdxNumeric),
            1 => Ok(Self::InvIdxTerm),
            2 => Ok(Self::InvIdxWildcard),
            3 => Ok(Self::InvIdxMissing),
            4 => Ok(Self::InvIdxTag),
            5 => Ok(Self::Hybrid),
            6 => Ok(Self::Union),
            7 => Ok(Self::Intersect),
            8 => Ok(Self::Not),
            9 => Ok(Self::NotOptimized),
            10 => Ok(Self::Optional),
            11 => Ok(Self::OptionalOptimized),
            12 => Ok(Self::Wildcard),
            13 => Ok(Self::Empty),
            14 => Ok(Self::IdListSorted),
            15 => Ok(Self::IdListUnsorted),
            16 => Ok(Self::MetricSortedById),
            17 => Ok(Self::MetricSortedByScore),
            18 => Ok(Self::Profile),
            19 => Ok(Self::Optimus),
            20 => Ok(Self::GeoShape),
            21 => Ok(Self::Mock),
            22 => Ok(Self::Max),
            other => Err(other),
        }
    }
}
