#!/bin/bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
ROOT=$(cd $HERE/.. && pwd)


if [[ $1 == --help || $1 == help || $HELP == 1 ]]; then
	cat <<-END
		Build RedisJSON module (for Sanitizer)

		build-redisjson [--help|help]

		Argument variables:
		BINROOT=dir        Build into dir
		BRANCH=name        Use given branch (default: master)
		SAN=mode           Clang Sanitizer mode (address|memory)
		MODULE_FILE=file   Write module path into `file`
		FORCE=1            Force rebuild
		NOP=1              No operation
		HELP=1             Show help

	END
	exit 0
fi


if [[ -n $SAN && $SAN != address && $SAN != memory ]]; then
	echo "Invalid SAN setting: '$SAN'"
	exit 1
fi


BRANCH=${BRANCH:-master}

TARGET_DIR=$BINROOT/RedisJSON/${BRANCH}
echo Building into $TARGET_DIR ...

if [[ $FORCE == 1 ]]; then
	rm -rf $TARGET_DIR
fi

cd $ROOT/deps
if [[ ! -d RedisJSON ]]; then
	git clone --quiet --recursive https://github.com/RedisJSON/RedisJSON.git
fi

cd RedisJSON
git checkout $BRANCH
git pull --quiet --recurse-submodules

# Temporary patch to use a fixed GOOD_NIGHTLY version because of a bug in the
# latest nightly https://github.com/rust-lang/rust/issues/125319
sed -i 's/# GOOD_NIGHTLY=.*/GOOD_NIGHTLY=nightly-2024-05-16/' ./deps/readies/bin/getrust

# Install only rust, because the rest of the dependencies are already installed
if [[ $NOP != 1 ]]; then

	# for RedisJSON build with addess santizer if required
	if [[ -n $SAN ]]; then
		rustup component add rust-src --toolchain nightly
	fi
	BINROOT=$TARGET_DIR make SAN=$SAN
	echo "Created ${TARGET_DIR}/rejson.so"
fi

if [[ -n $MODULE_FILE ]]; then
	echo "${TARGET_DIR}/rejson.so" > $MODULE_FILE
fi
