#!/bin/bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
ROOT=$(cd $HERE/.. && pwd)

WITH_PASSPHRASE=${1:-1}
PHRASE=${2:-MySecretPassPhrase42}

mkdir -p $ROOT/bin/tls
cd $ROOT/bin/tls

[[ -f .generated && $(cat .generated) == $WITH_PASSPHRASE ]] && exit 0

openssl genrsa -out ca.key 2048
openssl req \
    -x509 -new -nodes -sha256 \
    -key ca.key \
    -days 365 \
    -subj '/O=Redis Test/CN=Certificate Authority' \
    -out ca.crt

PASSOUT=""
PASSIN=""
if [[ $WITH_PASSPHRASE == 1 ]]; then
    PASSOUT="-aes256 -passout pass:$PHRASE"
    PASSIN="-passin pass:$PHRASE"
    echo -n $PHRASE > .passphrase
fi

# avoid "Cannot open file:crypto/rand/randfile.c:98:Filename=/github/home/.rnd" error
# (knowm openssl11 bug)
set RANDFILE=.rnd
openssl genrsa $PASSOUT -out redis.key 2048
openssl req \
    -new -sha256 \
    -key redis.key \
    $PASSIN \
    -subj '/O=Redis Test/CN=Server' | \
openssl x509 \
    -req -sha256 \
    -CA ca.crt \
    -CAkey ca.key \
    -CAserial ca.txt \
    -CAcreateserial \
    -days 365 \
    -out redis.crt 2>/dev/null

echo -n $WITH_PASSPHRASE > .generated
