#!/bin/bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
ROOT=$(cd $HERE/.. && pwd)
READIES=$ROOT/deps/readies
. $READIES/shibumi/defs

export HOMEBREW_NO_AUTO_UPDATE=1

$READIES/bin/getpy3
pyenv="$(get_profile_d)/pyenv.sh"
if [[ -f $pyenv ]]; then
	. $pyenv
fi
if [[ $VERBOSE == 1 ]]; then
	python3 --version
	python3 -m pip list
fi

$ROOT/sbin/system-setup.py
if [[ $VERBOSE == 1 ]]; then
	python3 -m pip list
fi
