#!/bin/bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
ROOT=$(cd $HERE/.. && pwd)
READIES=$ROOT/deps/readies
. $READIES/shibumi/defs

export HOMEBREW_NO_AUTO_UPDATE=1

VERBOSE=2 $READIES/bin/getpy3
pyenv="$(get_profile_d)/pyenv.sh"
if [[ -f $pyenv ]]; then
	. $pyenv
fi
python3 --version
python3 -m pip list

$ROOT/sbin/system-setup.py
python3 -m pip list
