#!/bin/bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
ROOT=$(cd $HERE/.. && pwd)
READIES=$ROOT/deps/readies
. $READIES/shibumi/defs

echo "Verifying $DOCKER:"
errfile=$(mktemp /tmp/verify-docker.err.XXXXX)
if DOCKER="$DOCKER" PORT=6401 $READIES/bin/redis-cmd -- ft.config get timeout 2> $errfile | cat | grep TIMEOUT > /dev/null; then
	echo "OK"
	E=0
else
	eprint "There are errors:"
	>&2 cat $errfile
	E=1
fi
rm -f $errfile
exit $E
