#pragma once

/* Warning, this file is autogenerated by cbindgen from `src/redisearch_rs/c_entrypoint/idf_ffi/build.rs`. Don't modify it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Computes the Inverse Document Frequency (IDF) for a term.
 *
 * See [`idf::calculate_idf`] for details.
 */
double CalculateIDF(size_t total_docs, size_t term_docs);

/**
 * Computes the BM25 IDF for a term.
 *
 * See [`idf::calculate_idf_bm25`] for details.
 */
double CalculateIDF_BM25(size_t total_docs, size_t term_docs);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
