#pragma once

/* WARNING: this file was auto-generated by cheadergen from `c_entrypoint/index_spec_cache_ffi`. Do not edit it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
// Defined in field_spec.h.
typedef struct FieldSpec FieldSpec;


/**
 * An immutable snapshot of an index schema's fields and of its rule's
 * special field names (language, score and payload).
 *
 * The index and every query that resolves fields against it share the
 * snapshot as an [`Arc`](std::sync::Arc). The index builds a new snapshot
 * whenever its fields or those names change instead of modifying the shared
 * one, so a running query keeps the schema it started with.
 */
typedef struct IndexSpecCache IndexSpecCache;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Releases `cache`; the cache is freed with its last handle. Does nothing if
 * `cache` is null.
 *
 * # Safety
 *
 * 1. `cache` must be null or a handle that has not been released.
 * 2. `cache` must not be used after this call.
 */
void IndexSpecCache_Decref(const struct IndexSpecCache *cache);

/**
 * Returns a new handle to the cache `cache` refers to.
 *
 * # Safety
 *
 * 1. `cache` must be a handle that has not been released.
 */
const struct IndexSpecCache *IndexSpecCache_Incref(const struct IndexSpecCache *cache);

/**
 * Builds a cache from the schema's fields and its rule's special field
 * names, and returns the first handle to it.
 *
 * # Safety
 *
 * 1. If `nfields` is non-zero, `fields` must be [valid] for reads of
 *    `nfields` consecutive, properly aligned `FieldSpec`s, none of which is
 *    mutated during the call.
 * 2. The `fieldName` and `fieldPath` of each of those fields must be
 *    [valid] `HiddenString`s whose buffers are readable for the length they
 *    report.
 * 3. `lang_field`, `score_field` and `payload_field` must each be null or a
 *    [valid] pointer to a NUL-terminated string.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 */
const struct IndexSpecCache *IndexSpecCache_New(const FieldSpec *fields, size_t nfields, const char *lang_field, const char *score_field, const char *payload_field);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
