#pragma once

/* Warning, this file is autogenerated by cbindgen from `src/redisearch_rs/c_entrypoint/index_error_ffi/build.rs. Don't modify it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "redismodule.h"
// Required to ensure that the alignment declared by cbindgen is respected on
// the C/C++ side.
#define ALIGNED(n) __attribute__((aligned(n)))

// Forward declaration for RedisModuleString from redismodule.h
typedef struct RedisModuleString RedisModuleString;

// timespec from C standard library
#include <time.h>


/**
 * A type with size `N`.
 */
typedef uint8_t Size_72[72];

/**
 * An opaque index error which can be passed by value to C.
 *
 * The size and alignment of this struct must match the Rust `IndexError`
 * structure exactly.
 */
typedef struct ALIGNED(8) IndexError {
  Size_72 _0;
} IndexError;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the IndexError module globals.
 * This should be called once during module initialization.
 *
 * # Safety
 * - `ctx` must be a valid RedisModuleCtx pointer
 */
void IndexError_GlobalInit(RedisModuleCtx *ctx);

/**
 * Returns the default [`IndexError`].
 */
struct IndexError IndexError_Default(void);

/**
 * Returns the number of errors in the IndexError.
 *
 * # Safety
 * - `error` must be a valid pointer to an OpaqueIndexError
 */
uintptr_t IndexError_ErrorCount(const struct IndexError *error);

/**
 * Returns the last error message in the IndexError.
 *
 * # Safety
 * - `error` must be a valid pointer to an OpaqueIndexError
 */
const char *IndexError_LastError(const struct IndexError *error);

/**
 * Returns the last error message in the IndexError, obfuscated.
 *
 * # Safety
 * - `error` must be a valid pointer to an OpaqueIndexError
 */
const char *IndexError_LastErrorObfuscated(const struct IndexError *error);

/**
 * Returns the time of the last error.
 *
 * # Safety
 * - `error` must be a valid pointer to an OpaqueIndexError
 */
timespec IndexError_LastErrorTime(const struct IndexError *error);

/**
 * Get the background_indexing_OOM_failure flag.
 *
 * # Safety
 * - `error` must be a valid pointer to an OpaqueIndexError
 */
bool IndexError_HasBackgroundIndexingOOMFailure(const struct IndexError *error);

/**
 * Change the background_indexing_OOM_failure flag to true.
 *
 * # Safety
 * - `error` must be a valid pointer to an OpaqueIndexError
 */
void IndexError_RaiseBackgroundIndexFailureFlag(struct IndexError *error);

/**
 * Initializes an IndexError. The error_count is set to 0 and the last_error is set to NA.
 * Mirrors C function: `IndexError IndexError_Init()`
 *
 * # Safety
 * - This function uses RSDummyContext internally, which must be initialized
 */
struct IndexError IndexError_Init(void);

/**
 * Adds an error message to the IndexError. The error_count is incremented and the last_error is set to the error_message.
 * Mirrors C function: `void IndexError_AddError(IndexError *error, ConstErrorMessage withoutUserData, ConstErrorMessage withUserData, RedisModuleString *key)`
 *
 * # Safety
 * - `ctx` must be a valid RedisModuleCtx pointer
 * - `error` must be a valid pointer to an OpaqueIndexError
 * - `without_user_data` and `with_user_data` must be valid C strings or null
 * - `key` must be a valid RedisModuleString pointer
 */
void IndexError_AddError(RedisModuleCtx *ctx,
                         struct IndexError *error,
                         const char *without_user_data,
                         const char *with_user_data,
                         RedisModuleString *key);

/**
 * Returns the key of the document that caused the error.
 * Mirrors C function: `RedisModuleString *IndexError_LastErrorKey(const IndexError *error)`
 *
 * # Safety
 * - `error` must be a valid pointer to an OpaqueIndexError
 * - Returns a held reference (incremented refcount) so the caller can always call FreeString
 */
RedisModuleString *IndexError_LastErrorKey(const struct IndexError *error);

/**
 * Clears an IndexError. If the last_error is not NA, it is freed.
 * Mirrors C function: `void IndexError_Clear(IndexError error)`
 *
 * # Safety
 * - `ctx` must be a valid RedisModuleCtx pointer
 */
void IndexError_Clear(RedisModuleCtx *ctx, struct IndexError error);

/**
 * Clears global variables used in the IndexError module.
 * This function should be called on shutdown.
 * Mirrors C function: `void IndexError_GlobalCleanup()`
 *
 * # Safety
 * - `ctx` must be a valid RedisModuleCtx pointer
 */
void IndexError_GlobalCleanup(RedisModuleCtx *ctx);

/**
 * Adds the error message of the other IndexError to the IndexError. The error_count is incremented and the last_error is set to the error_message.
 * This is used when merging errors from different shards in a cluster.
 * Mirrors C function: `void IndexError_Combine(IndexError *error, const IndexError *other)`
 *
 * # Safety
 * - `ctx` must be a valid RedisModuleCtx pointer
 * - `error` must be a valid pointer to an OpaqueIndexError
 * - `other` must be a valid pointer to an OpaqueIndexError
 */
void IndexError_Combine(RedisModuleCtx *ctx,
                        struct IndexError *error,
                        const struct IndexError *other);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
