#pragma once

/* Warning, this file is autogenerated by cbindgen from `src/redisearch_rs/c_entrypoint/low_memory_thin_vec_ffi/build.rs. Don't modify it manually. */

/**
 * The type used to represent the capacity of a `LowMemoryThinVec`.
 */
typedef uint16_t SizeType;

/**
 * The header of a LowMemoryThinVec.
 */
typedef struct Header {
  SizeType len;
  SizeType cap;
} Header;
