#pragma once

/* WARNING: this file was auto-generated by cheadergen from `c_entrypoint/module_init_ffi`. Do not edit it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "redismodule.h"

typedef struct RedisModuleCtx RedisModuleCtx;

typedef struct RedisModuleInfoCtx RedisModuleInfoCtx;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initializes a global subscriber that reports Rust `tracing` traces through `redismodule` logging.
 *
 * `level` is the initial redis `loglevel` config value the filter is set to.
 *
 * # Safety
 *
 * `level` must point to a valid, null-terminated C string.
 */
void TracingRedisModule_Init(struct RedisModuleCtx *ctx, const char *level);

/**
 * Updates the `tracing` log level filter from a redis `loglevel` config value
 * (one of `debug`, `verbose`, `notice`, `warning`).
 *
 * # Safety
 *
 * `level` must point to a valid, null-terminated C string.
 */
void TracingRedisModule_SetLogLevel(const char *level);

/**
 * Initialize RediSearch's panic hook, without replaacing the pre-existing panic hook (if any).
 *
 * Panic messages will be logged through `tracing` at the `ERROR` level.
 */
void RustPanicHook_Init(void);

/**
 * Add the current backtrace as a new section to the report printed
 * by RediSearch's INFO command.
 *
 * # Safety
 *
 * `ctx` must be a valid pointer to a `RedisModuleInfoCtx`.
 */
void AddToInfo_RustBacktrace(struct RedisModuleInfoCtx *ctx);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
