#pragma once

/* WARNING: this file was auto-generated by cheadergen from `c_entrypoint/row_block_ffi`. Do not edit it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "reply.h"
#include "rlookup.h"

/**
 * An opaque lookup which can be passed by value to C.
 *
 * The size and alignment of this struct must match the Rust `RLookup`
 * structure exactly.
 */
typedef struct RLookup RLookup;

/**
 * An opaque lookup row which can be passed by value to C.
 *
 * The size and alignment of this struct must match the Rust `RLookupRow`
 * structure exactly.
 */
typedef struct RLookupRow RLookupRow;

/**
 * Growable output buffer for building one block.
 *
 * Reused from chunk to chunk via [`RowBlockWriter::reset`], so the per-chunk allocation cost
 * is amortised to zero after the first.
 *
 * Every chunk starts with [`RowBlockWriter::write_schema`], which fixes the columns, and
 * then appends rows with [`RowBlockWriter::write_row`]. [`RowBlockWriter::as_bytes`] is the
 * finished block.
 *
 * Opaque to C: the writer owns a heap buffer, so C may only hold a pointer to one and pass
 * it back to the `row_block_ffi` entrypoints.
 */
typedef struct RowBlockWriter RowBlockWriter;

/**
 * Opens a block's header.
 */
#define ROW_BLOCK_MAGIC 1381188178

/**
 * Tag for a [`Tag::Array`] value.
 */
#define ROW_BLOCK_TAG_ARRAY 4

/**
 * Tag for a [`Tag::Map`] value.
 */
#define ROW_BLOCK_TAG_MAP 5

/**
 * Tag for a [`Tag::Null`] value.
 */
#define ROW_BLOCK_TAG_NULL 3

/**
 * Tag for a [`Tag::Number`] value.
 */
#define ROW_BLOCK_TAG_NUM 1

/**
 * Tag for a [`Tag::String`] value.
 */
#define ROW_BLOCK_TAG_STR 2

/**
 * The format version this build writes and reads.
 */
#define ROW_BLOCK_VERSION 2

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Borrows the block built so far, writing its length to `len`.
 *
 * The returned pointer stays valid until the next call that appends to or resets `w`.
 *
 * # Safety
 *
 * 1. Same contract as [`RowBlockWriter_Free`]'s `w`, except that the writer stays usable.
 * 2. `len` must be a non-null, writable pointer to a `size_t`.
 */
const char *RowBlockWriter_Bytes(const struct RowBlockWriter *w, size_t *len);

/**
 * Releases a writer and its buffer.
 *
 * # Safety
 *
 * 1. `w` must be a non-null pointer returned by [`RowBlockWriter_New`] and not freed since.
 */
void RowBlockWriter_Free(struct RowBlockWriter *w);

/**
 * Allocates a writer with no header written yet. Free it with [`RowBlockWriter_Free`].
 *
 * One writer is meant to serve every chunk of a request, and every request a thread handles:
 * [`RowBlockWriter_Reset`] keeps the buffer capacity that earlier chunks grew.
 */
struct RowBlockWriter *RowBlockWriter_New(void);

/**
 * Emits the rows appended so far as ordinary RESP rows, reporting whether it could.
 *
 * Returns `false`, having emitted nothing and leaving `nelem` untouched, when the block does
 * not decode. That cannot happen for a block this process just wrote, so it means the encoder
 * and decoder disagree; the caller's contract is to fail the query rather than reply rows it
 * cannot vouch for. The whole block is decoded before the first row is emitted precisely so
 * that failure is all-or-nothing: `RedisModule_Reply` writes through to the client with no way
 * to retract, so detecting the disagreement half way through would leave a partial reply that
 * can no longer be turned into an error.
 *
 * The encoder read backwards, for abandoning a block after rows have already gone into it:
 * those rows exist nowhere else - the pipeline row they came from is long released - and a
 * chunk's reply carries either a block or RESP rows, never both. Each row is emitted as the
 * same name/value map the RESP row serializer produces, so a chunk that falls back is
 * indistinguishable on the wire from one a shard with the format off would have sent.
 *
 * Only rows are replayed. The block never carried the per-row extras (id, score, sortkey)
 * that `serializeResult` can add, so a request that asks for those cannot use blocks in the
 * first place.
 *
 * # Safety
 *
 * 1. Same contract as [`RowBlockWriter_Bytes`]'s `w`.
 * 2. `reply` must be a non-null pointer to a [valid] `RedisModule_Reply` currently building
 *    an array, and must outlive this call.
 * 3. `nelem` must be a non-null, writable pointer to a `size_t`.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 */
bool RowBlockWriter_ReplayAsResp(const struct RowBlockWriter *w, RedisModule_Reply *reply, uint32_t req_flags, size_t *nelem);

/**
 * Discards the block, keeping the allocated capacity for the next chunk.
 *
 * # Safety
 *
 * 1. Same contract as [`RowBlockWriter_Free`]'s `w`, except that the writer stays usable.
 */
void RowBlockWriter_Reset(struct RowBlockWriter *w);

/**
 * Appends one row, reading values for the schema's columns out of `row`.
 *
 * Returns false when the row holds a value the format cannot represent, in which case
 * nothing is appended for it: the block still holds exactly the rows written before, so the
 * caller can emit it as is or discard it, but must not treat this row as encoded.
 *
 * `req_flags` (a `QEFlags` bit set) and `api_version` select how a row field stored as a trio
 * resolves; see [`TrioMember`].
 *
 * # Safety
 *
 * 1. Same contract as [`RowBlockWriter_Reset`]'s `w`, and a schema declaring at least one
 *    column must have been written since the writer was created or reset.
 * 2. `lk` must be a non-null pointer to a [valid] `RLookup` that outlives this call, and the
 *    same one the schema was written from.
 * 3. `row` must be a non-null pointer to a [valid] `RLookupRow` that outlives this call.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 */
bool RowBlockWriter_WriteRow(struct RowBlockWriter *w, const struct RLookup *lk, const struct RLookupRow *row, uint32_t req_flags, unsigned int api_version);

/**
 * Writes the header and the schema taken from `lk`'s visible keys, and returns how many
 * columns it declares.
 *
 * `required_flags` / `exclude_flags` are `RLookup_F` bit sets selecting the same key subset the
 * RESP serializer would emit; see [`ColumnFilter`].
 *
 * A zero return means this chunk cannot be encoded and the caller must reply in RESP
 * instead: either the schema has no columns, or it holds a name the format cannot carry.
 * Both leave the writer empty.
 *
 * # Safety
 *
 * 1. Same contract as [`RowBlockWriter_Reset`]'s `w`, and no schema may have been written
 *    since the writer was created or reset.
 * 2. `lk` must be a non-null pointer to a [valid] `RLookup` that outlives this call.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 */
uint16_t RowBlockWriter_WriteSchema(struct RowBlockWriter *w, const struct RLookup *lk, uint32_t required_flags, uint32_t exclude_flags);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
