#pragma once

/* WARNING: this file was auto-generated by cheadergen from `rqe_iterators`. Do not edit it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The different types of metrics.
 * At the moment, only vector distance is supported.
 */
typedef enum MetricType {
  VECTOR_DISTANCE,
} MetricType;

/**
 * Profile counters collected during query execution.
 *
 * This struct is `#[repr(C)]` so that C code can access its fields directly.
 */
typedef struct ProfileCounters {
  /**
   * Number of `read()` calls made.
   */
  size_t read;
  /**
   * Number of `skip_to()` calls made.
   */
  size_t skip_to;
  /**
   * Whether the iterator reached EOF.
   */
  bool eof;
} ProfileCounters;
