#pragma once

/* Warning, this file is autogenerated by cbindgen from `src/redisearch_rs/c_entrypoint/slots_tracker_ffi/build.rs. Don't modify it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "redismodule.h"
#ifdef __cplusplus
extern "C" {
#endif


/**
 * FFI struct representing an optional SlotsTracker version.
 * This is used to return version information from the `slots_tracker_check_availability` function.
 *
 * Expected use cases:
 * - `is_some == false`: No version (unavailable) - query should be rejected.
 * - `is_some == true`: Store the version number in `version`, to be compared with `slots_tracker_get_version` to detect changes.
 */
typedef struct OptionSlotTrackerVersion {
  bool is_some;
  uint32_t version;
} OptionSlotTrackerVersion;

/**
 * Sets the local slot ranges this shard is responsible for.
 *
 * This function updates the "local slots" set to match the provided ranges.
 * If the ranges differ from the current configuration:
 * - Updates "local slots" to the new ranges
 * - Removes any overlapping slots from "fully available slots" and "partially available slots"
 * - Increments the version counter
 *
 * If the ranges are identical to the current configuration, no changes are made.
 *
 * Returns the current version after the operation.
 *
 * # Safety
 *
 * This function must be called from the main thread only.
 * The `ranges` pointer must be valid and point to a properly initialized RedisModuleSlotRangeArray.
 * The ranges array must contain `num_ranges` valid elements.
 * All ranges must be sorted and have start <= end, with values in [0, 16383].
 */
uint32_t slots_tracker_set_local_slots(const RedisModuleSlotRangeArray *ranges);

/**
 * Marks the given slot ranges as partially available.
 *
 * This function updates the "partially available slots" set by adding the provided ranges.
 * It also removes the given slots from "local slots" and "fully available slots", and
 * increments the version counter.
 * DO NOT call this function directly, use `ASM API` in the C header instead.
 *
 * Returns the current version after the operation, used by `ASM API`
 * in the C header for atomic version management.
 *
 * # Safety
 *
 * This function must be called from the main thread only.
 * The `ranges` pointer must be valid and point to a properly initialized RedisModuleSlotRangeArray.
 * The ranges array must contain `num_ranges` valid elements.
 * All ranges must be sorted and have start <= end, with values in [0, 16383].
 */
uint32_t slots_tracker_mark_partially_available_slots(const RedisModuleSlotRangeArray *ranges);

/**
 * Promotes slot ranges to local ownership.
 *
 * This function adds the provided ranges to "local slots" and removes them from
 * "partially available slots". Does NOT modify "fully available slots" and does NOT
 * increment the version counter (the version was already bumped when slots became
 * partially available, and while partially available slots exist, `check_availability`
 * returns unstable/unavailable anyway).
 *
 * # Safety
 *
 * This function must be called from the main thread only.
 * The `ranges` pointer must be valid and point to a properly initialized RedisModuleSlotRangeArray.
 * The ranges array must contain `num_ranges` valid elements.
 * All ranges must be sorted and have start <= end, with values in [0, 16383].
 */
void slots_tracker_promote_to_local_slots(const RedisModuleSlotRangeArray *ranges);

/**
 * Marks the given slot ranges as fully available non-owned.
 *
 * This function updates the "fully available slots" set by adding the provided ranges.
 * It also removes the given slots from "local slots".
 *
 * Note: This does NOT increment the version counter (slots availability is unchanged).
 * It also does NOT remove from "partially available slots".
 *
 * # Safety
 *
 * This function must be called from the main thread only.
 * The `ranges` pointer must be valid and point to a properly initialized RedisModuleSlotRangeArray.
 * The ranges array must contain `num_ranges` valid elements.
 * All ranges must be sorted and have start <= end, with values in [0, 16383].
 */
void slots_tracker_mark_fully_available_slots(const RedisModuleSlotRangeArray *ranges);

/**
 * Removes deleted slot ranges from the partially available slots.
 *
 * This function removes the given slot ranges from "partially available slots" only.
 * It does NOT modify "local slots" or "fully available slots", and does NOT increment the version.
 *
 * # Safety
 *
 * This function must be called from the main thread only.
 * The `ranges` pointer must be valid and point to a properly initialized RedisModuleSlotRangeArray.
 * The ranges array must contain `num_ranges` valid elements.
 * All ranges must be sorted and have start <= end, with values in [0, 16383].
 */
void slots_tracker_remove_deleted_slots(const RedisModuleSlotRangeArray *ranges);

/**
 * Checks if there is any overlap between the given slot ranges and the fully available slots.
 *
 * This function checks if any of the provided slot ranges overlap with "fully available slots".
 * Returns true if there is at least one overlapping slot, false otherwise.
 *
 * # Safety
 *
 * This function must be called from the main thread only.
 * The `ranges` pointer must be valid and point to a properly initialized RedisModuleSlotRangeArray.
 * The ranges array must contain `num_ranges` valid elements.
 * All ranges must be sorted and have start <= end, with values in [0, 16383].
 */
bool slots_tracker_has_fully_available_overlap(const RedisModuleSlotRangeArray *ranges);

/**
 * Checks if all requested slots are available and returns version information.
 *
 * Return values (via OptionSlotTrackerVersion):
 * - `is_some = false`: Required slots are not available. Query should be rejected.
 * - `is_some = true`: Slots available; Store the returned `version` and compare it (equality check) with the tracker's version.
 *
 * # Safety
 *
 * This function must be called from the main thread only.
 * The `ranges` pointer must be valid and point to a properly initialized RedisModuleSlotRangeArray.
 * The ranges array must contain `num_ranges` valid elements.
 * All ranges must be sorted and have start <= end, with values in [0, 16383].
 */
struct OptionSlotTrackerVersion slots_tracker_check_availability(const RedisModuleSlotRangeArray *ranges);

/**
 * Resets the tracker to its initial state.
 *
 * This function is intended for testing purposes only. It resets the tracker
 * to a clean state with no slots configured and version reset to initial.
 *
 * # Safety
 *
 * This function must be called from the main thread only.
 */
void slots_tracker_reset(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
