#pragma once

/* Warning, this file is autogenerated by cbindgen from `src/redisearch_rs/c_entrypoint/types_ffi/build.rs. Don't modify it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>



#define RS_SORTABLES_MAX 1024

#define RS_SORTABLE_NUM 1

#define RS_SORTABLE_STR 3

#define RS_SORTABLE_NIL 4

#define RS_SORTABLE_RSVAL 5

/**
 * A [`RSSortingVector`] is a vector of [`RSValue`] pointers.
 */
typedef struct RSSortingVector RSSortingVector;

/**
 * A new-type for RSValue that ensures that the reference count is managed correctly.
 */
typedef struct RSValue RSValue;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Gets a RSValue from the sorting vector at the given index.
 *
 * Safety:
 * 1. The pointer must be a valid pointer to an [`RSSortingVector`] created by [`NewSortingVector`].
 */
struct RSValue *RSSortingVector_Get(const struct RSSortingVector *vec, size_t idx);

/**
 * Returns the length of the sorting vector.
 *
 * Safety:
 * 1. The pointer must be a valid pointer to an [`RSSortingVector`] created by [`NewSortingVector`] or null.
 */
size_t RSSortingVector_Length(const struct RSSortingVector *vec);

/**
 * Returns the memory size of the sorting vector.
 *
 * Safety:
 * 1. The pointer must be a valid pointer to an [`RSSortingVector`] created by [`NewSortingVector`].
 */
size_t RSSortingVector_GetMemorySize(struct RSSortingVector *vector);

/**
 * Puts a number (double) at the given index in the sorting vector.
 *
 * Safety:
 * 1. The pointer must be a valid pointer to an [`RSSortingVector`] created by [`NewSortingVector`].
 * 2. The `idx` must be a valid index within the bounds of the sorting vector.
 */
void RSSortingVector_PutNum(struct RSSortingVector *vec, size_t idx, double num);

/**
 * Puts a string at the given index in the sorting vector.
 *
 * This function will normalize the string to lowercase and use utf normalization for sorting if `is_normalized` is true.
 *
 * Internally it uses `libc` functions to allocate and copy the string, ensuring that string allocation and deallocation
 * all happen on the C side for now.
 *
 * Safety:
 * 1. The pointer must be a valid pointer to an [`RSSortingVector`] created by [`NewSortingVector`].
 * 2. The `str` pointer must point to a valid C string (null-terminated).
 * 3. The `idx` must be a valid index within the bounds of the sorting vector.
 */
void RSSortingVector_PutStr(struct RSSortingVector *vec,
                            size_t idx,
                            const char *str,
                            bool is_normalized);

/**
 * Puts a value at the given index in the sorting vector.
 *
 * Safety:
 * 1. The pointer must be a valid pointer to an [`RSSortingVector`] created by [`NewSortingVector`].
 * 2. The `val` pointer must point to a valid `RSValue` instance.
 * 3. The `idx` must be a valid index within the bounds of the sorting vector.
 */
void RSSortingVector_PutRSVal(struct RSSortingVector *vec, size_t idx, struct RSValue *val);

struct RSSortingVector *NewSortingVector(size_t len);

/**
 * Reduces the refcount of every value and frees the memory allocated for an `RSSortingVector`.
 * Called by the C code to deallocate the vector.
 *
 * Safety:
 * 1. The pointer must be a valid pointer to an [`RSSortingVector`] created by [`NewSortingVector`].
 * 2. The pointer must not have been freed before this call to avoid double free.
 */
void SortingVector_Free(struct RSSortingVector *vector);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
