#pragma once

/* WARNING: this file was auto-generated by cheadergen from `c_entrypoint/ttl_table_ffi`. Do not edit it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "_ttl_table.h"
#include "field.h"

/**
 * Borrowed view of a contiguous run of [`FieldExpiration`] entries.
 *
 * The returned pointer aliases storage owned by the table — it is invalidated
 * by any subsequent `_Add` / `_Remove` / `_Destroy` for this table and must
 * not be freed by the caller. A miss is encoded as `ptr == NULL` and
 * `len == 0`.
 */
typedef struct FieldExpirationSlice {
  const FieldExpiration *ptr;
  size_t len;
} FieldExpirationSlice;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Lazy-initialize a [`TimeToLiveTable`] at `*table`. No-op if `*table` is
 * already non-null. `max_size` is the fixed modulus for the slot formula
 * so it must be ≥ 1.
 *
 * # Panics
 * `max_size` must be ≥ 1, otherwise the function panics
 *
 * # Safety
 *  - `table` must be a valid, writable `*mut *mut TimeToLiveTable`.
 */
void TimeToLiveTable_VerifyInit(struct TimeToLiveTable * *table, size_t max_size);

/**
 * Destroy the [`TimeToLiveTable`] at `*table` and write `NULL` back to it.
 * No-op if `*table` is already null.
 *
 * # Safety
 *  - `table` must be a valid, writable `*mut *mut TimeToLiveTable`.
 *  - If `*table` is non-null, it must point to a value previously returned
 *    by [`TimeToLiveTable_VerifyInit`] and not yet destroyed.
 */
void TimeToLiveTable_Destroy(struct TimeToLiveTable * *table);

/**
 * Insert a document's per-field expirations. Ownership of `field_expirations`
 * transfers to the table; the caller must not touch its storage
 * afterwards.
 *
 * # Safety
 *  - `table` must point to a valid, initialized [`TimeToLiveTable`] (no
 *    other reference to it must exist for the duration of the call).
 *  - `field_expirations` must have been produced by [`FieldExpirations_Empty`]
 *    or [`FieldExpirations_WithCapacity`] and must be non-empty.
 *    Sortedness and uniqueness-by-`index` are carried by the type itself.
 *  - `doc_id` must not already be present in the table.
 */
void TimeToLiveTable_Add(struct TimeToLiveTable *table, t_docId doc_id, FieldExpirations field_expirations);

/**
 * Remove the entry for `doc_id`, if any. No-op if absent.
 *
 * # Safety
 *  - `table` must point to a valid, initialized [`TimeToLiveTable`] with
 *    no other live references.
 */
void TimeToLiveTable_Remove(struct TimeToLiveTable *table, t_docId doc_id);

/**
 * Returns whether the table holds no entries.
 *
 * # Safety
 *  - `table` must point to a valid, initialized [`TimeToLiveTable`].
 */
bool TimeToLiveTable_IsEmpty(const struct TimeToLiveTable *table);

/**
 * Borrow the per-field expiration list stored for `doc_id`.
 *
 * Returns a [`FieldExpirationSlice`] borrowing storage owned by the table.
 * On miss, both `ptr` and `len` are zero. The returned pointer is invalidated
 * by any subsequent `_Add` / `_Remove` / `_Destroy` for this table and must
 * not be freed by the caller.
 *
 * # Safety
 *  - `table` must point to a valid, initialized [`TimeToLiveTable`].
 */
struct FieldExpirationSlice TimeToLiveTable_GetFieldExpirations(const struct TimeToLiveTable *table, t_docId doc_id);

/**
 * Single-field expiration check.
 *
 * # Returns
 * `true` if the field's state satisfies `predicate` at `expiration_point`,
 * `false` otherwise. Specifically:
 * - With [`FieldExpirationPredicate::Default`], returns `true` iff the
 *   field is not expired (untracked fields and documents with no entry are
 *   treated as not expired).
 * - With [`FieldExpirationPredicate::Missing`], returns `true` iff the
 *   field is expired.
 *
 * Documents with no entry trivially satisfy any predicate and return `true`.
 *
 * # Safety
 *  - `table` must point to a valid, initialized [`TimeToLiveTable`].
 *  - `expiration_point` must be a valid `*const t_expirationTimePoint`.
 */
bool TimeToLiveTable_VerifyDocAndField(const struct TimeToLiveTable *table, t_docId doc_id, uint16_t field_index, enum FieldExpirationPredicate predicate, const t_expirationTimePoint *expiration_point);

/**
 * 32-bit field-mask expiration check.
 *
 * `ft_id_to_field_index` must point to at least
 * `highest_set_bit(field_mask) + 1` valid `u16` entries.
 * May be `NULL` when `field_mask == 0`.
 *
 * # Returns
 * `true` if the set of fields selected by `field_mask` satisfies
 * `predicate` at `expiration_point`:
 * - With [`FieldExpirationPredicate::Default`], returns `true` iff at
 *   least one selected field is not expired.
 * - With [`FieldExpirationPredicate::Missing`], returns `true` iff at
 *   least one selected field is expired.
 *
 * Documents with no entry trivially return `true` under either predicate.
 *
 * # Safety
 *  - `table` must point to a valid, initialized [`TimeToLiveTable`].
 *  - `expiration_point` must be a valid `*const t_expirationTimePoint`.
 *  - `ft_id_to_field_index` must satisfy the bound above.
 */
bool TimeToLiveTable_VerifyDocAndFieldMask(const struct TimeToLiveTable *table, t_docId doc_id, uint32_t field_mask, enum FieldExpirationPredicate predicate, const t_expirationTimePoint *expiration_point, const uint16_t *ft_id_to_field_index);

/**
 * Wide field-mask version of [`TimeToLiveTable_VerifyDocAndFieldMask`].
 *
 * # Returns
 * Same semantics as [`TimeToLiveTable_VerifyDocAndFieldMask`] — see that
 * function for the predicate / no-entry cases.
 *
 * # Safety
 * Same contract as [`TimeToLiveTable_VerifyDocAndFieldMask`].
 */
bool TimeToLiveTable_VerifyDocAndWideFieldMask(const struct TimeToLiveTable *table, t_docId doc_id, t_fieldMask field_mask, enum FieldExpirationPredicate predicate, const t_expirationTimePoint *expiration_point, const uint16_t *ft_id_to_field_index);

/**
 * Test-only: number of buckets currently allocated.
 *
 * Number of buckets currently allocated (lazy-growth high-water mark).
 * Returns 0 if `table` is `NULL`. Exposed for the C `test_cpp_expire`
 * lazy-growth tests.
 *
 * # Returns
 * The current bucket-array length, or `0` if `table` is `NULL`.
 *
 * # Safety
 *  - If non-null, `table` must point to a valid, initialized
 *    [`TimeToLiveTable`].
 */
size_t TimeToLiveTable_NAllocatedBuckets(const struct TimeToLiveTable *table);

/**
 * Construct an empty [`FieldExpirations`].
 *
 * No heap allocation is performed until the first insertion.
 */
FieldExpirations FieldExpirations_Empty(void);

/**
 * Construct a [`FieldExpirations`] with backing storage pre-sized for at
 * least `cap` entries.
 */
FieldExpirations FieldExpirations_WithCapacity(size_t cap);

/**
 * Append `fe` to the end of `*v` without searching for the insertion
 * point.
 *
 * Use when the caller already knows that `fe.index` is strictly greater
 * than every index currently in `*v` — typically when building the
 * list from an already-sorted source iterator.
 *
 * # Safety
 *  - `v` must be a non-null pointer to an initialized [`FieldExpirations`].
 *  - `fe.index` must be strictly greater than the `index` of every entry
 *    already present in `*v`.
 */
void FieldExpirations_Push(FieldExpirations *v, FieldExpiration fe);

/**
 * Number of [`FieldExpiration`] entries currently stored in `*v`.
 *
 * # Safety
 *  - `v` must be non-null.
 *  - `*v` must be either an initialized [`FieldExpirations`] (returned by a
 *    constructor in this module).
 */
size_t FieldExpirations_Len(const FieldExpirations *v);

/**
 * Borrow the contents of `*v` as a [`FieldExpirationSlice`].
 *
 * The returned pointer aliases storage owned by `*v`.
 *
 * # Safety
 *  - `v` must be non-null.
 *  - `*v` must be either an initialized [`FieldExpirations`] (returned by a
 *    constructor in this module).
 */
struct FieldExpirationSlice FieldExpirations_AsSlice(const FieldExpirations *v);

/**
 * Drop the [`FieldExpirations`] at `*v` and leave it in an empty,
 * reusable state.
 *
 * Use on the abandon path — when a `FieldExpirations` is built but
 * never handed to [`TimeToLiveTable_Add`]. Two such paths exist on the
 * C side today:
 * - `Document_Free` (`src/document_basic.c`) releasing a discarded
 *   document.
 * - `DocTable_UpdateExpiration` (`src/doc_table.c`) discarding an
 *   empty list rather than registering it.
 *
 * After this call `*v` is logically the same as a fresh
 * [`FieldExpirations_Empty`] result and is safe to reuse or to drop
 * again.
 *
 * # Safety
 *  - `v` must be non-null.
 *  - `*v` must be either an initialized [`FieldExpirations`] (returned by a
 *    constructor in this module).
 *  - No other reference to `*v` may exist for the duration of the call.
 */
void FieldExpirations_Free(FieldExpirations *v);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
