#pragma once

/* Warning, this file is autogenerated by cbindgen from `src/redisearch_rs/c_entrypoint/value_ffi/build.rs. Don't modify it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "redismodule.h"
// Required to ensure that the alignment declared by cbindgen is respected on
// the C/C++ side.
#define ALIGNED(n) __attribute__((aligned(n)))

// Required to ensure that the layout declared by cbindgen is respected on
// the C/C++ side
#define PACKED __attribute__((packed))


/**
 * An actual [`RsValue`] object
 */
typedef struct RsValue RsValue;

/**
 * A shared RedisSearch dynamic value, backed by an `Arc<RsValue>`.
 */
typedef struct SharedRsValue SharedRsValue;

/**
 * A single entry of a [`RsValueMap`].
 */
typedef struct RsValueMapEntry {
  struct SharedRsValue key;
  struct SharedRsValue value;
} RsValueMapEntry;

/**
 * An low-memory immutable structure that holds and manages a set of
 * T items.
 *
 * This collection's capacity is represented by an `u32` and the
 * collection itself is `#[repr(C, packed)]` so that it's size is just
 * 12 bytes.
 *
 * # Invariants
 * - (1) Can hold at most [`Self::MAX_CAPACITY`] items, which on 32-bit systems
 *   is less than `u32::MAX`. The reason for this is that when doing pointer
 *   addition, we must ensure we don't overflow `isize::MAX`.
 *   See [`NonNull::add`].
 */
typedef struct PACKED RsValueCollection_RsValueMapEntry {
  /**
   * Pointer to a heap-allocated array of `Self::cap` items.
   */
  struct RsValueMapEntry *entries;
  /**
   * The number of items this collection can hold
   */
  uint32_t cap;
} RsValueCollection_RsValueMapEntry;

typedef struct RsValueCollection_RsValueMapEntry RsValueMap;

/**
 * An low-memory immutable structure that holds and manages a set of
 * T items.
 *
 * This collection's capacity is represented by an `u32` and the
 * collection itself is `#[repr(C, packed)]` so that it's size is just
 * 12 bytes.
 *
 * # Invariants
 * - (1) Can hold at most [`Self::MAX_CAPACITY`] items, which on 32-bit systems
 *   is less than `u32::MAX`. The reason for this is that when doing pointer
 *   addition, we must ensure we don't overflow `isize::MAX`.
 *   See [`NonNull::add`].
 */
typedef struct PACKED RsValueCollection_SharedRsValue {
  /**
   * Pointer to a heap-allocated array of `Self::cap` items.
   */
  struct SharedRsValue *entries;
  /**
   * The number of items this collection can hold
   */
  uint32_t cap;
} RsValueCollection_SharedRsValue;

typedef struct RsValueCollection_SharedRsValue RsValueArray;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new, uninitialized [`RsValueMap`], reserving space for `cap`
 * entries. The map entries are uninitialized and must be set using [`RsValueMap_SetEntry`].
 *
 * # Safety
 * - (1) All items of the returned [`RsValueMap`] must be initialized using
 *   [`RsValueMap_SetEntry`] prior to using it.
 *
 * @param cap the number of entries (key and value) the map needs to store
 * @returns an uninitialized `RsValueMap` of `cap` capacity.
 */
RsValueMap RsValueMap_AllocUninit(uint32_t cap);

/**
 * Set a key-value pair at a specific index in the map.
 * Takes ownership of both the key and value RSValues.
 *
 * # Safety
 * - (1) `map` must be a valid pointer to an [`RsValueMap`] that
 *   has been created by [`RsValueMap_AllocUninit`] and
 *   that is valid for writes;
 * - (2) `i` must smaller than the capacity of the [`RsValueMap`],
 *   which cannot exceed [`u32::MAX`].
 * - (3) `key` and `value` must be valid pointers to [`RsValue`]
 *   obtained from [`SharedRsValue::into_raw`].
 *
 * @param map The map to modify
 * @param i The index where to set the entry (must be < map->len)
 * @param key The key RSValue (ownership is transferred to the map)
 * @param value The value RSValue (ownership is transferred to the map)
 */
void RsValueMap_SetEntry(RsValueMap *map,
                         size_t i,
                         const struct RsValue *key,
                         const struct RsValue *value);

/**
 * Allocates an uninitialized [`RsValueArray`].
 *
 * # Safety
 * See [`RsValueCollection::reserve_uninit`](value::collection::RsValueCollection::reserve_uninit)
 *
 * @param cap The desired capacity of the [`RsValueArray`]
 * @return An uninitialized `RsValueArray` of `cap` capacity
 */
RsValueArray RsValueArray_AllocUninit(uint32_t cap);

/**
 * Writes a value into the [`RsValueArray`] at `i`.
 *
 * # Safety
 * - (1) `arr` must be a non-null pointer to an [`RsValueArray`] originating from
 *   [`RsValueArray_AllocUninit`];
 * - (2) `arr` must be unique;
 * - (3) `i` must not exceed the [`RsValueArray`]'s capacity, which cannot
 *   exceed [`u32::MAX`].
 * - (4) `value` must be a valid pointer to [`RsValue`]
 *   obtained from [`SharedRsValue::into_raw`].
 *
 * @param arr The array to modify
 * @param i The index at which to write the value
 * @param value the value that is to be written
 */
void RsValueArray_SetEntry(RsValueArray *arr, size_t i, const struct RsValue *value);

/**
 * Creates a heap-allocated `RsValue` wrapping a string.
 * Doesn't duplicate the string. Use strdup if the value needs to be detached.
 *
 * # Safety
 * - (1) `str` must not be NULL;
 * - (2) `len` must match the length of `str`;
 * - (3) `str` must point to a valid, C string with a length of at most `u32::MAX` bytes;
 * - (4) `str` must not be aliased.
 * - (5) `str` must point to a location allocated using `rm_alloc`
 * - (6) `RedisModule_Alloc` must not be mutated for the lifetime of the
 *   `OpaqueRsValue`.
 *
 * @param str The string to wrap (ownership is transferred)
 * @param len The length of the string
 * @return A pointer to a heap-allocated RsValue
 */
const struct RsValue *SharedRsValue_NewString(char *str, uint32_t len);

/**
 * Creates a heap-allocated `SharedRsValue` wrapping a const string.
 *
 * # Safety
 * - (1) `str` must live as least as long as the returned [`SharedRsValue`].
 * - (2) `str` must point to a byte sequence that is valid for reads of `len` bytes.
 *
 * @param str The null-terminated string to wrap (ownership is transferred)
 * @return A pointer to a heap-allocated RsValue wrapping a constant C string
 */
const struct RsValue *SharedRsValue_NewConstString(const char *str, uint32_t len);

/**
 * Creates a heap-allocated `RsValue` wrapping a RedisModuleString.
 * Does not increment the refcount of the Redis string.
 * The passed Redis string's refcount does not get decremented
 * upon freeing the returned RsValue.
 *
 * # Safety
 * - (1) The passed pointer must be non-null and valid for reads.
 * - (2) The reference count of the [`RedisModuleString`] `str` points to
 *   must be at least 1 for the lifetime of the created [`SharedRsValue`]
 *
 * @param str The RedisModuleString to wrap
 * @return A pointer to a heap-allocated RsValue
 */
const struct RsValue *SharedRsValue_NewBorrowedRedisString(RedisModuleString *str);

/**
 * Creates a heap-allocated `RsValue` which increments and owns a reference to the Redis string.
 * The RsValue will decrement the refcount when freed.
 *
 * # Safety
 * - (1) `str` must be non-null
 * - (2) `str` must point to a valid [`RedisModuleString`]
 *   with a reference count of at least 1.
 *
 * @param str The RedisModuleString to wrap (refcount is incremented)
 * @return A pointer to a heap-allocated RsValue
 */
const struct RsValue *SharedRsValue_NewOwnedRedisString(RedisModuleString *str);

/**
 * Creates a heap-allocated `RsValue` which steals a reference to the Redis string.
 * The caller's reference is transferred to the RsValue.
 *
 * # Safety
 * - (1) `str` must be non-null
 * - (2) `str` must point to a valid [`RedisModuleString`]
 *   with a reference count of at least 1.
 *
 * @param s The RedisModuleString to wrap (ownership is transferred)
 * @return A pointer to a heap-allocated RsValue
 */
const struct RsValue *SharedRsValue_NewStolenRedisString(RedisModuleString *str);

/**
 * Creates a heap-allocated `RsValue` with a copied string.
 * The string is duplicated using `rm_malloc`.
 *
 * # Safety
 * - (1) `str` must be a valid pointer to a char sequence of `len` chars.
 *
 * @param s The string to copy
 * @param dst The length of the string to copy
 * @return A pointer to a heap-allocated `RsValue` owning the copied string
 */
const struct RsValue *SharedRsValue_NewCopiedString(const char *str, uint32_t len);

/**
 * Creates a heap-allocated `RsValue` by parsing a string as a number.
 * Returns an undefined value if the string cannot be parsed as a valid number.
 *
 * # Safety
 * - (1) `str` must be a valid const pointer to a char sequence of `len` bytes.
 *
 * @param p The string to parse
 * @param l The length of the string
 * @return A pointer to a heap-allocated `RsValue`
 */
const struct RsValue *SharedRsValue_NewParsedNumber(const char *str, uintptr_t len);

/**
 * Creates a heap-allocated `RsValue` containing a number.
 *
 * @param n The numeric value to wrap
 * @return A pointer to a heap-allocated `RsValue` of type `RsValueType_Number`
 */
const struct RsValue *SharedRsValue_NewNumber(double n);

/**
 * Creates a heap-allocated `RsValue` containing a number from an int64.
 * This operation casts the passed `i64` to an `f64`, possibly losing information.
 *
 * @param ii The int64 value to convert and wrap
 * @return A pointer to a heap-allocated `RsValue` of type `RsValueType_Number`
 */
const struct RsValue *SharedRsValue_NewNumberFromInt64(int64_t dd);

/**
 * Creates a heap-allocated `RsValue` array from existing values.
 * Takes ownership of the values (values will be freed when array is freed).
 *
 * @param vals The values array to use for the array (ownership is transferred)
 * @param len Number of values
 * @return A pointer to a heap-allocated `RsValue` of type `RsValueType_Array`
 */
const struct RsValue *SharedRsValue_NewArray(RsValueArray vals);

/**
 * Creates a heap-allocated RsValue of type RsValue_Map from an RsValueMap.
 * Takes ownership of the map structure and all its entries.
 *
 * @param map The RsValueMap to wrap (ownership is transferred)
 * @return A pointer to a heap-allocated RsValue of type RsValueType_Map
 */
const struct RsValue *SharedRsValue_NewMap(RsValueMap map);

/**
 * Creates a heap-allocated RsValue Trio from three RsValues.
 * Takes ownership of all three values.
 *
 * # Safety
 *
 * - (1) `left`, `middle`, and `right` must be valid pointers to [`RsValue`]
 *   obtained from [`SharedRsValue::into_raw`].
 *
 * @param left The left value (ownership is transferred)
 * @param middle The middle value (ownership is transferred)
 * @param right The right value (ownership is transferred)
 * @return A pointer to a heap-allocated RsValue of type RsValueType_Trio
 */
const struct RsValue *SharedRsValue_NewTrio(const struct RsValue *left,
                                            const struct RsValue *middle,
                                            const struct RsValue *right);

/**
 * Gets the `f64` wrapped by the `SharedRsValue`
 *
 * # Safety
 * - (1) `v` must be a valid pointer to [`RsValue`] obtained from [`SharedRsValue::into_raw`].
 * - (2) `v` must be a number value.
 */
double SharedRsValue_Number_Get(const struct RsValue *v);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
