#ifndef value_h
#define value_h

/* Warning, this file is autogenerated by cbindgen from `src/redisearch_rs/c_entrypoint/value_ffi/build.rs. Don't modify it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "redismodule.h"
#include "query_error.h"

#define RSValueSize 16

/**
 * Enumeration of the types an [`RsValue`] can be of.
 *
 */
typedef enum RSValueType {
  RSValueType_Undef = 0,
  RSValueType_Number = 1,
  RSValueType_String = 2,
  RSValueType_Null = 3,
  RSValueType_RedisString = 4,
  RSValueType_Array = 5,
  RSValueType_Reference = 6,
  RSValueType_Trio = 7,
  RSValueType_Map = 8,
} RSValueType;

/**
 * Opaque map structure used during map construction.
 * Holds uninitialized entries that are populated via [`RSValue_MapBuilderSetEntry`]
 * before being finalized into an [`RsValue::Map`] via [`RSValue_NewMapFromBuilder`].
 */
typedef struct RSValueMapBuilder RSValueMapBuilder;

/**
 * An actual [`RsValue`] object
 */
typedef struct RSValue RSValue;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Allocates an array of null pointers with space for `len` [`RsValue`] pointers.
 *
 * The returned buffer must be populated and then passed to [`RSValue_NewArrayFromBuilder`]
 * to produce an array value.
 *
 * # Safety
 *
 * 1. The caller must eventually pass the returned pointer to [`RSValue_NewArrayFromBuilder`].
 */
struct RSValue **RSValue_NewArrayBuilder(uint32_t len);

/**
 * Creates a heap-allocated array [`RsValue`] from existing values.
 *
 * Takes ownership of the `values` buffer and all [`RsValue`] pointers within it.
 * The values will be freed when the array is freed.
 *
 * # Safety
 *
 * 1. `values` must have been allocated via [`RSValue_NewArrayBuilder`] with
 *    a capacity equal to `len`.
 * 2. All `len` entries in `values` must have been filled with valid [`RsValue`] pointers.
 */
struct RSValue *RSValue_NewArrayFromBuilder(struct RSValue **values, uint32_t len);

/**
 * Returns the number of elements in an array [`RsValue`].
 *
 * If `value` is not an array, returns `0`.
 *
 * # Safety
 *
 * 1. `value` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 */
uint32_t RSValue_ArrayLen(const struct RSValue *value);

/**
 * Returns a pointer to the element at `index` in an array [`RsValue`].
 *
 * If `value` is not an array, returns a null pointer. The returned pointer
 * is borrowed from the array and must not be freed by the caller.
 *
 * # Safety
 *
 * 1. `value` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 *
 * # Panics
 *
 * Panics if `index` greater than or equal to the array length.
 */
struct RSValue *RSValue_ArrayItem(const struct RSValue *value, uint32_t index);

int RSValue_Cmp(const struct RSValue *v1, const struct RSValue *v2, QueryError *status);

int RSValue_Equal(const struct RSValue *v1, const struct RSValue *v2, QueryError *_status);

int RSValue_BoolTest(const struct RSValue *value);

/**
 * Creates and returns a new **owned** [`RsValue`] object of type undefined.
 *
 * The caller must make sure to pass the returned [`RsValue`] to one of the
 * ownership taking `RSValue_` functions, directly or indirectly.
 */
struct RSValue *RSValue_NewUndefined(void);

/**
 * Creates and returns a new **owned** [`RsValue`] object of type null.
 *
 * The caller must make sure to pass the returned [`RsValue`] to one of the
 * ownership taking `RSValue_` functions, directly or indirectly.
 */
struct RSValue *RSValue_NewNull(void);

/**
 * Creates and returns a new **owned** [`RsValue`] object of type number
 * containing the given numeric value.
 *
 * The caller must make sure to pass the returned [`RsValue`] to one of the
 * ownership taking `RSValue_` functions, directly or indirectly.
 */
struct RSValue *RSValue_NewNumber(double value);

/**
 * Creates and returns a new **owned** [`RsValue`] object of type trio from three [`RsValue`]s.
 *
 * Takes ownership of all three arguments.
 *
 * The caller must make sure to pass the returned [`RsValue`] to one of the
 * ownership taking `RSValue_` functions, directly or indirectly.
 *
 * # Safety
 *
 * 1. All three arguments must point to a valid **owned** [`RsValue`] obtained from an
 *    `RSValue_*` function returning an owned [`RsValue`] object.
 */
struct RSValue *RSValue_NewTrio(struct RSValue *left,
                                struct RSValue *middle,
                                struct RSValue *right);

/**
 * Creates and returns a new **owned** [`RsValue`] object of type string,
 * taking ownership of the given `RedisModule_Alloc`-allocated buffer.
 *
 * The caller must make sure to pass the returned [`RsValue`] to one of the
 * ownership taking `RSValue_` functions, directly or indirectly.
 *
 * # Safety
 *
 * 1. `str` must be a [valid], non-null pointer to a buffer allocated by `RedisModule_Alloc`.
 * 2. `str` must be [valid] for reads of `len` bytes.
 * 3. `str` **must not** be used or freed after this function is called, as this function
 *    takes ownership of the allocation.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 */
struct RSValue *RSValue_NullStatic(void);

struct RSValue *RSValue_NewReference(const struct RSValue *src);

struct RSValue *RSValue_NewString(char *str, uint32_t len);

/**
 * Creates and returns a new **owned** [`RsValue`] object of type string,
 * taking ownership of the given `RedisModule_Alloc`-allocated buffer.
 *
 * The caller must make sure to pass the returned [`RsValue`] to one of the
 * ownership taking `RSValue_` methods, directly or indirectly.
 *
 * # Safety
 *
 * 1. `str` must be a [valid], non-null pointer to a buffer allocated by `RedisModule_Alloc`.
 * 2. `str` must be [valid] for reads of `len` bytes.
 * 3. `str` **must not** be used or freed after this function is called, as this function
 *    takes ownership of the allocation.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 */
struct RSValue *RSValue_NewStringWithoutNulTerminator(char *str, uint32_t len);

/**
 * Creates and returns a new **owned** [`RsValue`] object of type string,
 * borrowing the given string buffer without taking ownership.
 *
 * The caller must make sure to pass the returned [`RsValue`] to one of the
 * ownership taking `RSValue_` functions, directly or indirectly.
 *
 * # Safety
 *
 * 1. `str` must be a [valid], non-null pointer to a string buffer.
 * 2. `str` must be [valid] for reads of `len` bytes.
 * 3. The memory pointed to by `str` must remain valid and not be mutated for the entire
 *    lifetime of the returned [`RsValue`] and any clones of it.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 */
struct RSValue *RSValue_NewBorrowedString(const char *str, uint32_t len);

/**
 * Creates and returns a new **owned** [`RsValue`] object of type string,
 * taking ownership of the given [`RedisModuleString`].
 *
 * The caller must make sure to pass the returned [`RsValue`] to one of the
 * ownership taking `RSValue_` functions, directly or indirectly.
 *
 * # Safety
 *
 * 1. `str` must be a [valid], non-null pointer to a [`RedisModuleString`].
 * 2. `str` **must not** be used or freed after this function is called, as this function
 *    takes ownership of the string.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 */
struct RSValue *RSValue_NewRedisString(RedisModuleString *str);

/**
 * Creates and returns a new **owned** [`RsValue`] object of type string,
 * copying `len` bytes from the given string buffer into a new Rust-allocated [`Box<CStr>`].
 *
 * The caller retains ownership of `str`.
 *
 * The caller must make sure to pass the returned [`RsValue`] to one of the
 * ownership taking `RSValue_` functions, directly or indirectly.
 *
 * # Safety
 *
 * 1. `str` must be a [valid], non-null pointer to a string buffer.
 * 2. `str` must be [valid] for reads of `len` bytes.
 * 3. The `len` bytes pointed to by `str` must not contain any null bytes.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 */
struct RSValue *RSValue_NewCopiedString(const char *str, uint32_t len);

struct RSValue *RSValue_NewParsedNumber(const char *value, uint32_t len);

struct RSValue *RSValue_NewNumberFromInt64(int64_t number);

int RSValue_ToNumber(const struct RSValue *value, double *d);

const char *RSValue_ConvertStringPtrLen(const struct RSValue *value,
                                        size_t *len_ptr,
                                        char *buf,
                                        size_t buflen);

void RSValue_ToString(const struct RSValue *dst, const struct RSValue *value);

size_t RSValue_NumToString(const struct RSValue *value, char *buf, size_t buflen);

/**
 * Gets the numeric value from an [`RsValue`].
 *
 * # Safety
 *
 * 1. `value` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 *
 * # Panic
 *
 * Panics if the value is not a number type.
 */
double RSValue_Number_Get(const struct RSValue *value);

/**
 * Borrows an immutable reference to the left value of a trio.
 *
 * # Safety
 *
 * 1. `value` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 *
 * # Panic
 *
 * Panics if the value is not a trio type.
 */
const struct RSValue *RSValue_Trio_GetLeft(const struct RSValue *value);

/**
 * Borrows an immutable reference to the middle value of a trio.
 *
 * # Safety
 *
 * 1. `value` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 *
 * # Panic
 *
 * Panics if the value is not a trio type.
 */
const struct RSValue *RSValue_Trio_GetMiddle(const struct RSValue *value);

/**
 * Borrows an immutable reference to the right value of a trio.
 *
 * # Safety
 *
 * 1. `value` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 *
 * # Panic
 *
 * Panics if the value is not a trio type.
 */
const struct RSValue *RSValue_Trio_GetRight(const struct RSValue *value);

/**
 * Returns a pointer to the string data of an [`RsValue`] and optionally writes the string
 * length to `lenp`, if `lenp` is a non-null pointer.
 *
 * The returned pointer borrows from the [`RsValue`] and must not outlive it.
 *
 * # Safety
 *
 * 1. `value` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 * 2. `lenp` must be either null or a [valid], non-null pointer to a `u32`.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 *
 * # Panic
 *
 * Panics if the value is not a `String` type.
 * Panics (in debug mode) if the string data might not be nul-terminated.
 */
const char *RSValue_String_Get(const struct RSValue *value, uint32_t *lenp);

/**
 * Returns a pointer to the string data of an [`RsValue`] and optionally writes the string
 * length to `lenp`.
 *
 * The returned pointer borrows from the [`RsValue`] and must not outlive it.
 *
 * # Safety
 *
 * 1. `value` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 * 2. `lenp` must be either null or a [valid], non-null pointer to a `u32`.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 *
 * # Panic
 *
 * Panics if the value is not a `String` type.
 */
char *RSValue_String_GetTrusted(const struct RSValue *value, uint32_t *lenp);

/**
 * Returns a read only reference to the underlying [`RedisModuleString`] of an [`RsValue`].
 *
 * The returned reference borrows from the [`RsValue`] and must not outlive it.
 *
 * # Safety
 *
 * 1. `value` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 *
 * # Panic
 *
 * Panics if the value is not a `RedisString` type.
 */
const RedisModuleString *RSValue_RedisString_Get(const struct RSValue *value);

/**
 * Returns a pointer to the string data of an [`RsValue`] and optionally writes the string
 * length to `len_ptr`.
 *
 * Unlike [`RSValue_String_Get`], this function handles all string variants (including
 * `RedisString`) and automatically dereferences `Ref` values and follows through the left
 * element of `Trio` values. Returns null for non-string variants.
 *
 * The returned pointer borrows from the [`RsValue`] and must not outlive it.
 *
 * # Safety
 *
 * 1. `value` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 * 2. `len_ptr` must be either null or a [valid], non-null pointer to a `size_t`.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 */
const char *RSValue_StringPtrLen(const struct RSValue *value, size_t *len_ptr);

uint64_t RSValue_Hash(const struct RSValue *value, uint64_t hval);

/**
 * Allocates a new, uninitialized [`RSValueMapBuilder`] with space for `len` entries.
 *
 * The map entries are uninitialized and must be set using [`RSValue_MapBuilderSetEntry`]
 * before being finalized into an [`RsValue`] via [`RSValue_NewMapFromBuilder`].
 *
 * # Safety
 *
 * 1. All entries must be initialized via [`RSValue_MapBuilderSetEntry`] before
 *    passing the map to [`RSValue_NewMapFromBuilder`].
 */
struct RSValueMapBuilder *RSValue_NewMapBuilder(uint32_t len);

/**
 * Sets a key-value pair at a specific index in the map.
 *
 * Takes ownership of both the `key` and `value` [`RsValue`] pointers.
 *
 * # Safety
 *
 * 1. `map` must be a valid pointer to an [`RSValueMapBuilder`] created by
 *    [`RSValue_NewMapBuilder`].
 * 2. `key` and `value` must be valid pointers to [`RsValue`]
 *
 * # Panics
 *
 * Panics if `index` is greater than or equal to the map length.
 */
void RSValue_MapBuilderSetEntry(struct RSValueMapBuilder *map,
                                size_t index,
                                struct RSValue *key,
                                struct RSValue *value);

/**
 * Creates a heap-allocated map [`RsValue`] from an [`RSValueMapBuilder`].
 *
 * Takes ownership of the map structure and all its entries. The [`RSValueMapBuilder`]
 * pointer is consumed and must not be used after this call.
 *
 * # Safety
 *
 * 1. `map` must be a valid pointer to an [`RSValueMapBuilder`] created by
 *    [`RSValue_NewMapBuilder`].
 * 2. All entries in the map must have been initialized via [`RSValue_MapBuilderSetEntry`].
 */
struct RSValue *RSValue_NewMapFromBuilder(struct RSValueMapBuilder *map);

/**
 * Returns the number of key-value pairs in a map [`RsValue`].
 *
 * # Safety
 *
 * 1. `map` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 *
 * # Panics
 *
 * Panics if `map` is not a map value.
 */
uint32_t RSValue_Map_Len(const struct RSValue *map);

/**
 * Retrieves a key-value pair from a map [`RsValue`] at a specific index.
 *
 * The returned key and value pointers are borrowed from the map and must
 * not be freed by the caller.
 *
 * # Safety
 *
 * 1. `map` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 * 2. `key` and `value` must be valid, non-null pointers to writable
 *    `*mut RsValue` locations.
 *
 * # Panics
 *
 * - Panics if `map` is not a map value.
 * - Panics if `index` is greater or equal to the map length.
 */
void RSValue_Map_GetEntry(const struct RSValue *map,
                          uint32_t index,
                          struct RSValue **key,
                          struct RSValue **value);

sds RSValue_DumpSds(const struct RSValue *value, sds sds, bool obfuscate);

/**
 * Converts an [`RsValue`] to a number type in-place.
 *
 * This clears the existing value and sets it to Number with the given value.
 *
 * # Safety
 *
 * 1. `value` must point to a valid **owned** [`RsValue`] obtained from an
 *    `RSValue_*` function returning an owned [`RsValue`] object.
 * 2. Only 1 reference is allowed to exist pointing to this [`RsValue`] object.
 *
 * # Panic
 *
 * Panics if more than 1 reference exists to this [`RsValue`] object.
 */
void RSValue_SetNumber(struct RSValue *value, double n);

/**
 * Converts an [`RsValue`] to null type in-place.
 *
 * This clears the existing value and sets it to Null.
 *
 * # Safety
 *
 * 1. `value` must point to a valid **owned** [`RsValue`] obtained from an
 *    `RSValue_*` function returning an owned [`RsValue`] object.
 * 2. Only 1 reference is allowed to exist pointing to this [`RsValue`] object.
 *
 * # Panic
 *
 * Panics if more than 1 reference exists to this [`RsValue`] object.
 */
void RSValue_SetNull(struct RSValue *value);

/**
 * Converts an [`RsValue`] to a string type in-place, taking ownership of the given
 * `RedisModule_Alloc`-allocated buffer.
 *
 * This clears the existing value and sets it to an [`RsString`] of kind `RmAlloc`
 * with the given buffer.
 *
 * # Safety
 *
 * 1. `value` must point to a valid **owned** [`RsValue`] obtained from an
 *    `RSValue_*` function returning an owned [`RsValue`] object.
 * 2. `str` must be a [valid], non-null pointer to a buffer allocated by `RedisModule_Alloc`.
 * 3. `str` must be [valid] for reads of `len` bytes.
 * 4. `str` **must not** be used or freed after this function is called, as this function
 *    takes ownership of the allocation.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 *
 * # Panic
 *
 * Panics if more than 1 reference exists to this [`RsValue`] object.
 */
void RSValue_SetString(struct RSValue *value, char *str, uint32_t len);

/**
 * Converts an [`RsValue`] to a string type in-place, borrowing the given string buffer
 * without taking ownership.
 *
 * This clears the existing value and sets it to an [`RsString`] of kind `Const`
 * with the given buffer.
 *
 * # Safety
 *
 * 1. `value` must point to a valid **owned** [`RsValue`] obtained from an
 *    `RSValue_*` function returning an owned [`RsValue`] object.
 * 2. `str` must be a [valid], non-null pointer to a string buffer.
 * 3. `str` must be [valid] for reads of `len` bytes.
 * 4. The memory pointed to by `str` must remain valid and not be mutated for the entire
 *    lifetime of the [`RsValue`] and any clones of it.
 *
 * [valid]: https://doc.rust-lang.org/std/ptr/index.html#safety
 *
 * # Panic
 *
 * Panics if more than 1 reference exists to this [`RsValue`] object.
 */
void RSValue_SetConstString(struct RSValue *value, const char *str, uint32_t len);

/**
 * Decrement the reference count of the provided [`RsValue`] object. If this was
 * the last available reference, it frees the data.
 *
 * # Safety
 *
 * 1. `value` must point to a valid **owned** [`RsValue`] obtained from an
 *    `RSValue_*` function returning an owned [`RsValue`] object.
 */
void RSValue_DecrRef(const struct RSValue *value);

struct RSValue *RSValue_Dereference(const struct RSValue *value);

void RSValue_Clear(const struct RSValue *value);

struct RSValue *RSValue_IncrRef(const struct RSValue *value);

void RSValue_MakeReference(const struct RSValue *dst, const struct RSValue *src);

void RSValue_MakeOwnReference(const struct RSValue *dst, const struct RSValue *src);

void RSValue_Replace(struct RSValue **dstpp, const struct RSValue *src);

uint16_t RSValue_Refcount(const struct RSValue *value);

/**
 * Returns the type of the given [`RsValue`].
 *
 * # Safety
 *
 * 1. `value` must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 */
enum RSValueType RSValue_Type(const struct RSValue *value);

/**
 * Returns whether the given [`RsValue`] is a reference type, or `false` if `value` is NULL.
 *
 * # Safety
 *
 * 1. If `value` is non-null, it must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 */
bool RSValue_IsReference(const struct RSValue *value);

/**
 * Returns whether the given [`RsValue`] is a number type, or `false` if `value` is NULL.
 *
 * # Safety
 *
 * 1. If `value` is non-null, it must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 */
bool RSValue_IsNumber(const struct RSValue *value);

/**
 * Returns whether the given [`RsValue`] is a string type (any string variant), or `false` if `value` is NULL.
 *
 * # Safety
 *
 * 1. If `value` is non-null, it must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 */
bool RSValue_IsString(const struct RSValue *value);

/**
 * Returns whether the given [`RsValue`] is an array type, or `false` if `value` is NULL.
 *
 * # Safety
 *
 * 1. If `value` is non-null, it must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 */
bool RSValue_IsArray(const struct RSValue *value);

/**
 * Returns whether the given [`RsValue`] is a trio type, or `false` if `value` is NULL.
 *
 * # Safety
 *
 * 1. If `value` is non-null, it must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 */
bool RSValue_IsTrio(const struct RSValue *value);

/**
 * Returns whether the given [`RsValue`] is a null pointer, a null type, or a reference to a null type.
 *
 * # Safety
 *
 * 1. If `value` is non-null, it must point to a valid [`RsValue`] obtained from an `RSValue_*` function.
 */
bool RSValue_IsNull(const struct RSValue *value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* value_h */
