[package]
name = "value"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
c_ffi_utils = { workspace = true }
cheadergen.workspace = true
ffi.workspace = true
libc.workspace = true
query_error.workspace = true
nul_terminated_bytes.workspace = true
redis-module.workspace = true
workspace_hack.workspace = true
thiserror.workspace = true
tracing.workspace = true
triomphe.workspace = true
tracing_assert.workspace = true

[dev-dependencies]
redisearch_rs = { workspace = true, features = ["mock_allocator"] }
redis_mock.workspace = true

[lints]
workspace = true
