
/* #line 1 "lexer.rl" */
/*
 * Copyright Redis Ltd. 2016 - present
 * Licensed under your choice of the Redis Source Available License 2.0 (RSALv2) or
 * the Server Side Public License v1 (SSPLv1).
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>

#include "../parse.h"
#include "parser.h"
#include "../../query_node.h"
#include "../../stopwords.h"

/* forward declarations of stuff generated by lemon */

#define RSQuery_Parse_v3 RSQueryParser_v3_ // weird Lemon quirk.. oh well..
#define RSQuery_ParseAlloc_v3 RSQueryParser_v3_Alloc
#define RSQuery_ParseFree_v3 RSQueryParser_v3_Free

void RSQuery_Parse_v3(void *yyp, int yymajor, QueryToken yyminor, QueryParseCtx *ctx);
void *RSQuery_ParseAlloc_v3(void *(*mallocProc)(size_t));
void RSQuery_ParseFree_v3(void *p, void (*freeProc)(void *));


/* #line 752 "lexer.rl" */



/* #line 36 "lexer.c" */
static const char _query_actions[] = {
	0, 1, 0, 1, 1, 1, 2, 1, 
	20, 1, 21, 1, 22, 1, 23, 1, 
	24, 1, 25, 1, 26, 1, 27, 1, 
	28, 1, 29, 1, 30, 1, 31, 1, 
	32, 1, 33, 1, 34, 1, 35, 1, 
	36, 1, 37, 1, 38, 1, 39, 1, 
	40, 1, 41, 1, 42, 1, 43, 1, 
	44, 1, 45, 1, 46, 1, 47, 1, 
	48, 1, 49, 1, 50, 1, 51, 1, 
	52, 1, 53, 1, 54, 1, 55, 1, 
	56, 1, 57, 1, 58, 1, 59, 1, 
	60, 1, 61, 1, 62, 1, 63, 1, 
	64, 1, 65, 1, 66, 1, 67, 1, 
	68, 1, 69, 2, 2, 3, 2, 2, 
	4, 2, 2, 5, 2, 2, 6, 2, 
	2, 7, 2, 2, 8, 2, 2, 9, 
	2, 2, 10, 2, 2, 11, 2, 2, 
	12, 2, 2, 13, 2, 2, 14, 2, 
	2, 15, 2, 2, 16, 2, 2, 17, 
	2, 2, 18, 2, 2, 19
};

static const short _query_key_offsets[] = {
	0, 10, 20, 22, 22, 32, 42, 45, 
	47, 51, 53, 55, 59, 61, 63, 65, 
	66, 67, 69, 71, 72, 72, 77, 81, 
	82, 86, 90, 94, 95, 99, 104, 109, 
	113, 117, 122, 127, 129, 130, 130, 134, 
	138, 143, 148, 153, 155, 156, 156, 160, 
	163, 167, 177, 179, 181, 181, 226, 237, 
	238, 248, 259, 261, 277, 288, 293, 296, 
	302, 318, 331, 336, 341, 344, 350, 352, 
	368, 383, 396, 398, 400, 402, 403, 405, 
	406, 416, 429, 444, 457, 470, 483, 496, 
	509, 522, 532
};

static const char _query_trans_keys[] = {
	9, 13, 32, 47, 58, 64, 91, 96, 
	123, 126, 9, 13, 32, 47, 58, 64, 
	91, 96, 123, 126, 39, 92, 9, 13, 
	32, 47, 58, 64, 91, 96, 123, 126, 
	92, 96, 0, 47, 58, 64, 91, 94, 
	123, 127, 46, 48, 57, 48, 57, 43, 
	45, 48, 57, 48, 57, 48, 57, 43, 
	45, 48, 57, 48, 57, 78, 110, 70, 
	102, 119, 39, 39, 92, 39, 92, 41, 
	36, 42, 92, 119, 125, 36, 42, 92, 
	125, 125, 36, 42, 92, 125, 36, 42, 
	92, 125, 36, 42, 92, 125, 125, 36, 
	42, 92, 125, 36, 42, 92, 119, 125, 
	36, 39, 42, 92, 125, 36, 42, 92, 
	125, 36, 42, 92, 125, 36, 39, 42, 
	92, 125, 36, 39, 42, 92, 125, 39, 
	92, 125, 36, 42, 92, 125, 36, 42, 
	92, 125, 36, 39, 42, 92, 125, 36, 
	39, 42, 92, 125, 36, 39, 42, 92, 
	125, 39, 92, 125, 36, 42, 92, 125, 
	39, 92, 125, 36, 42, 92, 125, 9, 
	13, 32, 47, 58, 64, 91, 96, 123, 
	126, 39, 92, 39, 92, 32, 33, 34, 
	36, 37, 39, 40, 41, 42, 43, 45, 
	46, 58, 59, 60, 61, 62, 63, 64, 
	65, 73, 91, 92, 93, 95, 97, 105, 
	119, 123, 124, 125, 126, 127, 0, 8, 
	9, 13, 14, 31, 35, 47, 48, 57, 
	94, 96, 42, 92, 96, 0, 47, 58, 
	64, 91, 94, 123, 127, 61, 92, 96, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	42, 92, 96, 0, 47, 58, 64, 91, 
	94, 123, 127, 39, 92, 36, 43, 45, 
	46, 92, 96, 0, 47, 48, 57, 58, 
	64, 91, 94, 123, 127, 42, 92, 96, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	42, 69, 101, 48, 57, 42, 48, 57, 
	42, 46, 69, 101, 48, 57, 42, 46, 
	69, 92, 96, 101, 0, 47, 48, 57, 
	58, 64, 91, 94, 123, 127, 42, 43, 
	45, 92, 96, 0, 47, 58, 64, 91, 
	94, 123, 127, 46, 73, 105, 48, 57, 
	42, 69, 101, 48, 57, 42, 48, 57, 
	42, 46, 69, 101, 48, 57, 48, 57, 
	42, 46, 69, 92, 96, 101, 0, 47, 
	48, 57, 58, 64, 91, 94, 123, 127, 
	42, 43, 45, 92, 96, 0, 47, 48, 
	57, 58, 64, 91, 94, 123, 127, 42, 
	92, 96, 0, 47, 48, 57, 58, 64, 
	91, 94, 123, 127, 40, 123, 39, 92, 
	39, 92, 61, 61, 62, 61, 92, 96, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	42, 83, 92, 96, 115, 0, 47, 58, 
	64, 91, 94, 123, 127, 42, 78, 83, 
	92, 96, 110, 115, 0, 47, 58, 64, 
	91, 94, 123, 127, 42, 70, 92, 96, 
	102, 0, 47, 58, 64, 91, 94, 123, 
	127, 42, 69, 92, 96, 101, 0, 47, 
	58, 64, 91, 94, 123, 127, 42, 77, 
	92, 96, 109, 0, 47, 58, 64, 91, 
	94, 123, 127, 42, 80, 92, 96, 112, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	42, 84, 92, 96, 116, 0, 47, 58, 
	64, 91, 94, 123, 127, 42, 89, 92, 
	96, 121, 0, 47, 58, 64, 91, 94, 
	123, 127, 9, 13, 32, 47, 58, 64, 
	91, 96, 123, 126, 39, 42, 92, 96, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	0
};

static const char _query_single_lengths[] = {
	0, 0, 2, 0, 0, 2, 1, 0, 
	2, 0, 0, 2, 0, 2, 2, 1, 
	1, 2, 2, 1, 0, 5, 4, 1, 
	4, 4, 4, 1, 4, 5, 5, 4, 
	4, 5, 5, 2, 1, 0, 4, 4, 
	5, 5, 5, 2, 1, 0, 4, 3, 
	4, 0, 2, 2, 0, 33, 3, 1, 
	2, 3, 2, 6, 3, 3, 1, 4, 
	6, 5, 3, 3, 1, 4, 0, 6, 
	5, 3, 2, 2, 2, 1, 2, 1, 
	2, 5, 7, 5, 5, 5, 5, 5, 
	5, 0, 4
};

static const char _query_range_lengths[] = {
	5, 5, 0, 0, 5, 4, 1, 1, 
	1, 1, 1, 1, 1, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 5, 0, 0, 0, 6, 4, 0, 
	4, 4, 0, 5, 4, 1, 1, 1, 
	5, 4, 1, 1, 1, 1, 1, 5, 
	5, 5, 0, 0, 0, 0, 0, 0, 
	4, 4, 4, 4, 4, 4, 4, 4, 
	4, 5, 4
};

static const short _query_index_offsets[] = {
	0, 6, 12, 15, 16, 22, 29, 32, 
	34, 38, 40, 42, 46, 48, 51, 54, 
	56, 58, 61, 64, 66, 67, 73, 78, 
	80, 85, 90, 95, 97, 102, 108, 114, 
	119, 124, 130, 136, 139, 141, 142, 147, 
	152, 158, 164, 170, 173, 175, 176, 181, 
	185, 190, 196, 199, 202, 203, 243, 251, 
	253, 260, 268, 271, 283, 291, 296, 299, 
	305, 317, 327, 332, 337, 340, 346, 348, 
	360, 371, 380, 383, 386, 389, 391, 394, 
	396, 403, 413, 425, 435, 445, 455, 465, 
	475, 485, 491
};

static const unsigned char _query_indicies[] = {
	1, 1, 1, 1, 1, 0, 2, 2, 
	2, 2, 2, 0, 5, 6, 4, 4, 
	7, 7, 7, 7, 7, 0, 9, 8, 
	8, 8, 8, 8, 7, 10, 11, 8, 
	12, 0, 14, 14, 15, 13, 15, 13, 
	16, 0, 18, 18, 19, 17, 19, 0, 
	20, 20, 0, 21, 21, 0, 23, 22, 
	24, 22, 22, 26, 25, 27, 26, 25, 
	28, 22, 25, 22, 30, 31, 32, 22, 
	29, 22, 33, 34, 35, 29, 36, 22, 
	29, 29, 29, 29, 22, 22, 22, 38, 
	22, 37, 22, 39, 38, 40, 37, 41, 
	22, 37, 37, 37, 37, 22, 29, 29, 
	29, 42, 29, 22, 22, 44, 22, 45, 
	22, 43, 22, 22, 45, 46, 43, 43, 
	43, 43, 43, 22, 48, 43, 48, 49, 
	50, 47, 48, 51, 48, 49, 50, 47, 
	52, 53, 48, 35, 0, 48, 22, 22, 
	45, 35, 43, 47, 47, 47, 47, 48, 
	22, 54, 33, 34, 35, 29, 56, 29, 
	57, 58, 59, 55, 56, 60, 57, 58, 
	59, 55, 61, 62, 56, 63, 0, 56, 
	22, 33, 34, 35, 29, 61, 62, 64, 
	56, 55, 55, 55, 55, 56, 65, 65, 
	65, 65, 65, 0, 66, 68, 67, 69, 
	68, 67, 67, 71, 72, 73, 75, 76, 
	77, 78, 79, 80, 81, 82, 83, 85, 
	86, 87, 88, 89, 74, 90, 91, 92, 
	93, 94, 95, 96, 91, 92, 97, 98, 
	99, 100, 101, 70, 70, 71, 70, 74, 
	84, 74, 1, 102, 103, 0, 0, 0, 
	0, 0, 1, 105, 104, 106, 104, 104, 
	104, 104, 104, 2, 102, 106, 107, 107, 
	107, 107, 107, 2, 104, 6, 4, 109, 
	110, 110, 10, 9, 108, 108, 111, 108, 
	108, 108, 7, 113, 9, 112, 112, 112, 
	112, 112, 7, 113, 114, 114, 12, 112, 
	113, 15, 112, 113, 10, 114, 114, 11, 
	112, 113, 10, 115, 9, 112, 115, 112, 
	111, 112, 112, 112, 7, 113, 14, 14, 
	9, 112, 112, 112, 112, 112, 7, 116, 
	118, 118, 117, 0, 102, 120, 120, 16, 
	119, 102, 19, 119, 102, 116, 120, 120, 
	117, 119, 16, 104, 102, 116, 122, 103, 
	121, 122, 121, 84, 121, 121, 121, 1, 
	102, 18, 18, 103, 123, 123, 124, 123, 
	123, 123, 1, 102, 103, 119, 119, 124, 
	119, 119, 119, 1, 126, 127, 125, 52, 
	53, 48, 61, 62, 56, 130, 129, 132, 
	133, 131, 135, 134, 136, 0, 0, 0, 
	0, 0, 65, 102, 137, 103, 123, 137, 
	123, 123, 123, 123, 1, 102, 138, 139, 
	103, 123, 138, 139, 123, 123, 123, 123, 
	1, 102, 140, 103, 123, 140, 123, 123, 
	123, 123, 1, 102, 141, 103, 123, 141, 
	123, 123, 123, 123, 1, 102, 142, 103, 
	123, 142, 123, 123, 123, 123, 1, 102, 
	143, 103, 123, 143, 123, 123, 123, 123, 
	1, 102, 144, 103, 123, 144, 123, 123, 
	123, 123, 1, 102, 145, 103, 123, 145, 
	123, 123, 123, 123, 1, 1, 1, 1, 
	1, 1, 104, 146, 102, 103, 123, 123, 
	123, 123, 123, 1, 0
};

static const char _query_trans_targs[] = {
	53, 54, 57, 53, 2, 53, 3, 60, 
	53, 4, 7, 63, 61, 53, 9, 62, 
	67, 53, 12, 68, 14, 53, 53, 16, 
	17, 18, 20, 19, 53, 22, 25, 29, 
	40, 23, 24, 53, 53, 26, 28, 27, 
	53, 53, 30, 31, 33, 32, 53, 34, 
	35, 39, 75, 38, 36, 37, 41, 42, 
	43, 47, 48, 76, 46, 44, 45, 53, 
	76, 80, 53, 51, 52, 53, 53, 53, 
	55, 53, 53, 56, 53, 58, 53, 53, 
	59, 66, 66, 70, 71, 74, 53, 77, 
	78, 79, 80, 81, 82, 53, 89, 53, 
	54, 90, 53, 53, 53, 53, 53, 0, 
	53, 53, 1, 53, 53, 5, 6, 64, 
	53, 53, 8, 65, 10, 69, 13, 53, 
	11, 53, 72, 53, 73, 53, 15, 21, 
	53, 53, 53, 53, 53, 53, 53, 53, 
	49, 54, 83, 84, 54, 85, 86, 87, 
	88, 54, 50
};

static const unsigned char _query_trans_actions[] = {
	105, 143, 116, 99, 0, 63, 0, 155, 
	97, 0, 0, 155, 5, 103, 0, 0, 
	110, 93, 0, 0, 0, 9, 95, 0, 
	0, 0, 0, 0, 65, 0, 0, 0, 
	0, 0, 0, 47, 55, 0, 0, 0, 
	53, 57, 0, 0, 0, 0, 49, 0, 
	0, 0, 149, 0, 0, 0, 0, 0, 
	0, 0, 0, 146, 0, 0, 0, 51, 
	152, 113, 101, 0, 0, 67, 45, 41, 
	0, 11, 43, 137, 35, 5, 23, 25, 
	134, 131, 128, 0, 107, 125, 31, 0, 
	0, 0, 137, 143, 143, 37, 0, 39, 
	137, 143, 27, 21, 29, 33, 59, 0, 
	85, 13, 0, 73, 83, 0, 0, 155, 
	91, 61, 0, 155, 0, 110, 0, 71, 
	0, 69, 143, 87, 110, 81, 0, 0, 
	89, 79, 19, 75, 15, 7, 77, 17, 
	0, 119, 143, 143, 122, 143, 143, 143, 
	143, 140, 0
};

static const unsigned char _query_to_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 1, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0
};

static const unsigned char _query_from_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 3, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0
};

static const short _query_eof_trans[] = {
	1, 1, 4, 4, 1, 9, 9, 1, 
	14, 14, 1, 18, 1, 1, 1, 23, 
	23, 23, 23, 23, 23, 23, 23, 23, 
	23, 23, 23, 23, 23, 23, 23, 23, 
	23, 23, 23, 1, 1, 1, 23, 23, 
	23, 23, 23, 1, 1, 1, 23, 23, 
	23, 1, 67, 67, 67, 0, 1, 105, 
	105, 108, 105, 109, 113, 113, 113, 113, 
	113, 113, 1, 120, 120, 120, 105, 122, 
	124, 120, 126, 129, 1, 130, 132, 135, 
	1, 124, 124, 124, 124, 124, 124, 124, 
	124, 105, 124
};

static const int query_start = 53;
static const int query_first_final = 53;
static const int query_error = -1;

static const int query_en_main = 53;


/* #line 755 "lexer.rl" */

QueryNode *RSQuery_ParseRaw_v3(QueryParseCtx *q) {
  void *pParser = RSQuery_ParseAlloc_v3(rm_malloc);

  int cs, act;
  const char* ts = q->raw;          // query start
  const char* te = q->raw + q->len; // query end
  
/* #line 363 "lexer.c" */
	{
	cs = query_start;
	ts = 0;
	te = 0;
	act = 0;
	}

/* #line 763 "lexer.rl" */
  QueryToken tok = {.len = 0, .pos = 0, .s = 0};

  //parseCtx ctx = {.root = NULL, .ok = 1, .errorMsg = NULL, .q = q};
  const char* p = q->raw;
  const char* pe = q->raw + q->len;
  const char* eof = pe;

  
/* #line 380 "lexer.c" */
	{
	int _klen;
	unsigned int _trans;
	const char *_acts;
	unsigned int _nacts;
	const char *_keys;

	if ( p == pe )
		goto _test_eof;
_resume:
	_acts = _query_actions + _query_from_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 1:
/* #line 1 "NONE" */
	{ts = p;}
	break;
/* #line 399 "lexer.c" */
		}
	}

	_keys = _query_trans_keys + _query_key_offsets[cs];
	_trans = _query_index_offsets[cs];

	_klen = _query_single_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + _klen - 1;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + ((_upper-_lower) >> 1);
			if ( (*p) < *_mid )
				_upper = _mid - 1;
			else if ( (*p) > *_mid )
				_lower = _mid + 1;
			else {
				_trans += (unsigned int)(_mid - _keys);
				goto _match;
			}
		}
		_keys += _klen;
		_trans += _klen;
	}

	_klen = _query_range_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + (_klen<<1) - 2;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + (((_upper-_lower) >> 1) & ~1);
			if ( (*p) < _mid[0] )
				_upper = _mid - 2;
			else if ( (*p) > _mid[1] )
				_lower = _mid + 2;
			else {
				_trans += (unsigned int)((_mid - _keys)>>1);
				goto _match;
			}
		}
		_trans += _klen;
	}

_match:
	_trans = _query_indicies[_trans];
_eof_trans:
	cs = _query_trans_targs[_trans];

	if ( _query_trans_actions[_trans] == 0 )
		goto _again;

	_acts = _query_actions + _query_trans_actions[_trans];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 )
	{
		switch ( *_acts++ )
		{
	case 2:
/* #line 1 "NONE" */
	{te = p+1;}
	break;
	case 3:
/* #line 99 "lexer.rl" */
	{act = 1;}
	break;
	case 4:
/* #line 110 "lexer.rl" */
	{act = 2;}
	break;
	case 5:
/* #line 121 "lexer.rl" */
	{act = 3;}
	break;
	case 6:
/* #line 130 "lexer.rl" */
	{act = 4;}
	break;
	case 7:
/* #line 148 "lexer.rl" */
	{act = 6;}
	break;
	case 8:
/* #line 157 "lexer.rl" */
	{act = 7;}
	break;
	case 9:
/* #line 276 "lexer.rl" */
	{act = 22;}
	break;
	case 10:
/* #line 291 "lexer.rl" */
	{act = 24;}
	break;
	case 11:
/* #line 299 "lexer.rl" */
	{act = 25;}
	break;
	case 12:
/* #line 314 "lexer.rl" */
	{act = 27;}
	break;
	case 13:
/* #line 347 "lexer.rl" */
	{act = 32;}
	break;
	case 14:
/* #line 357 "lexer.rl" */
	{act = 34;}
	break;
	case 15:
/* #line 367 "lexer.rl" */
	{act = 35;}
	break;
	case 16:
/* #line 378 "lexer.rl" */
	{act = 36;}
	break;
	case 17:
/* #line 437 "lexer.rl" */
	{act = 37;}
	break;
	case 18:
/* #line 555 "lexer.rl" */
	{act = 40;}
	break;
	case 19:
/* #line 664 "lexer.rl" */
	{act = 43;}
	break;
	case 20:
/* #line 139 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts+1;
    RSQuery_Parse_v3(pParser, ARROW, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 21:
/* #line 157 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 22:
/* #line 168 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, QUOTE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 23:
/* #line 176 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts - q->raw;
    RSQuery_Parse_v3(pParser, NOT_EQUAL, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 24:
/* #line 184 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts - q->raw;
    RSQuery_Parse_v3(pParser, EQUAL_EQUAL, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 25:
/* #line 208 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts - q->raw;
    RSQuery_Parse_v3(pParser, GE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 26:
/* #line 224 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts - q->raw;
    RSQuery_Parse_v3(pParser, LE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 27:
/* #line 240 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, OR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 28:
/* #line 247 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, LP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 29:
/* #line 255 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, RP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 30:
/* #line 262 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 31:
/* #line 269 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 32:
/* #line 283 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v3(pParser, SEMICOLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 33:
/* #line 307 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, TILDE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 34:
/* #line 322 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, PERCENT, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 35:
/* #line 330 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, LSQB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 36:
/* #line 338 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, RSQB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 37:
/* #line 345 "lexer.rl" */
	{te = p+1;}
	break;
	case 38:
/* #line 347 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts - q->raw;
    RSQuery_Parse_v3(pParser, PUNCTUATION, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 39:
/* #line 355 "lexer.rl" */
	{te = p+1;}
	break;
	case 40:
/* #line 378 "lexer.rl" */
	{te = p+1;{
    tok.numval = 0;
    tok.len = 1;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.s = ts + 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = te - (ts + 3);
    tok.s = ts + 2;

    bool parsed = false;
    if(tok.len > 3) {
      if(tok.s[0] == 'w' && tok.s[1] == '\'' && tok.s[tok.len - 1] == '\'') {
        int is_attr = (*(ts + 4) == '$') ? 1 : 0;
        tok.type = is_attr ? QT_PARAM_WILDCARD : QT_WILDCARD;
        tok.len = te - (ts + 6 + is_attr);
        tok.s = ts + 4 + is_attr;
        tok.pos = tok.s - q->raw;
        RSQuery_Parse_v3(pParser, WILDCARD, tok, q);
        parsed = true;
      }
    }

    if(!parsed) {
      // remove leading spaces
      while(tok.len && isspace(tok.s[0])) {
        tok.s++;
        tok.len--;
      }
      // remove trailing spaces
      while(tok.len > 1 && isspace(tok.s[tok.len - 1])) {
        tok.len--;
      }
      tok.pos = tok.s - q->raw;
      tok.type = QT_TERM;
      RSQuery_Parse_v3(pParser, UNESCAPED_TAG, tok, q);
    }
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = 1;
    tok.s = te - 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 41:
/* #line 437 "lexer.rl" */
	{te = p+1;{
    tok.numval = 0;
    tok.len = 1;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.s = ts + 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = te - (ts + 3);
    tok.s = ts + 2;
    tok.pos = tok.s - q->raw;
    tok.type = QT_TERM;
    RSQuery_Parse_v3(pParser, UNESCAPED_TAG, tok, q);

    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = 1;
    tok.s = te - 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 42:
/* #line 472 "lexer.rl" */
	{te = p+1;{
    tok.numval = 0;
    tok.len = 1;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.s = ts + 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    int is_attr = (*(ts + 4) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_WILDCARD : QT_WILDCARD;
    tok.len = te - (ts + 6 + is_attr);
    tok.s = ts + 4 + is_attr;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, WILDCARD, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = 1;
    tok.s = te - 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 43:
/* #line 507 "lexer.rl" */
	{te = p+1;{
    tok.numval = 0;
    tok.len = 1;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.s = ts + 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    int is_attr = (*(ts + 3) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 3 + is_attr) - 1;
    tok.s = ts + 3 + is_attr;
    tok.pos = tok.s - q->raw;
    // Invalid case: wildcard and suffix
    if(tok.s[0] == 'w' && tok.s[1] == '\'') {
      {p++; goto _out; }
    }
    // remove leading spaces
    while(tok.len && isspace(tok.s[0])) {
      tok.s++;
      tok.len--;
    }
    // remove trailing spaces
    while(tok.len > 1 && isspace(tok.s[tok.len - 1])) {
      tok.len--;
    }
    RSQuery_Parse_v3(pParser, SUFFIX, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = 1;
    tok.s = te - 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 44:
/* #line 555 "lexer.rl" */
	{te = p+1;{
    tok.numval = 0;
    tok.len = 1;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.s = ts + 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    int is_attr = (*(ts + 2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 2 + is_attr) - 2;
    tok.s = ts + 2 + is_attr;
    tok.pos = tok.s - q->raw;
    // Invalid case: wildcard and prefix
    if(tok.s[0] == 'w' && tok.s[1] == '\'') {
      {p++; goto _out; }
    }
    // remove leading spaces
    while(tok.len && isspace(tok.s[0])) {
      tok.s++;
      tok.len--;
    }
    // remove trailing spaces
    while(tok.len > 1 && isspace(tok.s[tok.len - 1])) {
      tok.len--;
    }
    RSQuery_Parse_v3(pParser, PREFIX, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = 1;
    tok.s = te - 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 45:
/* #line 603 "lexer.rl" */
	{te = p+1;{
    tok.numval = 0;
    tok.len = 1;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.s = ts + 2;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    int is_attr = (*(ts + 3) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 3 + is_attr) - 2;
    tok.s = ts + 3 + is_attr;
    tok.pos = tok.s - q->raw;
    // Invalid case: wildcard and contains
    if(tok.s[0] == 'w' && tok.s[1] == '\'') {
      {p++; goto _out; }
    }
    // remove leading spaces
    while(tok.len && isspace(tok.s[0])) {
      tok.s++;
      tok.len--;
    }
    // remove trailing spaces
    while(tok.len > 1 && isspace(tok.s[tok.len - 1])) {
      tok.len--;
    }
    RSQuery_Parse_v3(pParser, CONTAINS, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = 1;
    tok.s = te - 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 46:
/* #line 651 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*ts == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, PREFIX, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 47:
/* #line 677 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts + 1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, CONTAINS, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 48:
/* #line 690 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    RSQuery_Parse_v3(pParser, VERBATIM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 49:
/* #line 703 "lexer.rl" */
	{te = p+1;{
    tok.numval = 0;
    tok.len = 1;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.s = ts + 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, LP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    int is_attr = (*(ts + 4) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_WILDCARD : QT_WILDCARD;
    tok.len = te - (ts + 6 + is_attr);
    tok.s = ts + 4 + is_attr;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, WILDCARD, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = 1;
    tok.s = te - 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, RP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 50:
/* #line 738 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_WILDCARD : QT_WILDCARD;
    tok.pos = ts-q->raw + 2;
    tok.len = te - (ts + 3 + is_attr);
    tok.s = ts + 2 + is_attr;
    tok.numval = 0;
    RSQuery_Parse_v3(pParser, WILDCARD, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 51:
/* #line 99 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 52:
/* #line 110 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 53:
/* #line 130 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v3(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 54:
/* #line 192 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts - q->raw;
    RSQuery_Parse_v3(pParser, EQUAL, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 55:
/* #line 200 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts - q->raw;
    RSQuery_Parse_v3(pParser, GT, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 56:
/* #line 216 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts - q->raw;
    RSQuery_Parse_v3(pParser, LT, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 57:
/* #line 276 "lexer.rl" */
	{te = p;p--;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 58:
/* #line 314 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 59:
/* #line 347 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts - q->raw;
    RSQuery_Parse_v3(pParser, PUNCTUATION, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 60:
/* #line 367 "lexer.rl" */
	{te = p;p--;{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 61:
/* #line 437 "lexer.rl" */
	{te = p;p--;{
    tok.numval = 0;
    tok.len = 1;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.s = ts + 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = te - (ts + 3);
    tok.s = ts + 2;
    tok.pos = tok.s - q->raw;
    tok.type = QT_TERM;
    RSQuery_Parse_v3(pParser, UNESCAPED_TAG, tok, q);

    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = 1;
    tok.s = te - 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 62:
/* #line 664 "lexer.rl" */
	{te = p;p--;{
    int is_attr = (*(ts + 1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, SUFFIX, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 63:
/* #line 110 "lexer.rl" */
	{{p = ((te))-1;}{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 64:
/* #line 276 "lexer.rl" */
	{{p = ((te))-1;}{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 65:
/* #line 314 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 66:
/* #line 347 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.pos = ts - q->raw;
    RSQuery_Parse_v3(pParser, PUNCTUATION, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 67:
/* #line 367 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 68:
/* #line 664 "lexer.rl" */
	{{p = ((te))-1;}{
    int is_attr = (*(ts + 1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, SUFFIX, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 69:
/* #line 1 "NONE" */
	{	switch( act ) {
	case 1:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 2:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 3:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v3(pParser, MODIFIER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 4:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v3(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 6:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, AS_T, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 7:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 22:
	{{p = ((te))-1;} 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }
	break;
	case 24:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 25:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, PLUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 27:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 32:
	{{p = ((te))-1;}
    tok.pos = ts - q->raw;
    RSQuery_Parse_v3(pParser, PUNCTUATION, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 34:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, ISEMPTY, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 35:
	{{p = ((te))-1;}
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 36:
	{{p = ((te))-1;}
    tok.numval = 0;
    tok.len = 1;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.s = ts + 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = te - (ts + 3);
    tok.s = ts + 2;

    bool parsed = false;
    if(tok.len > 3) {
      if(tok.s[0] == 'w' && tok.s[1] == '\'' && tok.s[tok.len - 1] == '\'') {
        int is_attr = (*(ts + 4) == '$') ? 1 : 0;
        tok.type = is_attr ? QT_PARAM_WILDCARD : QT_WILDCARD;
        tok.len = te - (ts + 6 + is_attr);
        tok.s = ts + 4 + is_attr;
        tok.pos = tok.s - q->raw;
        RSQuery_Parse_v3(pParser, WILDCARD, tok, q);
        parsed = true;
      }
    }

    if(!parsed) {
      // remove leading spaces
      while(tok.len && isspace(tok.s[0])) {
        tok.s++;
        tok.len--;
      }
      // remove trailing spaces
      while(tok.len > 1 && isspace(tok.s[tok.len - 1])) {
        tok.len--;
      }
      tok.pos = tok.s - q->raw;
      tok.type = QT_TERM;
      RSQuery_Parse_v3(pParser, UNESCAPED_TAG, tok, q);
    }
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = 1;
    tok.s = te - 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 37:
	{{p = ((te))-1;}
    tok.numval = 0;
    tok.len = 1;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.s = ts + 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = te - (ts + 3);
    tok.s = ts + 2;
    tok.pos = tok.s - q->raw;
    tok.type = QT_TERM;
    RSQuery_Parse_v3(pParser, UNESCAPED_TAG, tok, q);

    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = 1;
    tok.s = te - 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 40:
	{{p = ((te))-1;}
    tok.numval = 0;
    tok.len = 1;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.s = ts + 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    int is_attr = (*(ts + 2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 2 + is_attr) - 2;
    tok.s = ts + 2 + is_attr;
    tok.pos = tok.s - q->raw;
    // Invalid case: wildcard and prefix
    if(tok.s[0] == 'w' && tok.s[1] == '\'') {
      {p++; goto _out; }
    }
    // remove leading spaces
    while(tok.len && isspace(tok.s[0])) {
      tok.s++;
      tok.len--;
    }
    // remove trailing spaces
    while(tok.len > 1 && isspace(tok.s[tok.len - 1])) {
      tok.len--;
    }
    RSQuery_Parse_v3(pParser, PREFIX, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }

    tok.len = 1;
    tok.s = te - 1;
    tok.pos = tok.s - q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 43:
	{{p = ((te))-1;}
    int is_attr = (*(ts + 1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, SUFFIX, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	}
	}
	break;
/* #line 1653 "lexer.c" */
		}
	}

_again:
	_acts = _query_actions + _query_to_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 0:
/* #line 1 "NONE" */
	{ts = 0;}
	break;
/* #line 1666 "lexer.c" */
		}
	}

	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	if ( _query_eof_trans[cs] > 0 ) {
		_trans = _query_eof_trans[cs] - 1;
		goto _eof_trans;
	}
	}

	_out: {}
	}

/* #line 771 "lexer.rl" */

  if (QPCTX_ISOK(q)) {
    RSQuery_Parse_v3(pParser, 0, tok, q);
  }
  RSQuery_ParseFree_v3(pParser, rm_free);
  if (!QPCTX_ISOK(q) && q->root) {
    QueryNode_Free(q->root);
    q->root = NULL;
  }
  return q->root;
}

