#define LOWEST                           1
#define PUNCTUATION                      2
#define TEXTEXPR                         3
#define ORX                              4
#define OR                               5
#define ISEMPTY                          6
#define MODIFIER                         7
#define RP                               8
#define RB                               9
#define RSQB                            10
#define TERM                            11
#define QUOTE                           12
#define LP                              13
#define LB                              14
#define LSQB                            15
#define TILDE                           16
#define MINUS                           17
#define AND                             18
#define NOT_EQUAL                       19
#define EQUAL                           20
#define GE                              21
#define GT                              22
#define LE                              23
#define LT                              24
#define ARROW                           25
#define COLON                           26
#define NUMBER                          27
#define SIZE                            28
#define STAR                            29
#define TAGLIST                         30
#define TERMLIST                        31
#define PREFIX                          32
#define SUFFIX                          33
#define CONTAINS                        34
#define PERCENT                         35
#define ATTRIBUTE                       36
#define VERBATIM                        37
#define WILDCARD                        38
#define AS_T                            39
#define SEMICOLON                       40
