#define LOWEST                           1
#define PUNCTUATION                      2
#define TEXTEXPR                         3
#define ORX                              4
#define OR                               5
#define ISEMPTY                          6
#define MODIFIER                         7
#define RP                               8
#define RB                               9
#define RSQB                            10
#define TERM                            11
#define QUOTE                           12
#define LP                              13
#define LB                              14
#define LSQB                            15
#define TILDE                           16
#define MINUS                           17
#define AND                             18
#define ARROW                           19
#define COLON                           20
#define NUMBER                          21
#define SIZE                            22
#define STAR                            23
#define TAGLIST                         24
#define TERMLIST                        25
#define PREFIX                          26
#define SUFFIX                          27
#define CONTAINS                        28
#define PERCENT                         29
#define ATTRIBUTE                       30
#define VERBATIM                        31
#define WILDCARD                        32
#define AS_T                            33
#define SEMICOLON                       34
