#define LOWEST                           1
#define PUNCTUATION                      2
#define TEXTEXPR                         3
#define ORX                              4
#define OR                               5
#define ISEMPTY                          6
#define MODIFIER                         7
#define RP                               8
#define RB                               9
#define RSQB                            10
#define UNESCAPED_TAG                   11
#define TERM                            12
#define QUOTE                           13
#define LP                              14
#define LB                              15
#define LSQB                            16
#define TILDE                           17
#define MINUS                           18
#define PLUS                            19
#define AND                             20
#define EQUAL                           21
#define NOT_EQUAL                       22
#define EQUAL_EQUAL                     23
#define GE                              24
#define GT                              25
#define LE                              26
#define LT                              27
#define ARROW                           28
#define COLON                           29
#define NUMBER                          30
#define SIZE                            31
#define STAR                            32
#define TAGLIST                         33
#define TERMLIST                        34
#define PREFIX                          35
#define SUFFIX                          36
#define CONTAINS                        37
#define PERCENT                         38
#define ATTRIBUTE                       39
#define VERBATIM                        40
#define WILDCARD                        41
#define AS_T                            42
#define SEMICOLON                       43
