/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
*/

use crate::{RLookup, RLookupKey, RLookupKeyFlag, RLookupKeyFlags, lookup::TRANSIENT_FLAGS};
use sorting_vector::{RSSortingVector, RSSortingVectorRef};
use std::{borrow::Cow, ffi::CStr, fmt};
use thin_vec::ThinVec;
use value::SharedValue;

/// Row data for a lookup key. This abstracts the question of if the data comes from a borrowed sorting vector slice
/// or from dynamic values stored in the row during processing.
///
/// The C-visible layout comes from the `OpaqueRLookupRow` wrapper (which is
/// `#[repr(C, align(8))]` and `#[cheadergen::config(rename = "RLookupRow")]`).
/// Force this internal type to opaque so cheadergen does not warn about it
/// being reached by value through `SearchResult._row_data` — both names emit
/// to the same C tag, and the wrapper provides the actual layout.
#[cheadergen::config(export, opaque)]
pub struct RLookupRow<'a> {
    /// A reference to the sorting vector.
    sorting_vector: RSSortingVectorRef<'a>,

    /// Dynamic values obtained from prior processing
    dyn_values: ThinVec<Option<SharedValue>>,

    /// The number of values in [`RLookupRow::dyn_values`] that are `is_some()`. Note that this
    /// is not the length of [`RLookupRow::dyn_values`]
    num_dyn_values: u32,
}

impl fmt::Debug for RLookupRow<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // NB: we purposefully DO NOT include the sorting_vector and dyn_values fields here,
        // so we don't accidentally leak user-data into log messages!
        f.debug_struct("RLookupRow")
            .field("num_dyn_values", &self.num_dyn_values)
            .finish_non_exhaustive()
    }
}

impl<'a> Default for RLookupRow<'a> {
    fn default() -> Self {
        Self::new()
    }
}

impl<'a> RLookupRow<'a> {
    /// Creates a new `RLookupRow` with an empty [`RLookupRow::dyn_values`] vector and
    /// a [`RLookupRow::sorting_vector`] of the given length.
    #[inline]
    pub const fn new() -> Self {
        Self {
            sorting_vector: RSSortingVectorRef::empty(),
            dyn_values: ThinVec::new(),
            num_dyn_values: 0,
        }
    }

    /// Returns the length of [`RLookupRow::dyn_values`].
    #[inline]
    pub fn len(&self) -> usize {
        self.dyn_values.len()
    }

    /// Returns true if the [`RLookupRow::dyn_values`] vector is empty.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.dyn_values.is_empty()
    }

    /// Readonly access to the [`RLookupRow::dyn_values`] vector that has been generated by prior processing.
    ///
    /// The function [`RLookupRow::write_key`] can be used to write values to this vector.
    #[inline]
    pub fn dyn_values(&self) -> &[Option<SharedValue>] {
        &self.dyn_values
    }

    /// Sets the capacity of the [`RLookupRow::dyn_values`] vector to the given capacity.
    /// It fills up the vector with None values to the given capacity.
    /// This is useful to preallocate memory for the row if you know the number of values that will be written to it.
    pub fn set_dyn_capacity(&mut self, capacity: usize) {
        self.dyn_values.resize(capacity, None);
    }

    /// Readonly access to the sorting vector values as a slice.
    #[inline]
    pub fn sorting_vector(&self) -> &'a [SharedValue] {
        self.sorting_vector.as_slice()
    }

    /// Borrow a sorting vector for the row.
    pub const fn set_sorting_vector(&mut self, sv: Option<&'a RSSortingVector>) {
        // We use [`RSSortingVectorRef`], a pointer-sized borrowed view, to avoid
        // dereferencing the `ThinVec` header here. This is a performance optimization
        // for hot paths where this function is called frequently and the sorting vector
        // being set may not need to be dereferenced later on.
        match sv {
            Some(sv) => {
                self.sorting_vector = RSSortingVectorRef::from_ref(sv);
            }
            None => {
                self.sorting_vector = RSSortingVectorRef::empty();
            }
        }
    }

    /// The number of values in [`RLookupRow::dyn_values`] that are `is_some()`. Note that this
    /// is not the length of [`RLookupRow::dyn_values`]
    #[inline]
    pub const fn num_dyn_values(&self) -> u32 {
        self.num_dyn_values
    }

    /// Retrieves an item from the given `RLookupRow` based on the provided `RLookupKey`.
    /// The function first checks for dynamic values, and if not found, it checks the sorting vector
    /// if the `SvSrc` flag is set in the key.
    /// If the item is not found in either location, it returns `None`.
    #[inline]
    pub fn get(&self, key: &RLookupKey) -> Option<&SharedValue> {
        // Check dynamic values first
        if let Some(Some(val)) = self.dyn_values().get(key.dstidx as usize) {
            return Some(val);
        }

        // If not found in dynamic values, check the sorting vector if the SvSrc flag is set
        if key.flags.contains(RLookupKeyFlag::SvSrc) {
            // Sorting vector slots that were never written hold the null sentinel.
            // Filter it out so callers see `None` for absent fields, mirroring the C
            // guard in `RLookupRow_Get`:
            //   `if (ret != NULL && ret == RSValue_NullStatic()) ret = NULL;`
            self.sorting_vector()
                .get(key.svidx as usize)
                .filter(|v| !v.is_null_static())
        } else {
            None
        }
    }

    /// Write a value to the lookup table in [`RLookupRow::dyn_values`]. Key must already be registered, and not
    /// refer to a read-only (SVSRC) key.
    pub fn write_key(&mut self, key: &RLookupKey, val: SharedValue) -> Option<SharedValue> {
        let idx = key.dstidx;
        if self.dyn_values.len() <= idx as usize {
            self.set_dyn_capacity((idx + 1) as usize);
        }

        let prev = self.dyn_values[idx as usize].replace(val);

        if prev.is_none() {
            self.num_dyn_values += 1;
        }

        prev
    }

    /// Write a value to the lookup table *by-name*. This is useful for 'dynamic' keys
    /// for which it is not necessary to use the boilerplate of getting an explicit
    /// key.
    pub fn write_key_by_name(
        &mut self,
        rlookup: &mut RLookup<'a>,
        name: impl Into<Cow<'a, CStr>>,
        val: SharedValue,
    ) {
        let name = name.into();
        let key = if let Some(cursor) = rlookup.find_key_by_name(&name) {
            cursor.into_current().expect("the cursor returned by `Keys::find_by_name` must have a current key. This is a bug!")
        } else {
            rlookup
                .get_key_write(name.into_owned(), RLookupKeyFlags::empty())
                .expect("`RLookup::get_key_write` must never return None for non-existent keys. This is a bug!")
        };
        self.write_key(key, val);
    }

    /// Wipes the row, retaining its memory but decrementing the ref count of any included instance of `T`.
    /// This does not free all the memory consumed by the row, but simply resets
    /// the row data (preserving any caches) so that it may be refilled.
    /// Also clears the sorting vector.
    #[inline]
    pub fn wipe(&mut self) {
        let mut remaining = self.num_dyn_values;
        for value in self.dyn_values.iter_mut() {
            if remaining == 0 {
                break;
            }
            if value.is_some() {
                drop(value.take());
                remaining -= 1;
            }
        }
        self.num_dyn_values = 0;
        self.sorting_vector = RSSortingVectorRef::empty();
    }

    /// Resets the row, clearing the dynamic values. This effectively wipes the row and deallocates the memory used for dynamic values.
    ///
    /// It does not affect the sorting vector.
    pub fn reset_dyn_values(&mut self) {
        self.num_dyn_values = 0;
        self.dyn_values = ThinVec::new();
    }

    /// Write fields from a source row into this row.
    ///
    /// Iterate through the source lookup keys, if it finds a corresponding key in the destination
    /// lookup by name, then it's value is written to this row as a destination.
    ///
    /// If a source key has no value in the source row, it is skipped.
    ///
    /// If a source key is not found in the destination lookup the function will either create it or panic
    /// depending on the value of `create_missing_keys`.
    ///
    /// # Arguments
    ///
    /// - `dst_lookup`: The destination lookup containing the schema of this row, must be the associated lookup of `self`.
    /// - `src_row`: The source row from which to copy values.
    /// - `src_lookup`: The source lookup containing the schema of the source row, must be the associated lookup of `src_row`.
    /// - `create_missing_keys`: Whether keys missing in `dst_lookup` should be created automatically, or force a panic.
    pub fn copy_fields_from(
        &mut self,
        dst_lookup: &mut RLookup<'a>,
        src_row: &Self,
        src_lookup: &RLookup<'a>,
        create_missing_keys: bool,
    ) {
        let dst_row = self;

        for src_key in src_lookup.iter() {
            if let Some(value) = src_row.get(src_key) {
                // Find corresponding key in destination lookup
                let dst_key = match dst_lookup.find_key_by_name(src_key.name()) {
                    Some(k) => k.into_current().unwrap(),
                    None if create_missing_keys => {
                        // Inherit non-transient flags from source.
                        let flags = src_key.flags & !TRANSIENT_FLAGS;

                        // Key doesn't exist in destination - create it on demand.
                        // This can happen with LOAD * where keys are created dynamically.
                        dst_lookup
                            .get_key_write(src_key.name().clone(), flags)
                            .unwrap()
                    }
                    _ => panic!("all source keys must exist in destination"),
                };

                // Write fields to destination
                dst_row.write_key(dst_key, value.clone());
            }
        }
    }

    /// Move data from the source row to the destination row. The source row is cleared.
    pub fn move_fields_from(&mut self, src: &mut Self, lookup: &RLookup) {
        for key in lookup.iter() {
            if let Some(value) = src.get(key) {
                self.write_key(key, value.to_owned());
            }
        }
        src.wipe();
    }

    #[track_caller]
    #[cfg(any(debug_assertions, test))]
    pub fn assert_valid(&self, ctx: &str) {
        for val in self.dyn_values.iter().flatten() {
            assert!(
                SharedValue::refcount(val) >= 1,
                "{ctx} - SharedValue refcount must not be zero"
            );
        }
    }
}

pub mod opaque {
    use super::RLookupRow;
    use c_ffi_utils::opaque::Size;

    /// An opaque lookup row which can be passed by value to C.
    ///
    /// The size and alignment of this struct must match the Rust `RLookupRow`
    /// structure exactly.
    #[cheadergen::config(rename = "RLookupRow")]
    #[repr(C, align(8))]
    pub struct OpaqueRLookupRow(Size<24>);

    c_ffi_utils::opaque!(RLookupRow<'_>, OpaqueRLookupRow);
}
