/*
 * Copyright (c) 2006-Present, Redis Ltd.
 * All rights reserved.
 *
 * Licensed under your choice of the Redis Source Available License 2.0
 * (RSALv2); or (b) the Server Side Public License v1 (SSPLv1); or (c) the
 * GNU Affero General Public License v3 (AGPLv3).
*/

use std::env;
use std::path::PathBuf;

use build_utils::{repository_root, rerun_if_c_changes};

fn main() {
    let root =
        repository_root().expect("Could not find repository root for static library linking");

    // Construct the correct folder path based on OS and architecture
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();

    // There are several symbols exposed by the C code that we don't
    // actually invoke (either directly or indirectly) in our benchmarks.
    // We provide a definition for the ones we need (e.g. Redis' allocation functions),
    // but we don't want to be forced to add dummy definitions for the ones we don't rely on.
    // We prefer to fail at runtime if we try to use a symbol that's undefined.
    // This is the default linker behaviour on macOS. On other platforms, the default
    // configuration is stricter: it exits with an error if any symbol is undefined.
    // We intentionally relax it here.
    if target_os != "macos" {
        println!("cargo:rustc-link-arg=-Wl,--unresolved-symbols=ignore-in-object-files");
    }

    let includes = {
        let src = root.join("src");
        let deps = root.join("deps");

        let redisearch_rs = src.join("redisearch_rs").join("headers");
        let inverted_index = src.join("inverted_index");
        let vecsim = deps.join("VectorSimilarity").join("src");
        let buffer = src.join("buffer");
        let ttl_table = src.join("ttl_table");
        let trie = src.join("trie");
        let rmalloc = deps.join("rmalloc");

        [
            src,
            deps,
            redisearch_rs,
            inverted_index,
            vecsim,
            buffer,
            ttl_table,
            trie,
            rmalloc,
        ]
    };

    let src = root.join("src");
    let deps = root.join("deps");
    let headers = [
        src.join("redismodule.h"),
        deps.join("hiredis").join("sds.h"),
        deps.join("rmutil").join("vector.h"),
        src.join("aggregate").join("reducer.h"),
        src.join("buffer/buffer.h"),
        src.join("config.h"),
        src.join("doc_table.h"),
        src.join("forward_index.h"),
        src.join("geo_index.h"),
        src.join("rs_geo.h"),
        deps.join("geohash").join("geohash.h"),
        src.join("index_result").join("index_result.h"),
        src.join("json.h"),
        src.join("obfuscation").join("hidden.h"),
        src.join("obfuscation").join("obfuscation_api.h"),
        src.join("query.h"),
        src.join("redis_index.h"),
        src.join("redisearch.h"),
        src.join("result_processor.h"),
        src.join("rlookup.h"),
        src.join("rlookup_load_document.h"),
        src.join("rules.h"),
        src.join("score_explain.h"),
        src.join("search_ctx.h"),
        src.join("search_disk.h"),
        src.join("search_disk_api.h"),
        src.join("search_result.h"),
        src.join("sortable.h"),
        src.join("spec.h"),
        src.join("stopwords.h"),
        src.join("numeric_filter.h"),
        src.join("tag_index.h"),
        src.join("trie").join("trie.h"),
        src.join("trie").join("trie_type.h"),
        src.join("ttl_table").join("ttl_table.h"),
        src.join("util").join("arr").join("arr.h"),
        src.join("util").join("dict").join("dict.h"),
        src.join("util").join("references.h"),
    ];

    let mut bindings = bindgen::Builder::default();

    for header in headers {
        bindings = bindings
            .header(header.display().to_string())
            .allowlist_file(header.display().to_string());

        println!("cargo:rerun-if-changed={}", header.display());
    }
    for include in includes {
        bindings = bindings.clang_arg(format!("-I{}", include.display()));
        // Re-run the build script if any of the C files in the included
        // directory changes
        let _ = rerun_if_c_changes(&include);
    }

    // Required so `<stdio.h>` declares `asprintf`/`vasprintf` (used by
    // `deps/rmalloc/rmalloc.h`) when bindgen parses the headers with clang.
    bindings = bindings.clang_arg("-D_GNU_SOURCE");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .blocklist_file(".*/document_rs.h")
        // numeric_range_tree.h is generated by Rust (cbindgen) and those types
        // are provided by the numeric_range_tree_ffi crate, not parsed from C
        .blocklist_file(".*/numeric_range_tree.h")
        // Provided by the query_term_ffi crate, not parsed from C
        .blocklist_file(".*/query_term.h")
        // IteratorType is defined in Rust (rqe_iterator_type crate);
        // cbindgen generates iterator_type.h which is included by
        // iterator_api.h. We blocklist the generated header so bindgen
        // doesn't re-parse it, and re-export the Rust type from lib.rs.
        .blocklist_file(".*/iterator_type.h")
        // QueryNodeType is defined in Rust (query_node_type crate);
        // cbindgen generates query_node_type.h which is included by
        // query_node.h. We blocklist the generated header so bindgen
        // doesn't re-parse it, and re-export the Rust type from lib.rs.
        .blocklist_file(".*/query_node_type.h")
        // QueryProcessingCtx is defined in Rust (ffi crate, lib.rs);
        // cbindgen generates the C definition into result_processor_rs.h.
        // Blocklist the type so bindgen doesn't re-parse it from the
        // generated header (which is included by result_processor.h).
        .blocklist_type("QueryProcessingCtx")
        .allowlist_file(".*/types_rs.h")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(out_dir.join("bindings.rs"))
        .expect("Couldn't write bindings!");
}
