[package]
name = "term_suffix_index_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
unittest = []

[dependencies]
term_suffix_index = { workspace = true }
workspace_hack.workspace = true

[dev-dependencies]
# Crate required to invoke C symbols
term_suffix_index_ffi = { path = ".", features = ["unittest"] }
redisearch_rs = { path = "../redisearch_rs" }
redis_mock.workspace = true

[target.'cfg(miri)'.dependencies]
redis_mock.workspace = true
