#define PLUS                             1
#define MINUS                            2
#define DIVIDE                           3
#define TIMES                            4
#define MOD                              5
#define POW                              6
#define LP                               7
#define RP                               8
#define PROPERTY                         9
#define FUNCTION                        10
#define STRING                          11
#define NUMBER                          12
#define FUNC                            13
#define COMMA                           14
