#define AND                              1
#define OR                               2
#define NOT                              3
#define EQ                               4
#define NE                               5
#define LT                               6
#define LE                               7
#define GT                               8
#define GE                               9
#define PLUS                            10
#define MINUS                           11
#define DIVIDE                          12
#define TIMES                           13
#define MOD                             14
#define POW                             15
#define LP                              16
#define RP                              17
#define ATTRIBUTE                       18
#define PROPERTY                        19
#define SYMBOL                          20
#define STRING                          21
#define NUMBER                          22
#define ARGLIST                         23
#define COMMA                           24
