#define LOWEST                           1
#define OR                               2
#define AND                              3
#define EQ                               4
#define NE                               5
#define LT                               6
#define LE                               7
#define GT                               8
#define GE                               9
#define NOT                             10
#define PLUS                            11
#define MINUS                           12
#define DIVIDE                          13
#define TIMES                           14
#define MOD                             15
#define POW                             16
#define LP                              17
#define RP                              18
#define PROPERTY                        19
#define SYMBOL                          20
#define STRING                          21
#define NUMBER                          22
#define ARGLIST                         23
#define COMMA                           24
