
/* #line 1 "lexer.rl" */
/*
 * Copyright Redis Ltd. 2016 - present
 * Licensed under your choice of the Redis Source Available License 2.0 (RSALv2) or
 * the Server Side Public License v1 (SSPLv1).
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>

#include "../parse.h"
#include "parser.h"
#include "../../query_node.h"
#include "../../stopwords.h"

/* forward declarations of stuff generated by lemon */

#define RSQuery_Parse_v2 RSQueryParser_v2_ // weird Lemon quirk.. oh well..
#define RSQuery_ParseAlloc_v2 RSQueryParser_v2_Alloc
#define RSQuery_ParseFree_v2 RSQueryParser_v2_Free

void RSQuery_Parse_v2(void *yyp, int yymajor, QueryToken yyminor, QueryParseCtx *ctx);
void *RSQuery_ParseAlloc_v2(void *(*mallocProc)(size_t));
void RSQuery_ParseFree_v2(void *p, void (*freeProc)(void *));


/* #line 332 "lexer.rl" */



/* #line 36 "lexer.c" */
static const char _query_actions[] = {
	0, 1, 0, 1, 1, 1, 2, 1, 
	14, 1, 15, 1, 16, 1, 17, 1, 
	18, 1, 19, 1, 20, 1, 21, 1, 
	22, 1, 23, 1, 24, 1, 25, 1, 
	26, 1, 27, 1, 28, 1, 29, 1, 
	30, 1, 31, 1, 32, 1, 33, 1, 
	34, 1, 35, 1, 36, 1, 37, 1, 
	38, 1, 39, 1, 40, 1, 41, 1, 
	42, 1, 43, 1, 44, 1, 45, 1, 
	46, 1, 47, 1, 48, 1, 49, 1, 
	50, 1, 51, 2, 2, 3, 2, 2, 
	4, 2, 2, 5, 2, 2, 6, 2, 
	2, 7, 2, 2, 8, 2, 2, 9, 
	2, 2, 10, 2, 2, 11, 2, 2, 
	12, 2, 2, 13
};

static const short _query_key_offsets[] = {
	0, 10, 20, 22, 22, 25, 28, 38, 
	48, 50, 52, 55, 57, 58, 59, 61, 
	64, 66, 76, 81, 83, 85, 87, 89, 
	91, 93, 95, 98, 99, 100, 102, 104, 
	106, 108, 110, 112, 114, 114, 155, 166, 
	176, 187, 190, 192, 206, 217, 223, 228, 
	231, 247, 259, 260, 263, 269, 274, 277, 
	293, 307, 320, 321, 331, 344, 352, 362, 
	374, 386
};

static const char _query_trans_keys[] = {
	9, 13, 32, 47, 58, 64, 91, 96, 
	123, 126, 9, 13, 32, 47, 58, 64, 
	91, 96, 123, 126, 39, 92, 39, 92, 
	110, 39, 92, 102, 9, 13, 32, 47, 
	58, 64, 91, 96, 123, 126, 92, 96, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	48, 57, 48, 57, 45, 48, 57, 48, 
	57, 110, 102, 48, 57, 45, 48, 57, 
	48, 57, 9, 13, 32, 47, 58, 64, 
	91, 96, 123, 126, 41, 67, 87, 99, 
	119, 79, 111, 78, 110, 84, 116, 65, 
	97, 73, 105, 78, 110, 83, 115, 32, 
	9, 13, 93, 93, 73, 105, 84, 116, 
	72, 104, 73, 105, 78, 110, 39, 92, 
	39, 92, 32, 34, 36, 37, 39, 40, 
	41, 42, 43, 45, 58, 59, 61, 64, 
	65, 91, 92, 93, 95, 97, 105, 119, 
	123, 124, 125, 126, 127, 0, 8, 9, 
	13, 14, 31, 33, 47, 48, 57, 60, 
	63, 94, 96, 42, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 92, 96, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	42, 92, 96, 0, 47, 58, 64, 91, 
	94, 123, 127, 39, 92, 105, 39, 92, 
	36, 45, 92, 96, 0, 47, 48, 57, 
	58, 64, 91, 94, 123, 127, 42, 92, 
	96, 0, 47, 58, 64, 91, 94, 123, 
	127, 42, 46, 69, 101, 48, 57, 42, 
	69, 101, 48, 57, 42, 48, 57, 42, 
	46, 69, 92, 96, 101, 0, 47, 48, 
	57, 58, 64, 91, 94, 123, 127, 42, 
	45, 92, 96, 0, 47, 58, 64, 91, 
	94, 123, 127, 105, 105, 48, 57, 42, 
	46, 69, 101, 48, 57, 42, 69, 101, 
	48, 57, 42, 48, 57, 42, 46, 69, 
	92, 96, 101, 0, 47, 48, 57, 58, 
	64, 91, 94, 123, 127, 42, 45, 92, 
	96, 0, 47, 48, 57, 58, 64, 91, 
	94, 123, 127, 42, 92, 96, 0, 47, 
	48, 57, 58, 64, 91, 94, 123, 127, 
	62, 92, 96, 0, 47, 58, 64, 91, 
	94, 123, 127, 42, 83, 92, 96, 115, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	32, 41, 67, 87, 99, 119, 9, 13, 
	9, 13, 32, 47, 58, 64, 91, 96, 
	123, 126, 42, 92, 96, 110, 0, 47, 
	58, 64, 91, 94, 123, 127, 42, 92, 
	96, 102, 0, 47, 58, 64, 91, 94, 
	123, 127, 39, 42, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 0
};

static const char _query_single_lengths[] = {
	0, 0, 2, 0, 3, 3, 0, 2, 
	0, 0, 1, 0, 1, 1, 0, 1, 
	0, 0, 5, 2, 2, 2, 2, 2, 
	2, 2, 1, 1, 1, 2, 2, 2, 
	2, 2, 2, 2, 0, 27, 3, 2, 
	3, 3, 2, 4, 3, 4, 3, 1, 
	6, 4, 1, 1, 4, 3, 1, 6, 
	4, 3, 1, 2, 5, 6, 0, 4, 
	4, 4
};

static const char _query_range_lengths[] = {
	5, 5, 0, 0, 0, 0, 5, 4, 
	1, 1, 1, 1, 0, 0, 1, 1, 
	1, 5, 0, 0, 0, 0, 0, 0, 
	0, 0, 1, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 7, 4, 4, 
	4, 0, 0, 5, 4, 1, 1, 1, 
	5, 4, 0, 1, 1, 1, 1, 5, 
	5, 5, 0, 4, 4, 1, 5, 4, 
	4, 4
};

static const short _query_index_offsets[] = {
	0, 6, 12, 15, 16, 20, 24, 30, 
	37, 39, 41, 44, 46, 48, 50, 52, 
	55, 57, 63, 69, 72, 75, 78, 81, 
	84, 87, 90, 93, 95, 97, 100, 103, 
	106, 109, 112, 115, 118, 119, 154, 162, 
	169, 177, 181, 184, 194, 202, 208, 213, 
	216, 228, 237, 239, 242, 248, 253, 256, 
	268, 278, 287, 289, 296, 306, 314, 320, 
	329, 338
};

static const char _query_indicies[] = {
	1, 1, 1, 1, 1, 0, 2, 2, 
	2, 2, 2, 0, 4, 5, 3, 3, 
	4, 5, 7, 3, 4, 5, 8, 3, 
	9, 9, 9, 9, 9, 0, 11, 10, 
	10, 10, 10, 10, 9, 12, 10, 14, 
	13, 15, 16, 13, 16, 13, 17, 0, 
	18, 0, 19, 0, 21, 22, 20, 22, 
	0, 23, 23, 23, 23, 23, 0, 25, 
	25, 26, 25, 26, 24, 27, 27, 24, 
	28, 28, 24, 29, 29, 24, 30, 30, 
	24, 31, 31, 24, 32, 32, 24, 33, 
	33, 24, 34, 34, 24, 24, 35, 36, 
	35, 37, 37, 24, 38, 38, 24, 39, 
	39, 24, 40, 40, 24, 33, 33, 24, 
	41, 43, 42, 44, 43, 42, 42, 46, 
	48, 49, 50, 51, 52, 53, 54, 55, 
	56, 58, 59, 60, 61, 62, 63, 64, 
	65, 66, 62, 67, 68, 69, 70, 71, 
	72, 45, 45, 46, 45, 47, 57, 47, 
	47, 1, 73, 74, 0, 0, 0, 0, 
	0, 1, 76, 75, 75, 75, 75, 75, 
	2, 73, 76, 77, 77, 77, 77, 77, 
	2, 75, 5, 78, 3, 4, 5, 3, 
	81, 82, 11, 80, 80, 83, 80, 80, 
	80, 9, 85, 11, 84, 84, 84, 84, 
	84, 9, 85, 86, 87, 87, 12, 84, 
	85, 87, 87, 14, 84, 85, 16, 84, 
	85, 86, 88, 11, 84, 88, 84, 83, 
	84, 84, 84, 9, 85, 15, 11, 84, 
	84, 84, 84, 84, 9, 89, 75, 89, 
	91, 90, 73, 93, 94, 94, 91, 92, 
	73, 94, 94, 19, 92, 73, 22, 92, 
	73, 93, 96, 74, 95, 96, 95, 57, 
	95, 95, 95, 1, 73, 21, 74, 97, 
	97, 98, 97, 97, 97, 1, 73, 74, 
	92, 92, 98, 92, 92, 92, 1, 99, 
	75, 100, 0, 0, 0, 0, 0, 23, 
	73, 101, 74, 97, 101, 97, 97, 97, 
	97, 1, 103, 25, 25, 26, 25, 26, 
	103, 102, 1, 1, 1, 1, 1, 75, 
	73, 74, 97, 104, 97, 97, 97, 97, 
	1, 73, 74, 97, 105, 97, 97, 97, 
	97, 1, 106, 73, 74, 97, 97, 97, 
	97, 97, 1, 0
};

static const char _query_trans_targs[] = {
	37, 38, 40, 2, 37, 3, 37, 5, 
	42, 44, 37, 6, 45, 37, 46, 11, 
	47, 13, 37, 53, 37, 16, 54, 59, 
	37, 19, 29, 20, 21, 22, 23, 24, 
	25, 26, 27, 28, 37, 30, 31, 32, 
	33, 37, 35, 36, 37, 37, 37, 37, 
	37, 39, 37, 41, 37, 37, 43, 50, 
	51, 55, 37, 37, 58, 59, 60, 61, 
	62, 37, 38, 63, 65, 37, 37, 37, 
	37, 37, 0, 37, 1, 37, 4, 37, 
	37, 7, 8, 48, 37, 37, 9, 10, 
	49, 12, 37, 52, 37, 14, 15, 37, 
	56, 37, 57, 37, 17, 38, 37, 18, 
	64, 38, 34
};

static const char _query_trans_actions[] = {
	81, 110, 92, 0, 43, 0, 75, 0, 
	98, 113, 71, 0, 5, 79, 5, 0, 
	0, 0, 9, 86, 69, 0, 0, 89, 
	73, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 47, 0, 0, 0, 
	0, 77, 0, 0, 45, 37, 33, 35, 
	11, 107, 29, 107, 15, 17, 104, 107, 
	101, 83, 23, 25, 0, 107, 110, 5, 
	0, 31, 107, 110, 110, 19, 13, 21, 
	27, 39, 0, 63, 0, 53, 0, 55, 
	59, 0, 0, 113, 67, 41, 0, 0, 
	113, 0, 57, 86, 51, 0, 0, 49, 
	110, 65, 86, 7, 0, 95, 61, 0, 
	110, 98, 0
};

static const char _query_to_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 1, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0
};

static const char _query_from_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 3, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0
};

static const short _query_eof_trans[] = {
	1, 1, 1, 1, 7, 7, 1, 11, 
	11, 14, 14, 14, 1, 1, 1, 21, 
	1, 1, 25, 25, 25, 25, 25, 25, 
	25, 25, 25, 25, 25, 25, 25, 25, 
	25, 25, 42, 42, 42, 0, 1, 76, 
	78, 76, 80, 81, 85, 85, 85, 85, 
	85, 85, 76, 91, 93, 93, 93, 96, 
	98, 93, 76, 1, 98, 103, 76, 98, 
	98, 98
};

static const int query_start = 37;
static const int query_first_final = 37;
static const int query_error = -1;

static const int query_en_main = 37;


/* #line 335 "lexer.rl" */

QueryNode *RSQuery_ParseRaw_v2(QueryParseCtx *q) {
  void *pParser = RSQuery_ParseAlloc_v2(rm_malloc);

  
  int cs, act;
  const char* ts = q->raw;
  const char* te = q->raw + q->len;
  
/* #line 290 "lexer.c" */
	{
	cs = query_start;
	ts = 0;
	te = 0;
	act = 0;
	}

/* #line 344 "lexer.rl" */
  QueryToken tok = {.len = 0, .pos = 0, .s = 0};
  
  //parseCtx ctx = {.root = NULL, .ok = 1, .errorMsg = NULL, .q = q};
  const char* p = q->raw;
  const char* pe = q->raw + q->len;
  const char* eof = pe;
  
  
/* #line 307 "lexer.c" */
	{
	int _klen;
	unsigned int _trans;
	const char *_acts;
	unsigned int _nacts;
	const char *_keys;

	if ( p == pe )
		goto _test_eof;
_resume:
	_acts = _query_actions + _query_from_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 1:
/* #line 1 "NONE" */
	{ts = p;}
	break;
/* #line 326 "lexer.c" */
		}
	}

	_keys = _query_trans_keys + _query_key_offsets[cs];
	_trans = _query_index_offsets[cs];

	_klen = _query_single_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + _klen - 1;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + ((_upper-_lower) >> 1);
			if ( (*p) < *_mid )
				_upper = _mid - 1;
			else if ( (*p) > *_mid )
				_lower = _mid + 1;
			else {
				_trans += (unsigned int)(_mid - _keys);
				goto _match;
			}
		}
		_keys += _klen;
		_trans += _klen;
	}

	_klen = _query_range_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + (_klen<<1) - 2;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + (((_upper-_lower) >> 1) & ~1);
			if ( (*p) < _mid[0] )
				_upper = _mid - 2;
			else if ( (*p) > _mid[1] )
				_lower = _mid + 2;
			else {
				_trans += (unsigned int)((_mid - _keys)>>1);
				goto _match;
			}
		}
		_trans += _klen;
	}

_match:
	_trans = _query_indicies[_trans];
_eof_trans:
	cs = _query_trans_targs[_trans];

	if ( _query_trans_actions[_trans] == 0 )
		goto _again;

	_acts = _query_actions + _query_trans_actions[_trans];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 )
	{
		switch ( *_acts++ )
		{
	case 2:
/* #line 1 "NONE" */
	{te = p+1;}
	break;
	case 3:
/* #line 67 "lexer.rl" */
	{act = 1;}
	break;
	case 4:
/* #line 78 "lexer.rl" */
	{act = 2;}
	break;
	case 5:
/* #line 89 "lexer.rl" */
	{act = 3;}
	break;
	case 6:
/* #line 98 "lexer.rl" */
	{act = 4;}
	break;
	case 7:
/* #line 116 "lexer.rl" */
	{act = 6;}
	break;
	case 8:
/* #line 125 "lexer.rl" */
	{act = 7;}
	break;
	case 9:
/* #line 194 "lexer.rl" */
	{act = 16;}
	break;
	case 10:
/* #line 208 "lexer.rl" */
	{act = 18;}
	break;
	case 11:
/* #line 237 "lexer.rl" */
	{act = 23;}
	break;
	case 12:
/* #line 240 "lexer.rl" */
	{act = 25;}
	break;
	case 13:
/* #line 264 "lexer.rl" */
	{act = 27;}
	break;
	case 14:
/* #line 107 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ARROW, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 15:
/* #line 125 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 16:
/* #line 136 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, QUOTE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 17:
/* #line 143 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, OR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 18:
/* #line 150 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 19:
/* #line 158 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 20:
/* #line 165 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 21:
/* #line 172 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 22:
/* #line 179 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v2(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 23:
/* #line 186 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v2(pParser, SEMICOLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 24:
/* #line 201 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, TILDE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 25:
/* #line 215 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, PERCENT, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 26:
/* #line 229 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RSQB, tok, q);   
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    } 
  }}
	break;
	case 27:
/* #line 236 "lexer.rl" */
	{te = p+1;}
	break;
	case 28:
/* #line 237 "lexer.rl" */
	{te = p+1;}
	break;
	case 29:
/* #line 238 "lexer.rl" */
	{te = p+1;}
	break;
	case 30:
/* #line 250 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*ts == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, PREFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 31:
/* #line 278 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, CONTAINS, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 32:
/* #line 293 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    RSQuery_Parse_v2(pParser, VERBATIM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 33:
/* #line 306 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_WILDCARD : QT_WILDCARD;
    tok.pos = ts-q->raw + 2;
    tok.len = te - (ts + 3 + is_attr);
    tok.s = ts + 2 + is_attr;
    tok.numval = 0;
    RSQuery_Parse_v2(pParser, WILDCARD, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 34:
/* #line 319 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw + 2;
    tok.len = te - ts - 2;
    tok.s = ts + 1;
    tok.numval = 0;
    RSQuery_Parse_v2(pParser, NAMED_PREDICATE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 35:
/* #line 67 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 36:
/* #line 78 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 37:
/* #line 98 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 38:
/* #line 125 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 39:
/* #line 194 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 40:
/* #line 208 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 41:
/* #line 222 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LSQB, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }  
  }}
	break;
	case 42:
/* #line 237 "lexer.rl" */
	{te = p;p--;}
	break;
	case 43:
/* #line 240 "lexer.rl" */
	{te = p;p--;{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 44:
/* #line 264 "lexer.rl" */
	{te = p;p--;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 45:
/* #line 78 "lexer.rl" */
	{{p = ((te))-1;}{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 46:
/* #line 208 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 47:
/* #line 222 "lexer.rl" */
	{{p = ((te))-1;}{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LSQB, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }  
  }}
	break;
	case 48:
/* #line 237 "lexer.rl" */
	{{p = ((te))-1;}}
	break;
	case 49:
/* #line 240 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 50:
/* #line 264 "lexer.rl" */
	{{p = ((te))-1;}{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 51:
/* #line 1 "NONE" */
	{	switch( act ) {
	case 1:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 2:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 3:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, MODIFIER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 4:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 6:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts;
    RSQuery_Parse_v2(pParser, AS_T, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 7:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 16:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 18:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 25:
	{{p = ((te))-1;}
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 27:
	{{p = ((te))-1;}
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	default:
	{{p = ((te))-1;}}
	break;
	}
	}
	break;
/* #line 975 "lexer.c" */
		}
	}

_again:
	_acts = _query_actions + _query_to_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 0:
/* #line 1 "NONE" */
	{ts = 0;}
	break;
/* #line 988 "lexer.c" */
		}
	}

	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	if ( _query_eof_trans[cs] > 0 ) {
		_trans = _query_eof_trans[cs] - 1;
		goto _eof_trans;
	}
	}

	_out: {}
	}

/* #line 352 "lexer.rl" */
  
  if (QPCTX_ISOK(q)) {
    RSQuery_Parse_v2(pParser, 0, tok, q);
  }
  RSQuery_ParseFree_v2(pParser, rm_free);
  if (!QPCTX_ISOK(q) && q->root) {
    QueryNode_Free(q->root);
    q->root = NULL;
  }
  return q->root;
}

