
/* #line 1 "lexer.rl" */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>

#include "../parse.h"
#include "parser.h"
#include "../../query_node.h"
#include "../../stopwords.h"

/* forward declarations of stuff generated by lemon */

#define RSQuery_Parse_v2 RSQueryParser_v2_ // weird Lemon quirk.. oh well..
#define RSQuery_ParseAlloc_v2 RSQueryParser_v2_Alloc
#define RSQuery_ParseFree_v2 RSQueryParser_v2_Free

void RSQuery_Parse_v2(void *yyp, int yymajor, QueryToken yyminor, QueryParseCtx *ctx);
void *RSQuery_ParseAlloc_v2(void *(*mallocProc)(size_t));
void RSQuery_ParseFree_v2(void *p, void (*freeProc)(void *));


/* #line 335 "lexer.rl" */



/* #line 30 "lexer.c" */
static const char _query_actions[] = {
	0, 1, 0, 1, 1, 1, 2, 1, 
	16, 1, 17, 1, 18, 1, 19, 1, 
	20, 1, 21, 1, 22, 1, 23, 1, 
	24, 1, 25, 1, 26, 1, 27, 1, 
	28, 1, 29, 1, 30, 1, 31, 1, 
	32, 1, 33, 1, 34, 1, 35, 1, 
	36, 1, 37, 1, 38, 1, 39, 1, 
	40, 1, 41, 1, 42, 1, 43, 1, 
	44, 1, 45, 1, 46, 1, 47, 1, 
	48, 1, 49, 1, 50, 1, 51, 1, 
	52, 2, 2, 3, 2, 2, 4, 2, 
	2, 5, 2, 2, 6, 2, 2, 7, 
	2, 2, 8, 2, 2, 9, 2, 2, 
	10, 2, 2, 11, 2, 2, 12, 2, 
	2, 13, 2, 2, 14, 2, 2, 15
	
};

static const short _query_key_offsets[] = {
	0, 10, 20, 22, 22, 25, 28, 31, 
	34, 35, 38, 41, 44, 47, 50, 54, 
	58, 62, 66, 69, 73, 77, 81, 85, 
	89, 92, 95, 105, 115, 117, 119, 122, 
	124, 125, 126, 128, 131, 133, 143, 145, 
	147, 147, 190, 201, 211, 222, 227, 230, 
	233, 236, 237, 240, 243, 246, 249, 251, 
	265, 276, 282, 287, 290, 306, 318, 319, 
	322, 328, 333, 336, 352, 366, 379, 380, 
	390, 403, 417, 431, 445, 459, 473, 484, 
	498, 512, 526, 540, 554, 564, 576, 588
};

static const char _query_trans_keys[] = {
	9, 13, 32, 47, 58, 64, 91, 96, 
	123, 126, 9, 13, 32, 47, 58, 64, 
	91, 96, 123, 126, 39, 92, 39, 67, 
	99, 39, 84, 116, 39, 79, 111, 39, 
	82, 114, 95, 39, 82, 114, 39, 65, 
	97, 39, 78, 110, 39, 71, 103, 39, 
	69, 101, 39, 67, 92, 99, 39, 84, 
	92, 116, 39, 79, 92, 111, 39, 82, 
	92, 114, 39, 92, 95, 39, 82, 92, 
	114, 39, 65, 92, 97, 39, 78, 92, 
	110, 39, 71, 92, 103, 39, 69, 92, 
	101, 39, 92, 110, 39, 92, 102, 9, 
	13, 32, 47, 58, 64, 91, 96, 123, 
	126, 92, 96, 0, 47, 58, 64, 91, 
	94, 123, 127, 48, 57, 48, 57, 45, 
	48, 57, 48, 57, 110, 102, 48, 57, 
	45, 48, 57, 48, 57, 9, 13, 32, 
	47, 58, 64, 91, 96, 123, 126, 39, 
	92, 39, 92, 32, 34, 36, 37, 39, 
	40, 41, 42, 43, 45, 58, 59, 61, 
	64, 65, 86, 91, 92, 93, 95, 97, 
	105, 118, 119, 123, 124, 125, 126, 127, 
	0, 8, 9, 13, 14, 31, 33, 47, 
	48, 57, 60, 63, 94, 96, 42, 92, 
	96, 0, 47, 58, 64, 91, 94, 123, 
	127, 92, 96, 0, 47, 58, 64, 91, 
	94, 123, 127, 42, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 39, 69, 
	92, 101, 105, 39, 84, 116, 39, 79, 
	111, 39, 82, 114, 95, 39, 65, 97, 
	39, 78, 110, 39, 71, 103, 39, 69, 
	101, 39, 92, 36, 45, 92, 96, 0, 
	47, 48, 57, 58, 64, 91, 94, 123, 
	127, 42, 92, 96, 0, 47, 58, 64, 
	91, 94, 123, 127, 42, 46, 69, 101, 
	48, 57, 42, 69, 101, 48, 57, 42, 
	48, 57, 42, 46, 69, 92, 96, 101, 
	0, 47, 48, 57, 58, 64, 91, 94, 
	123, 127, 42, 45, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 105, 105, 
	48, 57, 42, 46, 69, 101, 48, 57, 
	42, 69, 101, 48, 57, 42, 48, 57, 
	42, 46, 69, 92, 96, 101, 0, 47, 
	48, 57, 58, 64, 91, 94, 123, 127, 
	42, 45, 92, 96, 0, 47, 48, 57, 
	58, 64, 91, 94, 123, 127, 42, 92, 
	96, 0, 47, 48, 57, 58, 64, 91, 
	94, 123, 127, 62, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 42, 83, 
	92, 96, 115, 0, 47, 58, 64, 91, 
	94, 123, 127, 39, 42, 69, 92, 96, 
	101, 0, 47, 58, 64, 91, 94, 123, 
	127, 39, 42, 67, 92, 96, 99, 0, 
	47, 58, 64, 91, 94, 123, 127, 39, 
	42, 84, 92, 96, 116, 0, 47, 58, 
	64, 91, 94, 123, 127, 39, 42, 79, 
	92, 96, 111, 0, 47, 58, 64, 91, 
	94, 123, 127, 39, 42, 82, 92, 96, 
	114, 0, 47, 58, 64, 91, 94, 123, 
	127, 42, 92, 95, 0, 47, 58, 64, 
	91, 96, 123, 127, 39, 42, 82, 92, 
	96, 114, 0, 47, 58, 64, 91, 94, 
	123, 127, 39, 42, 65, 92, 96, 97, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	39, 42, 78, 92, 96, 110, 0, 47, 
	58, 64, 91, 94, 123, 127, 39, 42, 
	71, 92, 96, 103, 0, 47, 58, 64, 
	91, 94, 123, 127, 39, 42, 69, 92, 
	96, 101, 0, 47, 58, 64, 91, 94, 
	123, 127, 9, 13, 32, 47, 58, 64, 
	91, 96, 123, 126, 42, 92, 96, 110, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	42, 92, 96, 102, 0, 47, 58, 64, 
	91, 94, 123, 127, 39, 42, 92, 96, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	0
};

static const char _query_single_lengths[] = {
	0, 0, 2, 0, 3, 3, 3, 3, 
	1, 3, 3, 3, 3, 3, 4, 4, 
	4, 4, 3, 4, 4, 4, 4, 4, 
	3, 3, 0, 2, 0, 0, 1, 0, 
	1, 1, 0, 1, 0, 0, 2, 2, 
	0, 29, 3, 2, 3, 5, 3, 3, 
	3, 1, 3, 3, 3, 3, 2, 4, 
	3, 4, 3, 1, 6, 4, 1, 1, 
	4, 3, 1, 6, 4, 3, 1, 2, 
	5, 6, 6, 6, 6, 6, 3, 6, 
	6, 6, 6, 6, 0, 4, 4, 4
};

static const char _query_range_lengths[] = {
	5, 5, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 5, 4, 1, 1, 1, 1, 
	0, 0, 1, 1, 1, 5, 0, 0, 
	0, 7, 4, 4, 4, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 5, 
	4, 1, 1, 1, 5, 4, 0, 1, 
	1, 1, 1, 5, 5, 5, 0, 4, 
	4, 4, 4, 4, 4, 4, 4, 4, 
	4, 4, 4, 4, 5, 4, 4, 4
};

static const short _query_index_offsets[] = {
	0, 6, 12, 15, 16, 20, 24, 28, 
	32, 34, 38, 42, 46, 50, 54, 59, 
	64, 69, 74, 78, 83, 88, 93, 98, 
	103, 107, 111, 117, 124, 126, 128, 131, 
	133, 135, 137, 139, 142, 144, 150, 153, 
	156, 157, 194, 202, 209, 217, 223, 227, 
	231, 235, 237, 241, 245, 249, 253, 256, 
	266, 274, 280, 285, 288, 300, 309, 311, 
	314, 320, 325, 328, 340, 350, 359, 361, 
	368, 378, 389, 400, 411, 422, 433, 441, 
	452, 463, 474, 485, 496, 502, 511, 520
};

static const unsigned char _query_indicies[] = {
	1, 1, 1, 1, 1, 0, 2, 2, 
	2, 2, 2, 0, 4, 5, 3, 3, 
	6, 6, 6, 0, 7, 7, 7, 0, 
	8, 8, 8, 0, 9, 9, 9, 0, 
	10, 0, 11, 11, 11, 0, 12, 12, 
	12, 0, 13, 13, 13, 0, 14, 14, 
	14, 0, 15, 15, 15, 0, 17, 18, 
	5, 18, 3, 19, 20, 5, 20, 3, 
	21, 22, 5, 22, 3, 23, 24, 5, 
	24, 3, 4, 5, 25, 3, 26, 27, 
	5, 27, 3, 28, 29, 5, 29, 3, 
	30, 31, 5, 31, 3, 32, 33, 5, 
	33, 3, 15, 34, 5, 34, 3, 4, 
	5, 35, 3, 4, 5, 36, 3, 37, 
	37, 37, 37, 37, 0, 39, 38, 38, 
	38, 38, 38, 37, 40, 38, 42, 41, 
	43, 44, 41, 44, 41, 45, 0, 46, 
	0, 47, 0, 49, 50, 48, 50, 0, 
	51, 51, 51, 51, 51, 0, 52, 54, 
	53, 55, 54, 53, 53, 57, 59, 60, 
	61, 62, 63, 64, 65, 66, 67, 69, 
	70, 71, 72, 73, 74, 75, 76, 77, 
	78, 73, 79, 74, 80, 81, 82, 83, 
	84, 56, 56, 57, 56, 58, 68, 58, 
	58, 1, 85, 86, 0, 0, 0, 0, 
	0, 1, 88, 87, 87, 87, 87, 87, 
	2, 85, 88, 89, 89, 89, 89, 89, 
	2, 90, 91, 5, 91, 92, 3, 7, 
	7, 7, 93, 8, 8, 8, 93, 9, 
	9, 9, 93, 10, 93, 12, 12, 12, 
	93, 13, 13, 13, 93, 14, 14, 14, 
	93, 15, 15, 15, 93, 4, 5, 3, 
	95, 96, 39, 94, 94, 97, 94, 94, 
	94, 37, 99, 39, 98, 98, 98, 98, 
	98, 37, 99, 100, 101, 101, 40, 98, 
	99, 101, 101, 42, 98, 99, 44, 98, 
	99, 100, 102, 39, 98, 102, 98, 97, 
	98, 98, 98, 37, 99, 43, 39, 98, 
	98, 98, 98, 98, 37, 103, 87, 103, 
	105, 104, 85, 107, 108, 108, 105, 106, 
	85, 108, 108, 47, 106, 85, 50, 106, 
	85, 107, 110, 86, 109, 110, 109, 68, 
	109, 109, 109, 1, 85, 49, 86, 111, 
	111, 112, 111, 111, 111, 1, 85, 86, 
	106, 106, 112, 106, 106, 106, 1, 113, 
	87, 114, 0, 0, 0, 0, 0, 51, 
	85, 115, 86, 111, 115, 111, 111, 111, 
	111, 1, 90, 85, 116, 86, 111, 116, 
	111, 111, 111, 111, 1, 6, 85, 117, 
	86, 111, 117, 111, 111, 111, 111, 1, 
	7, 85, 118, 86, 111, 118, 111, 111, 
	111, 111, 1, 8, 85, 119, 86, 111, 
	119, 111, 111, 111, 111, 1, 9, 85, 
	120, 86, 111, 120, 111, 111, 111, 111, 
	1, 85, 86, 121, 111, 111, 111, 111, 
	1, 11, 85, 122, 86, 111, 122, 111, 
	111, 111, 111, 1, 12, 85, 123, 86, 
	111, 123, 111, 111, 111, 111, 1, 13, 
	85, 124, 86, 111, 124, 111, 111, 111, 
	111, 1, 14, 85, 125, 86, 111, 125, 
	111, 111, 111, 111, 1, 15, 85, 126, 
	86, 111, 126, 111, 111, 111, 111, 1, 
	1, 1, 1, 1, 1, 87, 85, 86, 
	111, 127, 111, 111, 111, 111, 1, 85, 
	86, 111, 128, 111, 111, 111, 111, 1, 
	129, 85, 86, 111, 111, 111, 111, 111, 
	1, 0
};

static const char _query_trans_targs[] = {
	41, 42, 44, 2, 41, 3, 5, 6, 
	7, 8, 9, 10, 11, 12, 13, 41, 
	41, 46, 15, 47, 16, 48, 17, 49, 
	18, 19, 50, 20, 51, 21, 52, 22, 
	53, 23, 54, 25, 54, 56, 41, 26, 
	57, 41, 58, 31, 59, 33, 41, 65, 
	41, 36, 66, 71, 41, 39, 40, 41, 
	41, 41, 41, 41, 43, 41, 45, 41, 
	41, 55, 62, 63, 67, 41, 41, 70, 
	71, 72, 73, 41, 84, 41, 42, 85, 
	87, 41, 41, 41, 41, 41, 0, 41, 
	1, 41, 4, 14, 24, 41, 41, 27, 
	28, 60, 41, 41, 29, 30, 61, 32, 
	41, 64, 41, 34, 35, 41, 68, 41, 
	69, 41, 37, 42, 74, 75, 76, 77, 
	78, 79, 80, 81, 82, 83, 42, 86, 
	42, 38
};

static const char _query_trans_actions[] = {
	79, 111, 90, 0, 47, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 9, 
	73, 117, 0, 117, 0, 117, 0, 117, 
	0, 0, 117, 0, 117, 0, 117, 0, 
	0, 0, 96, 0, 99, 114, 71, 0, 
	5, 77, 5, 0, 0, 0, 11, 84, 
	69, 0, 0, 87, 75, 0, 0, 49, 
	41, 37, 39, 13, 108, 31, 108, 17, 
	19, 105, 108, 102, 81, 25, 27, 0, 
	108, 111, 111, 33, 0, 35, 108, 111, 
	111, 21, 15, 23, 29, 43, 0, 61, 
	0, 55, 0, 0, 0, 67, 59, 0, 
	0, 114, 65, 45, 0, 0, 114, 0, 
	57, 84, 53, 0, 0, 51, 111, 63, 
	84, 7, 0, 93, 111, 111, 111, 111, 
	111, 111, 111, 111, 111, 111, 96, 111, 
	99, 0
};

static const char _query_to_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 1, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0
};

static const char _query_from_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 3, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0
};

static const short _query_eof_trans[] = {
	1, 1, 1, 1, 1, 1, 1, 1, 
	1, 1, 1, 1, 1, 1, 17, 17, 
	17, 17, 17, 17, 17, 17, 17, 17, 
	17, 17, 1, 39, 39, 42, 42, 42, 
	1, 1, 1, 49, 1, 1, 53, 53, 
	53, 0, 1, 88, 90, 88, 94, 94, 
	94, 94, 94, 94, 94, 94, 1, 95, 
	99, 99, 99, 99, 99, 99, 88, 105, 
	107, 107, 107, 110, 112, 107, 88, 1, 
	112, 112, 112, 112, 112, 112, 112, 112, 
	112, 112, 112, 112, 88, 112, 112, 112
};

static const int query_start = 41;
static const int query_first_final = 41;
static const int query_error = -1;

static const int query_en_main = 41;


/* #line 338 "lexer.rl" */

QueryNode *RSQuery_ParseRaw_v2(QueryParseCtx *q) {
  void *pParser = RSQuery_ParseAlloc_v2(rm_malloc);

  
  int cs, act;
  const char* ts = q->raw;
  const char* te = q->raw + q->len;
  
/* #line 354 "lexer.c" */
	{
	cs = query_start;
	ts = 0;
	te = 0;
	act = 0;
	}

/* #line 347 "lexer.rl" */
  QueryToken tok = {.len = 0, .pos = 0, .s = 0};
  
  //parseCtx ctx = {.root = NULL, .ok = 1, .errorMsg = NULL, .q = q};
  const char* p = q->raw;
  const char* pe = q->raw + q->len;
  const char* eof = pe;
  
  
/* #line 371 "lexer.c" */
	{
	int _klen;
	unsigned int _trans;
	const char *_acts;
	unsigned int _nacts;
	const char *_keys;

	if ( p == pe )
		goto _test_eof;
_resume:
	_acts = _query_actions + _query_from_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 1:
/* #line 1 "NONE" */
	{ts = p;}
	break;
/* #line 390 "lexer.c" */
		}
	}

	_keys = _query_trans_keys + _query_key_offsets[cs];
	_trans = _query_index_offsets[cs];

	_klen = _query_single_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + _klen - 1;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + ((_upper-_lower) >> 1);
			if ( (*p) < *_mid )
				_upper = _mid - 1;
			else if ( (*p) > *_mid )
				_lower = _mid + 1;
			else {
				_trans += (unsigned int)(_mid - _keys);
				goto _match;
			}
		}
		_keys += _klen;
		_trans += _klen;
	}

	_klen = _query_range_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + (_klen<<1) - 2;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + (((_upper-_lower) >> 1) & ~1);
			if ( (*p) < _mid[0] )
				_upper = _mid - 2;
			else if ( (*p) > _mid[1] )
				_lower = _mid + 2;
			else {
				_trans += (unsigned int)((_mid - _keys)>>1);
				goto _match;
			}
		}
		_trans += _klen;
	}

_match:
	_trans = _query_indicies[_trans];
_eof_trans:
	cs = _query_trans_targs[_trans];

	if ( _query_trans_actions[_trans] == 0 )
		goto _again;

	_acts = _query_actions + _query_trans_actions[_trans];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 )
	{
		switch ( *_acts++ )
		{
	case 2:
/* #line 1 "NONE" */
	{te = p+1;}
	break;
	case 3:
/* #line 61 "lexer.rl" */
	{act = 1;}
	break;
	case 4:
/* #line 72 "lexer.rl" */
	{act = 2;}
	break;
	case 5:
/* #line 83 "lexer.rl" */
	{act = 3;}
	break;
	case 6:
/* #line 92 "lexer.rl" */
	{act = 4;}
	break;
	case 7:
/* #line 110 "lexer.rl" */
	{act = 6;}
	break;
	case 8:
/* #line 123 "lexer.rl" */
	{act = 7;}
	break;
	case 9:
/* #line 136 "lexer.rl" */
	{act = 8;}
	break;
	case 10:
/* #line 205 "lexer.rl" */
	{act = 17;}
	break;
	case 11:
/* #line 219 "lexer.rl" */
	{act = 19;}
	break;
	case 12:
/* #line 248 "lexer.rl" */
	{act = 24;}
	break;
	case 13:
/* #line 251 "lexer.rl" */
	{act = 26;}
	break;
	case 14:
/* #line 279 "lexer.rl" */
	{act = 28;}
	break;
	case 15:
/* #line 308 "lexer.rl" */
	{act = 30;}
	break;
	case 16:
/* #line 101 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ARROW, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 17:
/* #line 123 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts;
    if (StopWordList_Contains(q->opts->stopwords, "vector_range", strlen("vector_range"))) {
      RSQuery_Parse_v2(pParser, VECTOR_RANGE_S, tok, q);
    } else {
      RSQuery_Parse_v2(pParser, VECTOR_RANGE_T, tok, q);
    }
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 18:
/* #line 136 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 19:
/* #line 147 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, QUOTE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 20:
/* #line 154 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, OR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 21:
/* #line 161 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 22:
/* #line 169 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 23:
/* #line 176 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 24:
/* #line 183 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 25:
/* #line 190 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v2(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 26:
/* #line 197 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v2(pParser, SEMICOLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 27:
/* #line 212 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, TILDE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 28:
/* #line 226 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, PERCENT, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 29:
/* #line 233 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LSQB, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }  
  }}
	break;
	case 30:
/* #line 240 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RSQB, tok, q);   
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    } 
  }}
	break;
	case 31:
/* #line 247 "lexer.rl" */
	{te = p+1;}
	break;
	case 32:
/* #line 248 "lexer.rl" */
	{te = p+1;}
	break;
	case 33:
/* #line 249 "lexer.rl" */
	{te = p+1;}
	break;
	case 34:
/* #line 265 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*ts == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, PREFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 35:
/* #line 293 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, CONTAINS, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 36:
/* #line 308 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    RSQuery_Parse_v2(pParser, VERBATIM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 37:
/* #line 321 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_WILDCARD : QT_WILDCARD;
    tok.pos = ts-q->raw + 2;
    tok.len = te - (ts + 3 + is_attr);
    tok.s = ts + 2 + is_attr;
    tok.numval = 0;
    RSQuery_Parse_v2(pParser, WILDCARD, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 38:
/* #line 61 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 39:
/* #line 72 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 40:
/* #line 92 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 41:
/* #line 205 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 42:
/* #line 219 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 43:
/* #line 248 "lexer.rl" */
	{te = p;p--;}
	break;
	case 44:
/* #line 251 "lexer.rl" */
	{te = p;p--;{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    if (!StopWordList_Contains(q->opts->stopwords, tok.s, tok.len)) {
      RSQuery_Parse_v2(pParser, TERM, tok, q);
    } else {
      RSQuery_Parse_v2(pParser, STOPWORD, tok, q);
    }
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 45:
/* #line 279 "lexer.rl" */
	{te = p;p--;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 46:
/* #line 308 "lexer.rl" */
	{te = p;p--;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    RSQuery_Parse_v2(pParser, VERBATIM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 47:
/* #line 72 "lexer.rl" */
	{{p = ((te))-1;}{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 48:
/* #line 219 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 49:
/* #line 248 "lexer.rl" */
	{{p = ((te))-1;}}
	break;
	case 50:
/* #line 251 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    if (!StopWordList_Contains(q->opts->stopwords, tok.s, tok.len)) {
      RSQuery_Parse_v2(pParser, TERM, tok, q);
    } else {
      RSQuery_Parse_v2(pParser, STOPWORD, tok, q);
    }
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 51:
/* #line 279 "lexer.rl" */
	{{p = ((te))-1;}{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 52:
/* #line 1 "NONE" */
	{	switch( act ) {
	case 1:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 2:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 3:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, MODIFIER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 4:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 6:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts;
    if (StopWordList_Contains(q->opts->stopwords, "as", 2)) {
      RSQuery_Parse_v2(pParser, AS_S, tok, q);
    } else {
      RSQuery_Parse_v2(pParser, AS_T, tok, q);
    }
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 7:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts;
    if (StopWordList_Contains(q->opts->stopwords, "vector_range", strlen("vector_range"))) {
      RSQuery_Parse_v2(pParser, VECTOR_RANGE_S, tok, q);
    } else {
      RSQuery_Parse_v2(pParser, VECTOR_RANGE_T, tok, q);
    }
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 8:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 17:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 19:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 26:
	{{p = ((te))-1;}
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    if (!StopWordList_Contains(q->opts->stopwords, tok.s, tok.len)) {
      RSQuery_Parse_v2(pParser, TERM, tok, q);
    } else {
      RSQuery_Parse_v2(pParser, STOPWORD, tok, q);
    }
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 28:
	{{p = ((te))-1;}
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 30:
	{{p = ((te))-1;}
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    RSQuery_Parse_v2(pParser, VERBATIM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	default:
	{{p = ((te))-1;}}
	break;
	}
	}
	break;
/* #line 1087 "lexer.c" */
		}
	}

_again:
	_acts = _query_actions + _query_to_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 0:
/* #line 1 "NONE" */
	{ts = 0;}
	break;
/* #line 1100 "lexer.c" */
		}
	}

	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	if ( _query_eof_trans[cs] > 0 ) {
		_trans = _query_eof_trans[cs] - 1;
		goto _eof_trans;
	}
	}

	_out: {}
	}

/* #line 355 "lexer.rl" */
  
  if (QPCTX_ISOK(q)) {
    RSQuery_Parse_v2(pParser, 0, tok, q);
  }
  RSQuery_ParseFree_v2(pParser, rm_free);
  if (!QPCTX_ISOK(q) && q->root) {
    QueryNode_Free(q->root);
    q->root = NULL;
  }
  return q->root;
}

