#define LOWEST                           1
#define TEXTEXPR                         2
#define ORX                              3
#define OR                               4
#define ISMISSING                        5
#define MODIFIER                         6
#define MODIFIER_EQUAL                   7
#define RP                               8
#define RB                               9
#define RSQB                            10
#define EXACT                           11
#define TERM                            12
#define QUOTE                           13
#define LP                              14
#define LB                              15
#define LSQB                            16
#define TILDE                           17
#define MINUS                           18
#define AND                             19
#define ARROW                           20
#define COLON                           21
#define NUMBER                          22
#define SIZE                            23
#define STAR                            24
#define TAGLIST                         25
#define TERMLIST                        26
#define PREFIX                          27
#define SUFFIX                          28
#define CONTAINS                        29
#define PERCENT                         30
#define ATTRIBUTE                       31
#define VERBATIM                        32
#define WILDCARD                        33
#define AS_T                            34
#define SEMICOLON                       35
