#define LOWEST                           1
#define TEXTEXPR                         2
#define ORX                              3
#define OR                               4
#define MODIFIER                         5
#define RP                               6
#define RB                               7
#define RSQB                             8
#define TERM                             9
#define QUOTE                           10
#define LP                              11
#define LB                              12
#define LSQB                            13
#define TILDE                           14
#define MINUS                           15
#define AND                             16
#define ARROW                           17
#define COLON                           18
#define NUMBER                          19
#define SIZE                            20
#define STOPWORD                        21
#define STAR                            22
#define TAGLIST                         23
#define TERMLIST                        24
#define PREFIX                          25
#define PERCENT                         26
#define ATTRIBUTE                       27
#define AS_S                            28
#define AS_T                            29
#define SEMICOLON                       30
