#define LOWEST                           1
#define TEXTEXPR                         2
#define ORX                              3
#define OR                               4
#define ISMISSING                        5
#define MODIFIER                         6
#define RP                               7
#define RB                               8
#define RSQB                             9
#define EXACT                           10
#define TERM                            11
#define QUOTE                           12
#define LP                              13
#define LB                              14
#define LSQB                            15
#define TILDE                           16
#define MINUS                           17
#define AND                             18
#define ARROW                           19
#define COLON                           20
#define NUMBER                          21
#define SIZE                            22
#define STAR                            23
#define TAGLIST                         24
#define TERMLIST                        25
#define PREFIX                          26
#define SUFFIX                          27
#define CONTAINS                        28
#define PERCENT                         29
#define ATTRIBUTE                       30
#define VERBATIM                        31
#define WILDCARD                        32
#define AS_T                            33
#define SEMICOLON                       34
