[package]
name = "value_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
test = false

[lints]
workspace = true

[dependencies]
cheadergen.workspace = true
ffi.workspace = true
libc.workspace = true
query_error.workspace = true
redis-module.workspace = true
value.workspace = true
workspace_hack.workspace = true

[dev-dependencies]
redis_mock.workspace = true
redisearch_rs = { workspace = true, features = ["mock_allocator"] }
