[package]
name = "module_init_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
# This crate has no benches.
# Compiling a no-op bench binary can cause linking issues with C.
bench = false

[dependencies]
chrono.workspace = true
redis-module.workspace = true
tracing = { workspace = true }
tracing_redismodule.workspace = true
workspace_hack.workspace = true


[lints]
workspace = true
