# name: Pull Request Flow

# on:
#   pull_request:
#     types: [opened, synchronize, reopened, ready_for_review]

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   tests:
#     uses: ./.github/workflows/task-test.yml

#   pr-validation:
#     needs:
#       - tests
#     runs-on: ubuntu-latest
#     if: ${{ !cancelled() }}
#     steps:
#       - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
#         run: exit 1
