name: Merge a pull request
run-name: Validate ${{ github.ref_name }}

on:
  merge_group:
    types: [checks_requested]

concurrency:
  # This group identifies the PR by the tree ID of the head commit.
  # TODO: Replace with PR number of branch name once GH adds it to the event context
  group: ${{ github.workflow }}-${{ github.event.merge_group.head_commit.tree_id }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/task-test.yml
    secrets: inherit

  pr-validation:
    needs:
      - tests
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
