name: Nightly Flow

# Documentation: https://redislabs.atlassian.net/wiki/spaces/DX/pages/3967844669/RediSearch+CI+refactor

on:
  workflow_dispatch:
  schedule:
    - cron: "20 20 * * *"

# TODO: Use RedisJSON's `master` branch when testing on nightly

jobs:
  lint:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/task-lint.yml
    secrets: inherit

  test-all-platforms:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/flow-test.yml
    secrets: inherit
    with:
      platform: all
      architecture: all
      redis-ref: 3cd464263b03b425ffae2e23db24df3dc9346871
      job-test-config: '{"test": "QUICK=1", "coverage": "QUICK=1", "sanitize": "QUICK=1"}'
      options: ${{ vars.ENABLE_CODE_COVERAGE != 'false' && 'unit-tests,coordinator,standalone,rejson,coverage,sanitize' || 'unit-tests,coordinator,standalone,rejson,sanitize' }}

  micro-benchmarks:
    uses: ./.github/workflows/flow-micro-benchmarks.yml
    secrets: inherit


  notify-failure:
    needs: [lint, test-all-platforms, micro-benchmarks]
    if: failure()
    runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
    steps:
      - name: Notify Failure
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "failed_workflow": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}",
              "repository": "${{ github.repository }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_NIGHTLY_FAILED }}
