name: Nightly Flow

# Documentation: https://redislabs.atlassian.net/wiki/spaces/DX/pages/3967844669/RediSearch+CI+refactor

on:
  workflow_dispatch:
  schedule:
    - cron: "20 20 * * *"

# TODO: Use RedisJSON's `master` branch when testing on nightly

jobs:
  lint:
    permissions:
      contents: read
      packages: write
      id-token: write # OIDC role assumption for sccache S3 (used inside task-lint.yml)
      actions: write  # Swatinem/rust-cache read/write of GH cache (used inside task-lint.yml)
    uses: ./.github/workflows/task-lint.yml
    secrets: inherit

  test-all-platforms:
    permissions:
      contents: read
      packages: write
      id-token: write # OIDC role assumption for sccache S3 (used inside task-test.yml)
      actions: write  # Swatinem/rust-cache read/write of GH cache (used inside task-test.yml)
    uses: ./.github/workflows/flow-test.yml
    secrets: inherit
    with:
      platform: all
      architecture: all
      redis-ref: 3cd464263b03b425ffae2e23db24df3dc9346871
      job-test-config: '{"test": "QUICK=1", "coverage": "QUICK=1", "sanitize": "QUICK=1"}'
      options: ${{ vars.ENABLE_CODE_COVERAGE != 'false' && 'unit-tests,coordinator,standalone,rejson,coverage,sanitize' || 'unit-tests,coordinator,standalone,rejson,sanitize' }}

  micro-benchmarks:
    permissions:
      contents: read
      id-token: write # OIDC role assumption for sccache S3 (used inside flow-micro-benchmarks-runner.yml)
    uses: ./.github/workflows/flow-micro-benchmarks.yml
    secrets: inherit

  redis-build-sanity:
    permissions:
      contents: read
    uses: ./.github/workflows/flow-redis-build-sanity.yml
    secrets: inherit
    with:
      platform: ${{ github.ref_name == 'master' && 'ubuntu:latest' || 'all' }}
      architecture: ${{ github.ref_name == 'master' && 'x86_64' || 'all' }}
      redis-repository: redis/redis
      redis-ref: unstable
      redisearch-repository: ${{ github.repository }}
      redisearch-ref: ${{ github.sha }}

  notify-failure:
    needs: [lint, test-all-platforms, micro-benchmarks, redis-build-sanity]
    if: failure()
    runs-on: ubuntu-slim
    steps:
      - name: Notify Failure
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "failed_workflow": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}",
              "repository": "${{ github.repository }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_NIGHTLY_FAILED }}
