name: temporary testing

# This file is useful for triggering actions when you implement them.
# When the `branches-ignore` line is commented out, this workflow will run on every push.
# It is better to use this file for testing your new flows than creating a new one, to avoid cluttering the repo
# action tab with unused workflows.
# Don't worry about conflicts with other PRs - there is no "right" content of this file.
# Make sure the `branches-ignore` line is not commented out when you merge your PR.

on:
  push:
    # branches-ignore: ['**'] # ignore all branches. Comment this line to run your workflow below on every push.

jobs:
  get-latest-7-2-redis-tag:
    uses: ./.github/workflows/task-get-latest-tag.yml
    with:
      repo: redis/redis
      prefix: '7.2'

  test-macos:
    needs: [get-latest-7-2-redis-tag]
    uses: ./.github/workflows/flow-macos.yml
    secrets: inherit
    with:
      redis-ref: ${{ needs.get-latest-7-2-redis-tag.outputs.tag }}
      test-config: QUICK=1

  test-linux-x86_64:
    needs: [get-latest-7-2-redis-tag]
    uses: ./.github/workflows/flow-linux-platforms.yml
    secrets: inherit
    with:
      redis-ref: ${{ needs.get-latest-7-2-redis-tag.outputs.tag }}
      architecture: x86_64
      rejson-branch: '2.6'

  test-linux-aarch64:
    needs: [get-latest-7-2-redis-tag]
    uses: ./.github/workflows/flow-linux-platforms.yml
    secrets: inherit
    with:
      redis-ref: ${{ needs.get-latest-7-2-redis-tag.outputs.tag }}
      test-config: QUICK=1
      architecture: aarch64
      rejson-branch: '2.6'

  coverage:
    needs: [get-latest-7-2-redis-tag]
    uses: ./.github/workflows/task-test.yml
    secrets: inherit
    with:
      coverage: true
      get-redis: ${{ needs.get-latest-7-2-redis-tag.outputs.tag }}
      rejson-branch: '2.6'
      test-config: ''

  sanitize:
    needs: [get-latest-7-2-redis-tag]
    secrets: inherit
    uses: ./.github/workflows/task-test.yml
    with:
      get-redis: ${{ needs.get-latest-7-2-redis-tag.outputs.tag }}
      rejson-branch: '2.6'
      test-config: ''
      san: address
