name: labeler

on: [pull_request]

# Grant the token the reusable workflow needs (it labels the PR).
permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    uses: redislabsdev/redisearch-ci-common/.github/workflows/pr-size-label.yml@5d3485c26571f609cec76dad6ad0b27bd1b1d0d7 # v1.0.1
