name: Start EC2 Runner

on:
  workflow_call:
    inputs:
      ec2-image-id:
        description: 'EC2 AMI ID to start as a GitHub Actions runner'
        type: string
        required: true
      ec2-instance-type:
        description: 'EC2 instance type for the GitHub Actions runner'
        type: string
        required: true
    outputs:
      label:
        description: 'GitHub Actions runner label'
        value: ${{ jobs.start-runner.outputs.label }}
      ec2-instance-id:
        description: 'Started EC2 instance ID'
        value: ${{ jobs.start-runner.outputs.ec2-instance-id }}
    secrets:
      PERFORMANCE_EC2_ACCESS_KEY:
        required: true
      PERFORMANCE_EC2_SECRET_KEY:
        required: true
      PERFORMANCE_EC2_AWS_REGION:
        required: true
      AWS_EC2_SUBNET_ID_BENCHMARK:
        required: true
      AWS_EC2_SG_ID_BENCHMARK:
        required: true
      GH_PR_APP_PRIVATE_KEY:
        required: true

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-slim
    env:
      TAGS: | # Make sure there is no trailing comma!
        [
          {"Key": "Name",         "Value": "redisearch-ci-runner"},
          {"Key": "Environment",  "Value": "CI"},
          {"Key": "Run ID",       "Value": "${{ github.run_id }}"},
          {"Key": "PR",           "Value": "${{ github.event.number }}"},
          {"Key": "Owner",        "Value": "${{ github.actor }}"},
          {"Key": "Project",      "Value": "${{ github.repository }}"}
        ]
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.PERFORMANCE_EC2_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PERFORMANCE_EC2_SECRET_KEY }}
          aws-region: ${{ secrets.PERFORMANCE_EC2_AWS_REGION }}

      - name: Generate GitHub App token
        id: generate-app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.GH_PR_APP_ID }}
          private-key: ${{ secrets.GH_PR_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
          permission-administration: write

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2.6.1
        with:
          mode: start
          github-token: ${{ steps.generate-app-token.outputs.token }}
          ec2-image-id: ${{ inputs.ec2-image-id }}
          ec2-instance-type: ${{ inputs.ec2-instance-type }}
          subnet-id: ${{ secrets.AWS_EC2_SUBNET_ID_BENCHMARK }}
          security-group-id: ${{ secrets.AWS_EC2_SG_ID_BENCHMARK }}
          aws-resource-tags: ${{ env.TAGS }}
