name: Lint

on:
  workflow_call:

jobs:
  ci:
    name: Lint on Ubuntu
    runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    permissions:
      contents: read
    steps:
      # Generate repo App token
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_CI_APP_ID }}
          private-key: ${{ secrets.GH_CI_PRIVATE_KEY }}
          owner: redislabsdev
          repositories: |
            Redis
            RediSearchEnterprise
            rust-speedb
            speedb-ent
            redismodule-rs

      # Full checkout, with the above token for private repos (and current)
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}

      # Configure Git/Cargo to authenticate with private repos using the app token
      - name: Configure Git for private Cargo dependencies
        uses: ./.github/actions/configure-cargo-auth
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Install Clippy and Rustfmt
        run: rustup component add clippy rustfmt

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      # Lint Rust code
      - name: Lint (Rust)
        env:
          TERM: xterm-256color
        run: ./build.sh lint

      # Lint C++ code
      - name: Lint (C++)
        run: ./build.sh lint-vecsim
